In [3]:
p=[1,2]

In [4]:
p

[1, 2]

In [6]:
print (p)

[1, 2]

In [7]:
type(p)

list

In [345]:
p=['zvxb']

type(p)

list

In [346]:
p='bubs'

type(p)

str

In [13]:
p=1,2,3,4

In [14]:
type(p)

tuple

In [15]:
p=1

In [16]:
type(p)

int

In [17]:
m=0.12

In [18]:
type(m)

float

In [19]:
n=1.2,2.1,2.3,5.2

In [20]:
type(n)

tuple

In [22]:
v='true'

In [23]:
type(v)

str

In [26]:
x=()

In [27]:
type(x)

tuple

In [28]:
 o=[1,'vin','pune',454545,'test@gmi.com']

In [29]:
print(o)

[1, 'vin', 'pune', 454545, 'test@gmi.com']

In [30]:
o.insert(3,'brnch')

In [34]:
print(o)

[1, 'vin', 'pune', 'brnch', 454545, 'yers', 'test@gmi.com']

In [33]:
o.insert(-1,'yers')

In [35]:
print(o)

[1, 'vin', 'pune', 'brnch', 454545, 'yers', 'test@gmi.com']

In [36]:
o.append('time')

In [37]:
print(o)

[1, 'vin', 'pune', 'brnch', 454545, 'yers', 'test@gmi.com', 'time']

In [38]:
print(o)

[1, 'vin', 'pune', 'brnch', 454545, 'yers', 'test@gmi.com', 'time']

In [47]:
person=[101,'snow','pune']
dept=['IT',1324]
person.extend(dept)
print(person)

[101, 'snow', 'pune', 'IT', 1324]

In [51]:
p=20>23
type(p)

bool

In [55]:
o=None
type(o)

NoneType

In [1]:
o

NameError: name 'o' is not defined

In [2]:
ptint(o)

NameError: name 'ptint' is not defined

In [3]:
o=[1,2,3,4,5]

In [10]:
print(o)

[1, 2, 8, 3, 4, 5]

In [6]:
o.insert(2,8)

o.append(7)

o.append('rima')

In [11]:
o

[1, 2, 8, 3, 4, 5]

In [12]:
o

[1, 2, 8, 3, 4, 5]

In [13]:
n=['a','c','v','n']

In [14]:
n

['a', 'c', 'v', 'n']

In [15]:
n.append('m')

In [16]:
n

['a', 'c', 'v', 'n', 'm']

In [17]:
n.insert(2,'e')

In [18]:
n

['a', 'c', 'e', 'v', 'n', 'm']

In [20]:
m=[1,2,3]

In [21]:
m

[1, 2, 3]

In [22]:
n.extend(m)

In [23]:
print(n)

['a', 'c', 'e', 'v', 'n', 'm', 1, 2, 3]

In [24]:
print(m)

[1, 2, 3]

In [25]:
m.extend(n)

In [26]:
print(n)

['a', 'c', 'e', 'v', 'n', 'm', 1, 2, 3]

In [27]:
print(m)

[1, 2, 3, 'a', 'c', 'e', 'v', 'n', 'm', 1, 2, 3]

In [28]:
m[5]

'e'

In [29]:
m[2]

3

In [30]:
m.remove(2)

In [31]:
print(m)

[1, 3, 'a', 'c', 'e', 'v', 'n', 'm', 1, 2, 3]

In [32]:
m.remove(z)

NameError: name 'z' is not defined

In [33]:
m.pop(3)

'c'

In [34]:
print(m)

[1, 3, 'a', 'e', 'v', 'n', 'm', 1, 2, 3]

In [35]:
m.pop(-1)

3

In [37]:
print(m)

[1, 3, 'a', 'e', 'v', 'n', 'm', 1, 2]

In [39]:
m.pop()

2

In [40]:
print(m)

[1, 3, 'a', 'e', 'v', 'n', 'm', 1]

In [41]:
a=[1,2,3]

In [46]:
print(a)

[1, 2, 3]

In [47]:
a.clear()

In [48]:
print(a)

[]

In [49]:
q=[1,1,1,2,2,3,3,3,3,3,3,4]

In [50]:
q.count(3)

6

In [51]:
q.index(2)

3

In [12]:
acc=[2,4,5,6]
bcc=[2,4,6,7]
acc+bcc

[2, 4, 5, 6, 2, 4, 6, 7]

In [13]:
print(acc.extend(bcc))

None

In [14]:

print(acc)

[2, 4, 5, 6, 2, 4, 6, 7]

In [20]:
acv=[1,7,2,8,3,4]
print(acv.sort())

None

In [242]:
m.reverse()

In [243]:
print(m)

[1, 'm', 'n', 'v', 'e', 'a', 3, 1]

In [ ]:
====================================
SET
====================================

In [1]:
s={1,2,3,4,'sam','kite','life'}

In [2]:
print(s)

{1, 2, 3, 4, 'life', 'sam', 'kite'}

In [3]:
type(s)

set

In [248]:
s.add(450)

In [249]:
print(s)

{1, 2, 3, 4, 450, 'life', 'kite', 'sam'}

In [252]:
s.update(200,680,741,'drag','crab','zebra')

TypeError: 'int' object is not iterable

In [ ]:
Why does s.update(200,680) give an error, but s.update([200,680]) works?

update() expects one or more iterables as arguments. Lists, tuples, sets, strings, and 
dictionaries are iterable, so Python can loop through them and add each element to the 
set. Integers are not iterable, so passing an integer directly to update() raises a 
TypeError. To add a single integer, use add(), and to add multiple integers, pass them 
inside an iterable like a list or tuple.

In [253]:
s.update('lag','man')

In [254]:
print(s)

{1, 2, 3, 4, 450, 'l', 'a', 'kite', 'g', 'sam', 'm', 'life', 'n'}

In [255]:
s.update(145,784,125496,'dam','gag')

TypeError: 'int' object is not iterable

In [256]:
s.update(11,22)

TypeError: 'int' object is not iterable

In [258]:
s.update({145,784,125496,'dam','gag'})

In [259]:
print(s)

{1, 2, 3, 4, 450, 'l', 'a', 'kite', 'g', 'sam', 784, 145, 'gag', 'm', 'life', 125496, 'n', 'dam'}

In [262]:
s.add({2500})

TypeError: unhashable type: 'set'

In [264]:
s.update((145,784,125496,'dam','gag'))----

print(s)

In [265]:
print(s)

{1, 2, 3, 4, 450, 'l', 'a', 'kite', 'g', 'sam', 784, 145, 'gag', 'm', 'life', 125496, 'n', 'dam'}

In [266]:
s.remove(3)

In [267]:
print(s)

{1, 2, 4, 450, 'l', 'a', 'kite', 'g', 'sam', 784, 145, 'gag', 'm', 'life', 125496, 'n', 'dam'}

In [268]:
s.remove('crzy')

KeyError: 'crzy'

In [269]:
s.discard(1)

In [270]:
print(s)

{2, 4, 450, 'l', 'a', 'kite', 'g', 'sam', 784, 145, 'gag', 'm', 'life', 125496, 'n', 'dam'}

In [271]:
s.discard( 'bb')

In [272]:
print(s)

{2, 4, 450, 'l', 'a', 'kite', 'g', 'sam', 784, 145, 'gag', 'm', 'life', 125496, 'n', 'dam'}

In [273]:
s.pop()

2

In [274]:
print(s)

{4, 450, 'l', 'a', 'kite', 'g', 'sam', 784, 145, 'gag', 'm', 'life', 125496, 'n', 'dam'}

user1 =s.pop()

In [277]:
user1 = s.pop()

In [278]:
print(s)

{'a', 'kite', 'g', 'sam', 784, 145, 'gag', 'm', 'life', 125496, 'n', 'dam'}

In [280]:
user3 =s.pop()

In [282]:
Z={1,2,3,4}
Y={3,4,5,6}

In [283]:
Z.union(Y)

{1, 2, 3, 4, 5, 6}

In [284]:
Z.intersection(Y)

{3, 4}

In [286]:
Z.difference(Y)

{1, 2}

In [287]:
Y.difference(Z)

{5, 6}

In [291]:
Z.symmetric_difference(Y)

{1, 2, 5, 6}

In [292]:
f={'a','b','c','d'}
g={'b','c'}

In [293]:
f.issuperset(g)

True

In [294]:
g.issubset(f)

True

In [295]:
b=1,2,3

In [296]:
print(b)

(1, 2, 3)

In [297]:
c=5,6,7

In [298]:
print(c)

(5, 6, 7)

In [299]:
h=[1,2,3]

In [300]:
k=[4,5,6]

In [ ]:
==========================
dict
==========================

In [1]:
d={'id':1,'name':'Sam','age':26,'bg':'B+'
}

In [2]:
type(d)

dict

In [3]:
j={'a':10,'b':20,'a':30}

In [4]:
print(j)

{'a': 30, 'b': 20}

In [5]:
d['age']

26

In [6]:
d['dept']

KeyError: 'dept'

In [7]:
d.get['age']

TypeError: 'builtin_function_or_method' object is not subscriptable

In [8]:
d.get('age')

26

In [9]:
d.get('dept','no key present')

'no key present'

In [12]:
d['dept']='Admin'

In [13]:
print(d)

{'id': 1, 'name': 'Sam', 'age': 26, 'bg': 'B+', 'dept': 'Admin'}

In [14]:
d['id']=01cnuu

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (2711547742.py, line 1)

In [15]:
d['id']=11

In [16]:
print(d)

{'id': 11, 'name': 'Sam', 'age': 26, 'bg': 'B+', 'dept': 'Admin'}

In [17]:
d.update({'a':100,'b':200,'c':300})

In [18]:
print(d)

{'id': 11, 'name': 'Sam', 'age': 26, 'bg': 'B+', 'dept': 'Admin', 'a': 100, 'b': 200, 'c': 300}

In [19]:
d.pop('a')

100

In [20]:
print(d)

{'id': 11, 'name': 'Sam', 'age': 26, 'bg': 'B+', 'dept': 'Admin', 'b': 200, 'c': 300}

In [22]:
d.popitem()

('c', 300)

In [25]:
d['name']='samruddhi'

In [26]:
print(d)

{'id': 11, 'name': 'samruddhi', 'age': 26, 'bg': 'B+', 'dept': 'Admin', 'b': 200}

In [27]:
d.popitem()

('b', 200)

In [28]:
print(d)

{'id': 11, 'name': 'samruddhi', 'age': 26, 'bg': 'B+', 'dept': 'Admin'}

In [29]:
print(d.keys())

dict_keys(['id', 'name', 'age', 'bg', 'dept'])

In [30]:
print(d.items())

dict_items([('id', 11), ('name', 'samruddhi'), ('age', 26), ('bg', 'B+'), ('dept', 'Admin')])

In [31]:
print(d.values())

dict_values([11, 'samruddhi', 26, 'B+', 'Admin'])

In [36]:
dict.fromkeys(d,0)###########

{'id': 0, 'name': 0, 'age': 0, 'bg': 0, 'dept': 0}

In [37]:
print(dict.fromkeys(d))

{'id': None, 'name': None, 'age': None, 'bg': None, 'dept': None}

In [49]:
d.setdefault('name','sam')

'samruddhi'

In [50]:
print(d)

{'id': 11, 'name': 'samruddhi', 'age': 26, 'bg': 'B+', 'dept': 'Admin'}

In [51]:
d.setdefault('school','lfc')

'lfc'

In [52]:
print(d)

{'id': 11, 'name': 'samruddhi', 'age': 26, 'bg': 'B+', 'dept': 'Admin', 'school': 'lfc'}

In [ ]:
========================
string
===========================

In [54]:
p='strip '

In [55]:
p.strip()

'strip'

In [56]:
p.lstrip()

'strip '

In [58]:
q='  strip  '

In [60]:
q.rstrip()

'  strip'

In [61]:
r='$strip$'

In [63]:
r.strip('$')

'strip'

In [66]:
s='$strip#$'

In [67]:
s.strip('#$')

'strip'

In [68]:
t='left set'

In [69]:
t.strip('left')

' s'

In [70]:
print(t)

left set

In [71]:
u='leftstrip'

In [72]:
u.strip('left')

'strip'

In [73]:
print(p)

strip

In [75]:
v='copper_2025_daily_prouduct_csv'

In [76]:
v.find('2025')

7

In [77]:
v.find('sam')

-1

In [90]:
if v.find('sam') == -1:
    print('not present')
else:
    print('present')

IndentationError: expected an indented block after 'if' statement on line 1 (2231485581.py, line 2)

In [88]:
if v.find('sam') == -1:  # Added missing colon after the if condition
    print('not present')  # Fixed indentation
else:  # Fixed indentation for else statement
    print('present')  # Fixed indentation

not present

In [92]:
if v.find('copper') == -1:  # Added missing colon after the if condition
    print('not present')  # Fixed indentation
else:  # Fixed indentation for else statement
    print('present')  # Fixed indentation

present

In [93]:
w=['keshav','patil']

In [97]:
'@'.join(w) #to join

'keshav@patil'

In [96]:
' '.join(w)

'keshav patil'

In [98]:
num1=input("enter the num 1") #num act as strings
num2=input("enter the num 2")
result=num1+num2
print(result)

enter the num 1 10
enter the num 2 20

1020

In [100]:
num3=int(input("enter the num 3")) #if u want toa use int word
num4=int(input("enter the num 4"))
result=num3+num4
print(result)

enter the num 3 10
enter the num 4 20

30

In [102]:
#format: to insert dynamic value into string
a=10 
b=20
c=a+b
"Addition of {} and {} is {}".format(a,b,c)

'Addition of 10 and 20 is 30'

In [106]:
x='python'
x.zfill(10)

'0000python'

In [107]:
x.zfill(1)

'python'

In [108]:
x.zfill(15)

'000000000python'

In [29]:
yy='102'
print(yy)
type(yy)

102

str

In [116]:
z=int '102'
print(int(z))
type(z)

SyntaxError: invalid syntax (1046247427.py, line 1)

In [121]:
a='103'
int(a)

103

In [123]:
b='10.2'
int(float(b))

10

In [4]:
cc=[10,20,30,45,56,56]
tuple(cc)

(10, 20, 30, 45, 56, 56)

In [128]:
d=[1,1,1,2,3,3,4,5,5,6]
set(d)

{1, 2, 3, 4, 5, 6}

In [155]:
zz=[11,11,11,2,3,44,44,44,5,5,5,6,7]
zz=list(set(zz))
print(zz)

[2, 3, 5, 6, 7, 11, 44]

In [160]:
aa=10
print(aa)
type(aa)

10

int

In [158]:
aa=str(aa)
print(aa)
type(aa)

10

str

In [32]:
tuple=(23,32,56)  ###############imp
tuple=list(tuple)
print(tuple)
type(list(tuple))

[23, 32, 56]

list

In [163]:
tuple.append(100)
print(tuple)

[23, 32, 56, 100, 100]

In [131]:
#STRING
e="python"
e.upper()

'PYTHON'

In [132]:
f='LIFE'
f.lower()

'life'

In [133]:
g='the book on life'
g.title()

'The Book On Life'

In [134]:
h='the book on life'
h.capitalize()

'The book on life'

In [140]:
i='PyTHon'
i.swapcase()

'pYthON'

In [142]:
p='pythonn'
p.count('n')

2

In [143]:
j='samruddhikhadtare'
j.count('a')

3

In [145]:
k='life is grat and we should enjoy it'
k.index('enjoy')

27

In [147]:
email='test@gmail.com'
email.startswith('test')

True

In [148]:
email.endswith('@gmail.com')

True

In [164]:
=====================
#OPERATORS                                                                          
====================

In [167]:
A=1
B=2
C=A+B
print(C)

3

In [168]:
D=1.5
E=2.5
F=D+E
print(F)

4.0

In [33]:
G=12
H=2.5
I=G+H
print(I)

14.5

In [170]:
J=1
K=3
J*K

3

In [173]:
L=[1,2,3,4,5] #LIST*INT=REPEATION
M=3
print(L*M)
#########
N=(1,2,3)
O=2
print(N*O)
############

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
(1, 2, 3, 1, 2, 3)

In [174]:
P='1,2,3'
Q=2
P*Q

'1,2,31,2,3'

In [175]:
P='1','2','3'
Q=2
P*Q

('1', '2', '3', '1', '2', '3')

In [176]:
5%2  #modulus

1

In [177]:
(1,2,3)*5

(1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)

In [178]:
5/2 #Normal divison

2.5

In [179]:
5//2 #floor divison

2

In [181]:
2**5 #exponent this is 2^5

32

In [185]:
R=[1,0,1,1,0]  #####logical operators --and , or , not
S=[1,1,0,0,1]
print(R or S)
print(R and S)

[1, 0, 1, 1, 0]
[1, 1, 0, 0, 1]

In [187]:
(1,1,0,0) and (1,0,1,0)

(1, 0, 1, 0)

In [188]:
(1,1,0,0) or (1,0,1,0)

(1, 1, 0, 0)

In [190]:

 # Try these:
5 and 3

3

In [191]:
0 or 7

7

In [193]:
# Practice with these:
a = True
b = False
print(a and b)
print(a or b)
print(not a)


print(not b)

False
True
False
True

In [195]:
## Membership
T=[10, 'phthon',2000] #list
10 in T

True

In [196]:
U={'ID':101,'NAME':'SAMRUDDHI','DEPT':'CLASS1'}#dict
'ID'in U #to find keys

True

In [197]:
101 in U.values() #to finde values

True

In [201]:
z=500  #identity operators is, not is
x=500
print(x==z)
print(x is z)

True
False

In [204]:
zz=xx=500
print(xx==zz)
print(xx is zz)

True
True

In [205]:
10&40

8

In [208]:
print(bin(10))  ###bitwise oper
print(bin(40))

0b1010
0b101000

In [207]:
bin(8)

'0b1000'

In [211]:
int('0b101000',2) ##However, there's still an issue with your code 
#because when you specify the base as `2`, you shouldn't include the `'0b'` prefix in the string,
#as Python expects just the binary digits.
#int('101000', 2)
#int('0b101000', 0)
#int('0b101000')

40

In [212]:
int('101000',2)

40

In [214]:
1040

1040

In [215]:
==================================
##### Flow control statements#######
====================================

In [51]:
##simpleif
filename=input("ENTER THE FILENAME")
if filename.endswith('.csv'):
    print("valid file:{processing}")
print("wrong file")

ENTER THE FILENAME aaa.xlsx

wrong file

In [2]:
filename=input("ENTER THE FILENAME")
if filename.endswith('.csv'):
    print("valid file:{processing}")
print("wrong file")

ENTER THE FILENAME sales.csv

valid file:{processing}

In [1]:
10+20

30

In [22]:
#zip
t1=[1,2,3]
t2=['a','b','c']
dict(zip(t1,t2))

{1: 'a', 2: 'b', 3: 'c'}

In [23]:
list(zip(t1,t2))

[(1, 'a'), (2, 'b'), (3, 'c')]

In [24]:
set(zip(t1,t2))

{(1, 'a'), (2, 'b'), (3, 'c')}

In [25]:
t11=[1,2,3]
t22=['a','b','c','d','e']
dict(zip(t11,t22))

{1: 'a', 2: 'b', 3: 'c'}

In [26]:
dict(zip(t22,t11))

{'a': 1, 'b': 2, 'c': 3}

In [28]:
column=['id','name','salary']
data=[101,'sam',2800000]
dict(zip(column,data))

{'id': 101, 'name': 'sam', 'salary': 2800000}

In [38]:
print(1)
print(2)
print(3)
a=50
if a>=100:
    print(5)

1
2
3

In [39]:
print(1)
print(2)
print(3)
a=500
if a>=100:
    print(5)

1
2
3
5

In [58]:
username=input('enter your username')
if username=='samruddhi123':
    print('enter password')
    else :
        print('wrong password')
password=input('enter password')
            if password==lifeline@123:
                        print('login sucessfull')
                else: 
                        print('wrong password')
print('wrong password or username')

IndentationError: unindent does not match any outer indentation level (<string>, line 9)

In [61]:
print('1')
print('2')
a_value=70
if a_value>=50:
    print('3')
    print('4')
print('5')
print('6')

1
2
3
4
5
6

filename_ = 'copper_daily_prd.pdf'

In [70]:
filename_ = 'copper_daily_prd.pdf'
if filename_.endswith(".csv"):
    print('valid file -- processing -- {}'.format(filename_))
print('rest code')

rest code

#if else

In [73]:
num = int(input("enetr the num:"))
if num%2==0 :
    print('numis even')
else:
    print("num is odsd")

enetr the num: 20

numis even

In [ ]:
client:
file-- copper and csv and it should belong to 2026-- valid processing

In [79]:
filename_1 = "copper_daily_prd_2026.csv"

In [81]:
if filename_1.startswith('copper') and filename_1.endswith(".csv") and '2026' in filename_1:
    print('valid file-- processing{}'.format(filename_1))
else:
    print('invalid file reciecved')

valid file-- processingcopper_daily_prd_2026.csv

In [ ]:
#if else ladder
when we have more than 2 comdititons

In [ ]:
csv :
csv-- read and write logic
pdf--
xlsx

invalid file

In [85]:
filenamee= input("enter the filenamee")
if filenamee.endswith(".csv"):
    print('csv file recieved--processing')
elif filenamee.endswith(".pdf"):
    print('csv file recieved--processing')
elif filenamee.endswith(".xlsx"):
    print("excel file received")
else:
    print("invalid file")

enter the filenamee copper.xlsx

excel file received

In [ ]:
product --pen, pencil,rubber, notebook
region code--- solapur 1, p[une 2, mumbai 3,jalgaon 4 
payment--- upi, cc, net, imops,

In [2]:
product=input("product name")
payment=input("payment mathod")
if product.startswith("pen") and payment.startswith("upi"):
    print("purchased pen with upi")

product name pen
payment mathod upi

okay

In [3]:
if country=='IND':
    if state=="MH":
        if city=='solapur':
            if area=='Antrolnikar naghar':
                pincode
if country=='USA':
    if state =="nbewyork":
        if city=="buffalow":
            pincode

NameError: name 'country' is not defined

In [10]:
filname=input("enter the filename")
if filname.endswith(".csv"):
    if filname.startswith("copper"):
        print("copper csv logic executed")
    elif filname.startswith("silver"):
        print("silver csv file executed")
    elif filname.startswith("bauxite"):
        print("bauxite csv file executed")
    else:
        print("invalid csv file")
if filname.endswith(".pdf"):
    if filname.startswith("copper"):
        print("copper pdf file executed")
    elif filname.startswith("silver"):
        print("silver pdf file executed ")
    elif filname.startswith("bauxite"):
        print("bauxite podf executed")
    else:
        print("invalid pdf file")
if filname.endswith(".xlsx"):
    if filname.startswith("copper"):
        print("copper xlsx file executed")
    elif filname.startswith("ironore"):
        print("ironore xlsx file executed")
    elif filname.startswith('aluminiumore'):
        print("aluminium ore xlsx file execute")
    else:
        print('invalid xlsx file')

enter the filename copper.pdf

copper pdf file executed

In [15]:
filname=input("enter the filename")
if filname.endswith(".csv"):
    if filname.startswith("copper"):
        if '2024' in filname:
            print("copper csv 2024 logic executed")
        if '2025' in filname:
            print("copper csv 2025 logic executed")
        if '2026' in filname:
            print("copper csv 2026 logic executed")
    elif filname.startswith("silver"):
        if '2024' in filname:
            print("silver csv 2024 logic executed")
        if '2025' in filname:
            print("silver csv 2025 logic executed")
        if '2026' in filname:
            print("silver csv 2026 logic executed")
    elif filname.startswith("bauxite"):
         if '2024' in filname:
            print("bauxite csv 2024 logic executed")
         if '2025' in filname:
            print("bauxite csv 2025 logic executed")
         if '2026' in filname:
            print("bauxite csv 2026 logic executed")
    else:
        print("invalid csv file")
if filname.endswith(".pdf"):
    if filname.startswith("copper"):
        if '2024' in filname:
            print("copper pdf 2024 logic executed")
        if '2025' in filname:
            print("copper pdf 2025 logic executed")
        if '2026' in filname:
            print("copper pdf 2026 logic executed")
    elif filname.startswith("silver"):
        if '2024' in filname:
            print("silver pdf 2024 logic executed")
        if '2025' in filname:
            print("silver pdf 2025 logic executed")
        if '2026' in filname:
            print("silver pdf 2026 logic executed")
    elif filname.startswith("bauxite"):
        if '2024' in filname:
            print("bauxite pdf 2024 logic executed")
        if '2025' in filname:
            print("bauxite pdf 2025 logic executed")
        
        if '2026' in filname:
            print("bauxite pdf 2026 logic executed")
    else:
        print("invalid pdf file")
if filname.endswith(".xlsx"):
    if filname.startswith("copper"):
         if '2024' in filname:
            print("copper xlsx 2024 logic executed")
         if '2025' in filname:
            print("copper xlsx 2025 logic executed")
         if '2026' in filname:
            print("copper xlsx 2026 logic executed")
    elif filname.startswith("ironore"):
         if '2024' in filname:
            print("ironore xlsx 2024 logic executed")
         if '2025' in filname:
            print("ironore xlsx 2025 logic executed")
         if '2026' in filname:
            print("ironore xlsx 2026 logic executed")
    elif filname.startswith('aluminiumore'):
         if '2024' in filname:
            print("aluminiumore xlsx 2024 logic executed")
         if '2025' in filname:
            print("aluminiumore xlsx 2025 logic executed")
         if '2026' in filname:
            print("aluminiumore xlsx 2026 logic executed")
    else:
        print('invalid xlsx file')

enter the filename ironore2025.xlsx

ironore xlsx 2025 logic executed

In [16]:
##forloop
code duplicate----less redundant=less duplicate
spcae
time complexity

1. for loop
2.while loop

note: do while loop not present in python

In [ ]:
for loopvar in DS|seq:

In [20]:
pylist=['python','java','scala','pyspark','hadoop']

In [ ]:
outpiut=['PHYTHON','JAVA','PYSPARK','HADOOP']#iteration use

In [ ]:
for (#dont use i,j,k l here)

In [21]:
for element in pylist: #element is called loop variable
    print(element)

python
java
scala
pyspark
hadoop

In [26]:
upper_list =[] #created empty list
for element in pylist:
        upper_list.append(element.upper())
print(upper_list)

['PYTHON', 'JAVA', 'SCALA', 'PYSPARK', 'HADOOP']

In [27]:
len_element_list=[]
for element in pylist:
    len_element_list.append(len(element))
print(len_element_list)

[6, 4, 5, 7, 6]

In [ ]:
#fetch only element whose len is greater than 6
len_element_list=[]
for element in pylist:
    len_element_list.append(len(element))>6
print(len_element_list)

In [30]:
print('hello') #sends cursor to next line
print('welcome')
print("bye")

hello
welcome
bye

In [23]:
print('hello',end=' ')#using ,end='space' wecan print all in one line
print('welcome',end=' ')
print("bye")

hello welcome bye

In [ ]:
#fetch only element whose len is greater than 6

In [ ]:
for with conditional statement

In [31]:
len_element_list =[]
for element in pylist:
    if len(element)>=6:
        len_element_list.append(element)
print(len_element_list)

['python', 'pyspark', 'hadoop']

In [45]:
emails = ['python@gmail.com','hadoop@yahoo.com','scala@gmail.com','sam@yahoo.com','dyasgvduashd','bfuhfiashf','sample@yahoo.com']

In [46]:
gmail_list = []
yahoo_list=[]
invalid_list=[]
for email in emails:
    if email.endswith('@gmail.com'):
        gmail_list.append(email)
    elif email.endswith('@yahoo.com'):
        yahoo_list.append(email)
    else:
        invalid_list.append(email)
print("Gmail list:",gmail_list)
print("yahoo list:",yahoo_list)
print("invalid list:",invalid_list)

Gmail list: ['python@gmail.com', 'scala@gmail.com']
yahoo list: ['hadoop@yahoo.com', 'sam@yahoo.com', 'sample@yahoo.com']
invalid list: ['dyasgvduashd', 'bfuhfiashf']

In [52]:
num=[45,464,546,5496,85,34,'dsdfd','ffd','dfdf','uyrti','grgh',48,45,96,35,1658]

In [54]:
numeric_ids = []
for element in num:
    if str(element).isnumeric(): #isnumeric is of string DS e cant use for int , so use str
        numeric_ids.append(element)
print('mumeric ids:',numeric_ids)

mumeric ids: [45, 464, 546, 5496, 85, 34, 48, 45, 96, 35, 1658]

In [55]:
mixed='356fbkjoydh80o%^&^fgyf&*^*hgy6532168970gyfdyv%$^%$'

In [58]:
char_list=[]
num_list=[]
special_char=[]
for char in mixed:
    if str(char).isnumeric():
        num_list.append(char)
    elif char.isalpha():
        char_list.append(char)
    else:
        special_char.append(char)
print("num list:",num_list)
print("char list",char_list)
print("special char list:",special_char)

num list: ['3', '5', '6', '8', '0', '6', '5', '3', '2', '1', '6', '8', '9', '7', '0']
char list ['f', 'b', 'k', 'j', 'o', 'y', 'd', 'h', 'o', 'f', 'g', 'y', 'f', 'h', 'g', 'y', 'g', 'y', 'f', 'd', 'y', 'v']
special char list: ['%', '^', '&', '^', '&', '*', '^', '*', '%', '$', '^', '%', '$']

In [63]:
ppp=[45,89,26,71,56,15,15,7,98,265,28574,185,87,16,64]

In [64]:
dd={}
for key in ppp:
    if key in dd:
        dd[key]+=1
    else:
        dd[key]=1
print(dd)

{45: 1, 89: 1, 26: 1, 71: 1, 56: 1, 15: 2, 7: 1, 98: 1, 265: 1, 28574: 1, 185: 1, 87: 1, 16: 1, 64: 1}

In [65]:
ppp1='gfjdgiafigfdhbfhdtyrfgdbfdhgfahdbcvjahiyurjfbc vgyuu'

In [66]:
dd1={}
for key in ppp1:
    if key in dd1:
        dd1[key]+=1
    else:
        dd1[key]=1
print(dd1)

{'g': 6, 'f': 8, 'j': 3, 'd': 6, 'i': 3, 'a': 3, 'h': 5, 'b': 4, 't': 1, 'y': 3, 'r': 2, 'c': 2, 'v': 2, 'u': 3, ' ': 1}

In [67]:
data="As digital infrastructure becomes more embedded in everyday life, cybersecurity has emerged as a critical concern. The complexity of modern information systems—and the societal functions they underpin—has introduced new vulnerabilities. Systems that manage essential services, such as power grids, electoral processes, and finance, are particularly sensitive to security breaches"

In [69]:
dd22={}
for key in data.split():
    if key in dd22:
        dd22[key]+=1
    else:
        dd22[key]=1
print(dd22)

{'As': 1, 'digital': 1, 'infrastructure': 1, 'becomes': 1, 'more': 1, 'embedded': 1, 'in': 1, 'everyday': 1, 'life,': 1, 'cybersecurity': 1, 'has': 1, 'emerged': 1, 'as': 2, 'a': 1, 'critical': 1, 'concern.': 1, 'The': 1, 'complexity': 1, 'of': 1, 'modern': 1, 'information': 1, 'systems—and': 1, 'the': 1, 'societal': 1, 'functions': 1, 'they': 1, 'underpin—has': 1, 'introduced': 1, 'new': 1, 'vulnerabilities.': 1, 'Systems': 1, 'that': 1, 'manage': 1, 'essential': 1, 'services,': 1, 'such': 1, 'power': 1, 'grids,': 1, 'electoral': 1, 'processes,': 1, 'and': 1, 'finance,': 1, 'are': 1, 'particularly': 1, 'sensitive': 1, 'to': 1, 'security': 1, 'breaches': 1}

In [71]:
print({word:data.split().count(word) for word in data.split()})
#dont writethis syntax no inbuilt functions |menthods to be used

{'As': 1, 'digital': 1, 'infrastructure': 1, 'becomes': 1, 'more': 1, 'embedded': 1, 'in': 1, 'everyday': 1, 'life,': 1, 'cybersecurity': 1, 'has': 1, 'emerged': 1, 'as': 2, 'a': 1, 'critical': 1, 'concern.': 1, 'The': 1, 'complexity': 1, 'of': 1, 'modern': 1, 'information': 1, 'systems—and': 1, 'the': 1, 'societal': 1, 'functions': 1, 'they': 1, 'underpin—has': 1, 'introduced': 1, 'new': 1, 'vulnerabilities.': 1, 'Systems': 1, 'that': 1, 'manage': 1, 'essential': 1, 'services,': 1, 'such': 1, 'power': 1, 'grids,': 1, 'electoral': 1, 'processes,': 1, 'and': 1, 'finance,': 1, 'are': 1, 'particularly': 1, 'sensitive': 1, 'to': 1, 'security': 1, 'breaches': 1}

In [ ]:
#min|max

In [77]:
pq=[458,5,8997,32,65,1,98,653,298,75,111,-1]

In [78]:
min_pq=pq[0] #here 0 is index no 
for element in pq:
    if min_pq > element:
        min_pq=element
print(min_pq)

-1

In [79]:
max_pq=pq[0] #here 0 is index no 
for element in pq:
    if max_pq < element:
        max_pq=element
print(max_pq)

8997

In [80]:
emp111={'id':101,'name':'sam','city':'Pune','sal':56449}

In [82]:
for key in emp111.keys():
    if key in ['id','sal']:
        print(key,emp111[key])

id 101
sal 56449

In [85]:
#range()- itis use to generate sequence ofmatters
#range(start,stop-1,step)

In [88]:
for i in range(1,12,1):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [92]:
for i in range(50,101,5):
    print(i)

50
55
60
65
70
75
80
85
90
95
100

In [93]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1

In [101]:
for i in range(-6,-12,-2):
 print(i)

-6
-8
-10

In [103]:
for i in range(-6,-1,2):
 print(i)

-6
-4
-2

In [107]:
wanttoreverse='python'

In [110]:
for i in range(5,-1,-1): #this is hardcode
    print(wanttoreverse[i])

n
o
h
t
y
p

In [111]:
for i in range(5,-1,-1): 
    print(wanttoreverse[i],end='') #to bring on same line

nohtyp

In [144]:
reverse='data science'

In [114]:
for i in range(len(reverse)-1,-1,-1): #for+indexing 
    print(reverse[i],end='')#for 012345

ecneics atad

In [145]:
for i in range(-1,-len(reverse)-1,-1):
    print(reverse[i], end='') #for-1,-2,-3 negative indexing

ecneics atad

In [146]:
rev = "python"

for i in range(-1, -len(rev)-1, -1):
    print(rev[i], end="")

nohtyp

In [ ]:
loop control statements:
break
continue

bopth are always used inside loop

In [149]:
eids=[45,856,748,265,5496,215,245,25,'ytfyf','fdf','fsdrdfi',4655,'wqeewasd',7546,54,88,32,78,'dtdyg']

In [ ]:
#for break- outoutwill come till 25 only
#for continue- outputwill come till 78

In [ ]:
BUSSINESS REQUIREMENT DOCUMENT = BRD BPREAPARED BY BA= BUSINESS ANALYST
client--data empids--striictly int data

In [ ]:
LOOP--IONVALID--TERMINATE/STOP

In [155]:
for ids in  eids:
    if str(ids).isnumeric():
        print("valid id--{} processing".format(ids))
    else:
        break
        print('hello')
print("outside the loop")

valid id--45 processing
valid id--856 processing
valid id--748 processing
valid id--265 processing
valid id--5496 processing
valid id--215 processing
valid id--245 processing
valid id--25 processing
outside the loop

In [ ]:
#after break it will go to firsdtline 
#so it will npot print hello

In [ ]:
for ids in  eids:
    if str(ids).isnumeric():
        print("valid id--{} processing".format(ids))
    else:
        break
print("outside the loop")

In [153]:
for ids in  eids:
    if str(ids).isnumeric():
        print("valid id--{} processing".format(ids))
    else:
        continue
print("outside the loop")

valid id--45 processing
valid id--856 processing
valid id--748 processing
valid id--265 processing
valid id--5496 processing
valid id--215 processing
valid id--245 processing
valid id--25 processing
valid id--4655 processing
valid id--7546 processing
valid id--54 processing
valid id--88 processing
valid id--32 processing
valid id--78 processing
outside the loop

In [ ]:
#continuw--excutes--jumps to next iteration

In [154]:
for ids in  eids:
    if str(ids).isnumeric():
        print("valid id--{} processing".format(ids))
    else:
        continue
        print("hello")

valid id--45 processing
valid id--856 processing
valid id--748 processing
valid id--265 processing
valid id--5496 processing
valid id--215 processing
valid id--245 processing
valid id--25 processing
valid id--4655 processing
valid id--7546 processing
valid id--54 processing
valid id--88 processing
valid id--32 processing
valid id--78 processing

In [ ]:
#aftercontinue it will go to firsdtline 
#so it will npot print hello

In [ ]:
we can use break n continue can be used in 
same esynatx

In [ ]:
for loop= finite number of elements
9group of element)
group based loop

In [ ]:
while loop --true/false--
false asen tr terminbate loop
################
condition based loop

In [ ]:
loop

list empty --loop terminate

In [ ]:
p contains element--list s not empty

[]-list is empty

In [ ]:
if len(p)==0:
    print("list is emopty")
else:
    print('list is not empty')

In [ ]:
but this is unpreffesional, student level
rather udse below code

In [ ]:
if p:
    print("list is not empty")
else:
    print("list is empty")

In [162]:
 records=[(101,'sa'),(25,'gd'),(245,'ghjkd')]

while records:
    record=records.pop()
    print("record inseted into db:")

In [163]:
while records:
    record= records.pop()
    print("record inseted into db:",records)

record inseted into db: [(101, 'sa'), (25, 'gd')]
record inseted into db: [(101, 'sa')]
record inseted into db: []

In [165]:
i=1
while i<=10:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10

In [1]:
while True:
    x=int(input("enter the num 1"))
    y=int(input("enter the num 2"))
    z=x+y
    print("addition of{} and {} is {}".format(x,y,z))

    choice=input("do u want to continue-yes|no")
    if choice=='no':
        print("thanks for viwsintiong")
        break

enter the num 1 59
enter the num 2 85

addition of59 and 85 is 144

do u want to continue-yes|no yes
enter the num 1 41
enter the num 2 63

addition of41 and 63 is 104

do u want to continue-yes|no yes
enter the num 1 852
enter the num 2 6321145

addition of852 and 6321145 is 6321997

do u want to continue-yes|no no

thanks for viwsintiong

In [ ]:
function
it is a block of code ehich perfoms given task

In [ ]:
def function_name(arg/parameters):
    bloack of code
    return value

In [3]:
def add(): #no argumenttaken
    x=int(input("enter the num 1"))
    y=int(input("enter the num 2"))
    z=x+y
    print(z)

In [4]:
add()

enter the num 1 10
enter the num 2 20

30

In [6]:
def add(x,y): #x y are formal valuese
        z=x+y
        print("additio of {} and {} is {}".format(x,y,z))

In [7]:
add(100,200) #100,200are actual values

additio of 100 and 200 is 300

In [16]:
def add(x,y): 
    z=x+y
    return z

In [17]:
result = add(100,200)

In [18]:
result

300

In [56]:
def even_odd_num(plistt):
    even =[]
    odd=[]
    for num in plistt:
        if num % 2 == 0:
            even.append(num)
        else:
            odd.append(num)
    return even,odd
    #if 2 values i.e even n odd are assignned to same variable then packing

In [57]:
ps = [45,86,21,874,963,5,852,385,63,45,74,21,22,96]
result = even_odd_num(ps)
print(result) #packing i.e 2 list in 1 tupple
#assinging result to both even n odd tehn both output in tuple form

([86, 874, 852, 74, 22, 96], [45, 21, 963, 5, 385, 63, 45, 21])

In [58]:
ps = [45,86,21,874,963,5,852,385,63,45,74,21,22,96]
e,o= even_odd_num(ps)

In [59]:
e

[86, 874, 852, 74, 22, 96]

In [60]:
o

[45, 21, 963, 5, 385, 63, 45, 21]

In [61]:
emails = ['test@gmail.com','ample@gmail.com','python@yahoo.com']

In [62]:
def fetch_username(email):
    username  =[]
    for em in email:
        username.append(em.split('@')[0])
    return username

In [63]:
fetch_username(emails)

['test', 'ample', 'python']

In [ ]:
def get_inputs_from_users():
    x=int(input("enter the marks for sub 1:"))
    y=int(input("enter the marks for sub 2:"))
    z=int(input("enter the marks for sub 3:"))
    return x,y,z

def calculate_total(t1,t2,t3):
    total= t1+t2+t3
    return total

def calculate_avg(tl1):
    avg = tl1/3
    return avg
    
def calculate_per(av):
    per = (av/300)*100
    return per

def catagorise_grade(per):
    if per>35 and per<60:
        return"C"
    elif per>60 and per<80:
        return"B"
    elif per>80 and per<100:
        return"A"
    else:
        return"failed"

def main():
    s1,s2,s3 = get_input_from_users()
    t1 = calculate_total(s1,s2,s3)
    av= calculate_avg(t1)
    per = calculate_per(av)
    grade = catagorise_grade(per)
    print("subject marks:", s1,s2,s3)
    print("Total:",tl1)
    print("Avg:",av)
    print("Per:",per)
    print("grade:",grade)

    
if __name__=='__main__':
    main()

In [87]:
def get_inputs_from_users():
    x=int(input("enter the marks for sub 1:"))
    y=int(input("enter the marks for sub 2:"))
    z=int(input("enter the marks for sub 3:"))
    return x,y,z

def calculate_total(t1,t2,t3):
    total= t1+t2+t3
    return total

def calculate_avg(tl1):
    avg = tl1/3
    return avg
    
def calculate_per(t1):
    per = (t1/300)*100
    return per

def catagorise_grade(per):
    if per>35 and per<60:
        return"C"
    elif per>60 and per<80:
        return"B"
    elif per>80 and per<100:
        return"A"
    else:
        return"failed"

def main():
    s1,s2,s3 = get_inputs_from_users()  # Fixed: changed from get_input_from_users to get_inputs_from_users
    t1 = calculate_total(s1,s2,s3)
    av= calculate_avg(t1)
    per = calculate_per(av)
    grade = catagorise_grade(per)
    print("subject marks:", s1,s2,s3)
    print("Total:",t1)  # Fixed: changed from tl1 to t1 (the correct variable name)
    print("Avg:",av)
    print("Per:",per)
    print("grade:",grade)

    
if __name__=='__main__':
    main()

enter the marks for sub 1: 80
enter the marks for sub 2: 80
enter the marks for sub 3: 80

subject marks: 80 80 80
Total: 240
Avg: 80.0
Per: 26.666666666666668
grade: failed

In [ ]:
#DECORATOR

In [ ]:
1. FUNCTION ALIAS

In [11]:
def sum():
    a=10
    b=20
    print(a+b)

In [12]:
sum()

30

In [13]:
t1 = sum

In [15]:
t1()

30

In [10]:
def fetch_username(email1):
    username = email1.split('@')[0]
    return username

In [98]:
new = fetch_username('hadoop@gmail.com')

In [99]:
new

'hadoop'

In [ ]:
here hadoop@gmail.com is alais to email1
and fetch_username is alais to new

In [2]:
def add(x,y):
    z=x+y
    return z

In [3]:
a=100
b=200
result=add(a,b)

In [5]:
result

300

In [16]:
def test():
    print("Hello from test")

In [17]:
m1 = test

In [18]:
m1()

Hello from test

In [ ]:
2. HOW TO CALL NESTED FUNCTION FROM OUTSIDE

In [20]:
def outer():
    print ("Hello")
    def inner():  #this is local func
        print("erlcome to DE")

In [21]:
outer() ##here we have called outer fuc so it will just print hello and create inner function but n0ot call the inner func

Hello

In [22]:
inner() #The name inner is local to outer() and isn't visible outside it.
#so use return to call local func

NameError: name 'inner' is not defined

In [29]:
def outer():
    print ("Hello")
    def inner():  #this is local func
        print("welcome to DE")
    return inner

In [30]:
result = outer() 
#now inner is saved in result

Hello

In [31]:
result()

welcome to DE

In [35]:
def outer():
    def inner():
        print("hello from inner function")
    return inner

In [38]:
temp = outer()

In [39]:
temp() # i have used temp which is outside name to call inside wall function

hello from inner function

In [ ]:
A nested function is a function inside another function. It cannot be called directly from outside because it has local scope. 
To use it outside, we must return it from the outer function.

In [ ]:
decorator: wrapper funct

it is funct which enhances the functionality of
another function without changinmg its orgiinal structure

In [43]:
def decor(funct):
    def inner():
        print("*"*25)
        funct()
        print("*"*25)
    return inner

def show():
    print("welcome to al nexus")

In [44]:
resultt = decor(show)
resultt()

*************************
welcome to al nexus
*************************

In [ ]:
#so now instead of this 
resultt = decor(show)
resultt()
#we can do it in 1 line internally by adding @decor n just call show

In [45]:
def decor(funct):
    def inner():
        print("*"*25) #before
        funct() #original func
        print("*"*25) # after
    return inner
@decor
def show():
    print("welcome to al nexus")

In [46]:
show()

*************************
welcome to al nexus
*************************

In [48]:
@decor
def welcome():
    print("welcome to data engineering")

In [49]:
welcome()

*************************
welcome to data engineering
*************************

In [53]:
@decor
def add():
    a= 100
    b= 200
    print("addition",a+b)

In [54]:
add()

*************************
addition 300
*************************

In [55]:
def db_decor(funct):
    def inner():
        print("connetion established")
        funct()
        print("connetion terminated")
    return inner

@db_decor
def copper():
    print("data transfer for copper")

@db_decor
def silver():
    print("data transfer for silver")

@db_decor
def gold():
    print ("data transfer for gold")

In [56]:
copper()
silver()
gold()

connetion established
data transfer for copper
connetion terminated
connetion established
data transfer for silver
connetion terminated
connetion established
data transfer for gold
connetion terminated

In [57]:
def auth_decor(funct):
    def inner():
        username = 'admin'
        u = input("enter the username:")
        if username==u:
            password = "admin@123"
            p = input("eneter the password:")
            if p== password:
                print("login successful")
                funct()
                print("logout successful")
            else:
                print("wrong password")
        else:
            print("wrong username")
    return inner
    
@auth_decor   
def fetch_bal_from_db():
    acc = 4464577541
    print("uracc bal is :",acc)

In [58]:
fetch_bal_from_db()

enter the username: admin
eneter the password: admin@123

login successful
uracc bal is : 4464577541
logout successful

In [59]:
fetch_bal_from_db()

enter the username: grfvawe

wrong username

In [60]:
fetch_bal_from_db()

enter the username: admin
eneter the password: gugr

wrong password

In [ ]:
Code optimization

In [ ]:
1. LAMBDA EXPRESSION

Anonymous func--no name
in line f
1 line f
temproary f
one time use f

In [61]:
(lambda x,y : x +y )(100,200)

300

In [63]:
reult = (lambda x,y : x +y )(100,200)

In [64]:
reult

300

In [69]:
username = (lambda email : email.split('@')[0])("sample@gmail.com")

In [71]:
username

'sample'

In [ ]:
map:
map is function which takes another function as argument and apply on seq |db

In [82]:
p = [1,2,3,4,5]

In [ ]:
#output req - [1,4,9,16,25]

In [75]:
sqr_element =[]
for element in p:
    sqr_element.append(element**2)
print(sqr_element)

[1, 4, 9, 16, 25]

In [ ]:
for loop --avoid loop--incrases time complexity

instead use map

In [84]:
def sqr_element(element):
    return element**2  #does for single element

In [85]:
list(map(sqr_element,p)) #for all elements in p use typecast

[1, 4, 9, 16, 25]

In [ ]:
#thisd becomes 3 mlinme code
#e need to optimize code so use lambda

In [86]:
list(map(lambda x:x**2,p))

[1, 4, 9, 16, 25]

In [87]:
emails=['test@gmail.com','samplea@gmail.com','xya@yahoo.com']

In [88]:
list(map(lambda x : x.split('@')[0],emails))

['test', 'samplea', 'xya']

In [90]:
dict(map(lambda x : (x.split('@')[0],x),emails))

{'test': 'test@gmail.com',
 'samplea': 'samplea@gmail.com',
 'xya': 'xya@yahoo.com'}

In [91]:
dict(map(lambda x : (x.split('@')[0],x.split('@')[1]),emails))

{'test': 'gmail.com', 'samplea': 'gmail.com', 'xya': 'yahoo.com'}

In [110]:
gen = ['m','f','m','f','f','m','fgsd','m','f']

In [103]:
#output [1,2,1,2,2,1]
#encoding
#m= 1
#f= 2

In [104]:
def gen_encode(temp):
    if temp=='m':
        return 1
    elif temp=='f':
        return 2
    else:
        return "invalid"

In [105]:
list(map(gen_encode,gen))

[1, 2, 1, 2, 2, 1, 'invalid']

In [106]:
#Ternary operator
#if else combination
#x if True else y

In [107]:
a=10
b=20
a if a>b else b
#if a>b true then will print a if false then prints b

20

In [108]:
list(map(lambda x :1 if x=='m' else 2,gen))

[1, 2, 1, 2, 2, 1, 2]

In [111]:
list(map(lambda x: 1 if x=='m' else 2 if x=='f' else 'invalid',gen))

[1, 2, 1, 2, 2, 1, 'invalid', 1, 2]

In [112]:
city=['pune','mumbai','banglore','chennai','banglore','pune','mumbai','banglore','chennai']

In [114]:
list(map(lambda x: 100 if x=='pune' else 200 if x=='mumbai' else 300 if x=='chennai' else 400 if x=='banglore' else 'invalid',city))

[100, 200, 400, 300, 400, 100, 200, 400, 300]

In [119]:
dates = ['01-12-2023','11-05-2000','29-03-1997']

In [120]:
year = list(map(lambda x : x.split('-')[-1],dates))

In [121]:
year

['2023', '2000', '1997']

In [122]:
month = list(map(lambda x : x.split('-')[1],dates))

In [123]:
month

['12', '05', '03']

In [125]:
day = list(map(lambda x : x.split('-')[0],dates))

In [126]:
day

['01', '11', '29']

In [127]:
##Filter

In [128]:
evenodd=[1,2,45,68,54165,44,496,21,44,9]

In [129]:
def even(num):
    if num%2==0:
        return True
    else:
        return False

In [130]:
list(filter(even,evenodd))

[2, 68, 44, 496, 44]

In [137]:
list(filter(lambda x : x%2==0,evenodd))

[2, 68, 44, 496, 44]

In [131]:
fax=[1,46,2563,89,641,56464,'erwq',64,131,87983,'gf','fsdgf',789,4246,454,1,4,4]

In [132]:
def valid_id(ids):
    if str(ids).isnumeric():
        return True
    else:
        return False

In [134]:
list(filter(valid_id,fax))

[1, 46, 2563, 89, 641, 56464, 64, 131, 87983, 789, 4246, 454, 1, 4, 4]

In [135]:
list (filter(lambda x : str(x).isnumeric(), fax))

[1, 46, 2563, 89, 641, 56464, 64, 131, 87983, 789, 4246, 454, 1, 4, 4]

In [138]:
tuple(filter(lambda x : str(x).isnumeric(), fax))

(1, 46, 2563, 89, 641, 56464, 64, 131, 87983, 789, 4246, 454, 1, 4, 4)

In [139]:
set(filter(lambda x : str(x).isnumeric(), fax))

{1, 4, 46, 64, 89, 131, 454, 641, 789, 2563, 4246, 56464, 87983}

In [140]:
list (filter(lambda x : str(x).isalpha(), fax))

['erwq', 'gf', 'fsdgf']

In [141]:
(filter(lambda x : str(x).isalpha(), fax))

In [ ]:
#if we dont mention which database is req it will not give result 
#will show memory location instead

In [142]:
list(map(lambda x : str(x).isalpha(), fax))

[False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False]

In [ ]:
#instead of filterif we use map then true or false is output

In [143]:
ppp=['131','121','89','79','85','452']
#what if intare in '' format

In [145]:
list(map(lambda x: int(x),ppp))

[131, 121, 89, 79, 85, 452]

In [146]:
colname=['prdname','prdlid','prdprice']

In [147]:
list(map(lambda x : x.upper(),colname))

['PRDNAME', 'PRDLID', 'PRDPRICE']

In [148]:
#diffrence between map n filter in diary

In [ ]:
#code optimization part 2 
using comprehension technique
for loop with single condition

1] list compreshension
2] tuple compreshension
3] dict compreshension

In [ ]:
LIST COMPREHENSION

In [ ]:
LIST---[VAR FOR VAR IN SEQ|DS if ccondtion]
[i fot i in DS|SEQ if cond]

In [150]:
pop= [1,65,55,5,421,3449,31,'fg','ffdsad','ewrr','erwy',49,412,963,6]

In [151]:
[i for i in pop if str(i).isnumeric()]

[1, 65, 55, 5, 421, 3449, 31, 49, 412, 963, 6]

In [153]:
top=['crazy','cheezy','cafe']

In [155]:
[(i,len(i)) for i in top if len(i)>5]

[('cheezy', 6)]

In [157]:
emails = ['test@gmail.com', 'samplea@gmail.com', 'xya@yahoo.com','sam@gmail.com', 'hadoop@yahoo.com']

In [161]:
[em.split('@')[0] for em in emails if em.endswith('@gmail.com')]

['test', 'samplea', 'sam']

In [164]:
paxx=[[1,2,3],[4,5,6]]

In [165]:
flatten_list = []
for element in paxx:
    for i in element:
        flatten_list.append(i)
print(flatten_list)

[1, 2, 3, 4, 5, 6]

In [167]:
[i for element in paxx for i in element]

[1, 2, 3, 4, 5, 6]

In [168]:
pack=[[1,2,3,'h','tr','gffg'],[4,41,789456,12356,1564,'hfgb','hdfua','tyt']]

In [171]:
[i for element in pack for i in element if str(i).isnumeric()]

[1, 2, 3, 4, 41, 789456, 12356, 1564]

In [ ]:
DICTONARY COMPREHENSION

In [ ]:
{k:v fork,v in ds if condition }

In [172]:
paps=['python','java','hadoop','pyspark']

In [174]:
{var:len(var) for var in paps}

{'python': 6, 'java': 4, 'hadoop': 6, 'pyspark': 7}

In [175]:
psq=[1,2,3,4,5,6]
#output={1:1,2:4,3:9...}

In [176]:
{i:i*i for i in psq }

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36}

In [177]:
{i:i*i for i in psq if i%2==0}

{2: 4, 4: 16, 6: 36}

In [183]:
pcount=[15,495,46,23,13,17,8,74,156,15,45,45,15,4,874,0,31,748,41,14,8]

In [184]:
{i:pcount.count(i) for i in pcount }

{15: 3,
 495: 1,
 46: 1,
 23: 1,
 13: 1,
 17: 1,
 8: 2,
 74: 1,
 156: 1,
 45: 2,
 4: 1,
 874: 1,
 0: 1,
 31: 1,
 748: 1,
 41: 1,
 14: 1}

In [190]:
#output {'2023': ''copper_2025_daily.csv'}
files=['copper_2025_daily.csv','copper_2026_daily.csv','copper_2023_daily.csv','copper_2025_daily.csv','copper_2024_daily.csv']

In [191]:
{i.split('_')[1]:i for i in files}

{'2025': 'copper_2025_daily.csv',
 '2026': 'copper_2026_daily.csv',
 '2023': 'copper_2023_daily.csv',
 '2024': 'copper_2024_daily.csv'}

In [ ]:
TUPLE COMPREHENSION

NOT POSSIBLE IN PYTHON
if we perform it will return Gererator Object

In [192]:
(i for i in range(10)) #tuple

In [193]:
#if we do same in list then output
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
what is GENERATOR????
it is used to generate seq of numbers


range:
it is used to genaerate seq of numbers

In [249]:
def demo():
    a=10
    b=20
    return a
    return b

In [197]:
demo()

10

In [ ]:
#dosent return b , cursors is thrown out after return a
to overcome this problem we have generator

In [ ]:
function  +  return == normal function
function  +  yield == Generator function

##yeild will give one vakue atatime n therefore wont show memory error

In [203]:
def demo():
    a=10
    b=20
    yield a
    yield b

In [204]:
result=demo()

In [205]:
next(result)

10

In [206]:
next(result)

20

In [207]:
next(result)

StopIteration:

In [258]:
def mygen():
    i=1
    while i<=10:
        yield i
        i+=1

In [259]:
obj = mygen()

In [260]:
next(obj)

1

In [261]:
next(obj)

2

In [262]:
for num in obj:
    print(num)

3
4
5
6
7
8
9
10

In [ ]:
[i for i in range(99999999999999999999999999999999999999999999999)]
#it will show memory error

In [ ]:
temp = (i for i in range(99999999999999999999999999999999999999999999999)
for num  in temp:
print(num)

In [ ]:
Intweerview
===================

Fabonacci series----0,1,1,2,3,5,8,13......

In [266]:
def fabbonacci_series():
    a,b = 0,1
    while a<=100:
        yield a
        a,b= b,a+b

In [267]:
obj=  fabbonacci_series()

In [268]:
next(obj)

0

In [269]:
for num in obj:
    print(num)

1
1
2
3
5
8
13
21
34
55
89

In [ ]:
solve for factorial

In [274]:
#Using a for Loop
num = int(input("Enter a number: "))

fact = 1

for i in range(1, num + 1):
    fact = fact * i

print("Factorial =", fact)

Enter a number:  5

Factorial = 120

In [278]:
#Using a while Loop
num = int(input("Enter a number: "))

fact = 1
i = 1

while i <= num:
    fact = fact * i
    i += 1

print("Factorial =", fact)

Enter a number:  2

Factorial = 2

In [277]:
#Using Recursion (Frequently Asked)
def factorial(n):

    if n == 0 or n == 1:
        return 1

    return n * factorial(n - 1)

num = int(input("Enter a number: "))

print("Factorial =", factorial(num))

Enter a number:  6

Factorial = 720

In [ ]:
solve for prime no

In [276]:
def prime_no():

    for num in range(2, 101):

        is_prime = True

        for i in range(2, num):

            if num % i == 0:
                is_prime = False
                break

        if is_prime:
            yield num


for no in prime_no():
    print(no)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97

In [275]:
binary = "10100010101"

decimal = int(binary, 2)

print("Decimal =", decimal)

Decimal = 1301

In [ ]:
Decorator vs Geneartor
===========================

decorator ====  enhances functionality
generator ==== number generator

In [ ]:
Iterator:
==============
iteratethe data structures
loop : start --- no control on loop...itwill happen till end

controllable iteration == iterate

In [284]:
peg =['python','java','hadoop']

In [285]:
iter(peg)

In [286]:
pea ={'python','java','hadoop'}

In [287]:
iter(pea)

In [288]:
pogo =('python','java','hadoop')

In [289]:
iter(pogo)

In [290]:
temp = iter (peg)

In [291]:
next(temp)

'python'

In [292]:
next(temp)

'java'

In [293]:
next(temp)

'hadoop'

In [294]:
next(temp)

StopIteration:

In [ ]:
which is memory optmized? generator or iterator 
iterator is applied on datastructure n datastructure occupies memory
iterators is alwsys applied on datastructures

generator ===generates only 1 no ata time
genarator is used to generate seq of nos

In [ ]:
FILE HANDELLING
11]read
2]write
3]append
4]read tehn write
5]write then read
6]append then read
7]exclusive

In [ ]:
read--------r

if file present then it will open file and read the content

if not then it will return filenot found error

In [215]:
fp= open("test1.txt","r") #r is default u add it or not it willread

FileNotFoundError: [Errno 2] No such file or directory: 'test1.txt'

In [212]:
fp= open("test.txt","r")
data = fp.read()
print(data)

v xb
cc
g

zczcxb
bnght
ghhv'ug
vcbSB

In [213]:
fp= open("test.txt","r")
data = fp.readlines ()#all data in list of lines
print(data)

['v xb\n', 'cc\n', 'g\n', '\n', 'zczcxb\n', 'bnght\n', "ghhv'ug\n", 'vcbSB']

In [214]:
fp= open("test.txt","r")
data = fp.readline()#reads only first line
print(data)

v xb

In [216]:
#to check status--- file is open in which mode
fp= open("test.txt","r")
print(fp.readable())

True

In [ ]:
write mode---"w"

if file present then it will write content into [overwrite]
will deleete old contenet n write new content in it

if not then it will create file n write the content

In [220]:
fp= open('online1314demo.txt','w')
fp.write("this is demo for write mode")

27

In [226]:
datata="""Python is a high-level, general-purpose programming language that emphasizes code readability, simplicity, and ease-of-writing with the use of significant indentation,[38] an extensive ("batteries-included") standard library, and garbage collection. Python supports multiple programming paradigms but with an emphasis on object-oriented programming and dynamic typing."""

In [227]:
fp = open("dem11.txt","w")
fp.write(datata)

368

In [309]:
fp = open("dem11.txt","r")
data = fp.read()
print(data)

Python is a high-level, general-purpose programming language 8463008725 that emphasizes code readability, simplicity, and ease-of-writing with the use of significant sam@gmail.com indentation,[38] an extensive ("batteries-included") standard 9851473264 library, and garbage collection. Python supports multiple programming paradigms but 7412886340 with an ayush@yahoo.com
 emphasis on 356984 object-oriented programming and 3498 dynamic typing. programming and dynamic typing. 9423774394

In [319]:
#to fetch nos from this file n create a new file of nos and dump it into it
mobileno =[]
for word in data.split():
    if word.isnumeric():
        if len(word)==10:
            if word.startswith(("6","7","8","9")):
                mobileno.append(word+"\n") #+\n so that nos will come next like
print(mobileno)

['8463008725\n', '9851473264\n', '7412886340\n', '9423774394\n']

In [ ]:
#"startswith() expects a string or a tuple of strings because it compares text prefixes.
#range(6,10) produces integers (6, 7, 8, 9), not strings, so it raises a TypeError. 
#To check multiple starting digits, we use startswith(('6', '7', '8', '9')) or simply
#check word[0] in '6789'."

In [ ]:
mobileno = []

for word in data.split():
    if word.isnumeric():
        if len(word) == 10:    #Give me the character at index 0
            if word[0] in "6789": #in is called the membership operator.
                mobileno.append(word)

print(mobileno)

In [ ]:
if word[0] in "6789": == if word[0] in ["6", "7", "8", "9"]:
    word[0] gets the first character of the string. The in operator checks whether that 
    character exists in the string '6789'. If the first character is 6, 7, 8, or 9, 
    the condition is True; otherwise, it is False."

In [ ]:
mobileno = []

for word in data.split():
    if word.isnumeric() and len(word) == 10 and word[0] in "6789":
        mobileno.append(word)

print(mobileno)

In [234]:
#"dgdgujfgbjgfi"----we will need write
#for list type we need writelines()--pass list of lines
write() is used to write a single string to a file, whereas writelines() is used to 
write multiple strings from an iterable. Neither method adds a newline automatically; 
you must include \n if needed.

In [237]:
fp1= open("mobiles.txt","w")
fp1.writelines(mobileno)

In [238]:
fp1.readable()

False

In [240]:
fp1.writable() #it is not write able but writ able

True

In [304]:
email= []
for mail in data.split():
    if mail.endswith(".com"):
        email.append(mail+"\n")
print(email)

['sam@gmail.com\n', 'ayush@yahoo.com\n']

In [308]:
fp2 = open("emails.txt","w")
fp2.writelines(email)

In [242]:
fp = open("test.txt")
print(fp.closed)

False

In [243]:
fp = open("test.txt")
print(fp.closed) #file is still open hence will show false
fp.close()#here file is closed 
print(fp.closed)

False
True

In [ ]:
#if we dont close file it will show ACCESS DENIDED for other files n developers
#till u close 1 file we csant open anothger new file

In [ ]:
Normal open VS with open  
normal open -we have tomanually open n close files
with open does that automatically

In [ ]:
with open(filename/path, mode) as fp:
    fp.read
    fp.write

In [245]:
with open('test.txt','r') as fp:
    data=fp.read()
    print("inside indent:",fp.closed)
print("outside indent :",fp.closed)

inside indent: False
outside indent : True

In [ ]:
 with open('test.txt','w') as fp:
    data=f`p.read()

In [ ]:
append ----a

if file present then itwill add the content
old content + new content

if file is not present then it will create new file then add the content


-----write deletes old content n adds new content but append keeps old content n add new   


w| a
write()
writelines()
writeable()--true/false

write() is used to write a single string to a file, whereas writelines() is used to
write multiple strings from an iterable. Neither method adds a newline automatically;
you must include \n if needed.

In [248]:
with open("test.txt","a" ) as fp:
    fp.write("\nnew content by  append mode")

In [ ]:
read then write mode : r+

In [322]:
with open ("test.txt",'r+') as fp:
    data = fp.read()
    print(data)
    fp.write('\nnew content bygjgfsd mode')

v xb
cc
g

zczcxb
bnght
ghhv'ug
vcbSB
new content by  append mode
new content by  append mode
new content by r+ mode
new content by r+ mode
new content by r+ mode
new content bygjgfsd mode

In [ ]:
append vs r+
in append u can add new content while keeping the old content too
in r+ u can read , add new content while keeping the old content too

In [ ]:
write then read---w+

In [327]:
with open("test.txt","w+") as fp:
    fp.write("new content by w+ mode")
    data=fp.read()
    print (data)

In [ ]:
# in write old data gets deleted so everything will get blank then 
next line i.e new content by w+ mode will be written 
but now cursor is at e of mode 
after that it has nothing to read 
so aoutput will be blank

then how to read content in file 
we have to bring pointer/cursor to start by 2 methods
1]tell---current pointer position/location
2]seek(pl)--move to given location----pl=pinter location

In [329]:
with open("test.txt","w+") as fp:
    fp.write("new content by w+ mode")
    fp.seek(0)
    data=fp.read()
    print (data)

new content by w+ mode

In [ ]:
append then read--a+
=============

In [336]:
with open("test.txt","a+") as fp:
    fp.write("\nnew content by a+ mode")
    fp.seek(0)
    data = fp.read()
    print(data)

new content by a+ modenew content by a+ mode/nnew content by a+ mode
new content by a+ mode
new content by a+ mode
new content by a+ mode
new content by a+ mode

In [13]:
with open("test.txt","a+") as fp:
    fp.write("new content by a+ mode\n")
    fp.seek(0)
    data = fp.read()
    print(data)

new content by a+ modenew content by a+ mode/nnew content by a+ mode
new content by a+ mode
new content by a+ mode
new content by a+ mode
new content by a+ modenew content by a+ mode
new content by a+ mode+
new content by a+ mode+
new content by a+ mode
new content by a+ mode

In [12]:
with open(r"C:\Users\ASUS\Desktop\s\emails.txt","a+") as fp:
    fp.write("\nnew content by a+ mode")
    fp.seek(0)
    data = fp.read()
    print(data)

new content by a+ mode
new content by a+ mode
new content by a+ mode
new content by a+ mode
new content by a+ mode

with open("C:\\Users\\ASUS\\Desktop\\s","a+") as fp:
    fp.write("\nnew content by a+ mode")
    fp.seek(0)
    data = fp.read()
    print(data)

In [ ]:
exclusive mode---'x'

if file present then return file Exists Error
if not then it will create new file

In [337]:
with open("test.txt","x") as fp:
    fp.write("\nnew contetent by x")

FileExistsError: [Errno 17] File exists: 'test.txt'

In [338]:
with open("test1.txt","x") as fp:
    fp.write("\nnew contetent by x")

In [ ]:
---used when servers logs arecreated 
logs are date wise
12.00 AM new file--- day log dump
12.00 Am new file

In [342]:
import datetime

In [343]:
filename = 'copper_daily_{}.txt'

In [344]:
filename.format(datetime.datetime.now())

'copper_daily_2026-07-25 18:36:09.610798.txt'

In [ ]:
file:
csv---csv module
json ---json odule
excel---openpyxl module
pdf---pydf2 module
yaml---pyaml module
img---pillow,cv2 module
audio | video ----encoders modules

In [ ]:
module is pytghon file tht has extension .py
module is collection of functyions n classes

In [143]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\asus\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [144]:
import pandas as pd

In [4]:
empdata = ((101,'Rakesh','Pune'),(102,'Amit','Mumbai')) #tuple of tuple

In [7]:
df=pd.DataFrame(empdata)

In [9]:
df

     0       1       2
0  101  Rakesh    Pune
1  102    Amit  Mumbai

In [5]:
df=pd.DataFrame(empdata,columns=['id','name','city'])

In [6]:
df

    id    name    city
0  101  Rakesh    Pune
1  102    Amit  Mumbai

In [11]:
empdata=[{"id":101,'name':'Sam','city':'Solapur'}, #list of dict
         {"id":101,'name':'Sam','city':'Solapur'},
         {"id":101,'name':'Sam','city':'Solapur'}]

In [12]:
df = pd.DataFrame(empdata) #for list of dict no need to give col names, itwill 
#take keys as col nammes

In [13]:
df

    id name     city
0  101  Sam  Solapur
1  101  Sam  Solapur
2  101  Sam  Solapur

In [153]:
empdata1=[{"id":101,'name':'Sam','city':'Solapur'},
         {"id":101,'name':'Sam'},#if we dont give value atall it will retun NaN
         {"id":101,'name':'Sam','city':'Solapur'}]

In [154]:
df2= pd.DataFrame(empdata1)

In [155]:
df2 #NaN=not a number

    id name     city
0  101  Sam  Solapur
1  101  Sam      NaN
2  101  Sam  Solapur

In [162]:
empdata11=[{"id":101,'name':'Sam','city':'Solapur'}, #list of dict
         {"id":101,'name':'Sam','city':None}, #ifwe give none then returns none
         {"id":101,'name':'Sam','city':'Solapur'}]

In [163]:
emp2= pd.DataFrame(empdata11)

In [164]:
emp2

    id name     city
0  101  Sam  Solapur
1  101  Sam     None
2  101  Sam  Solapur

In [147]:
emp = {"id":[1,2,3],
       "name": ['a','aa','aaaa'],
       "city" : ['d','gt','hj']
      }

In [150]:
dff = pd.DataFrame(emp)

In [151]:
dff

   id  name city
0   1     a    d
1   2    aa   gt
2   3  aaaa   hj

In [ ]:
=================
GET DATA FROM FILE
======================
CSV
JSON
EXCEL
API
HTML

In [ ]:
CSV====
pd.read_csv(filename/path)

In [49]:
readcsv=pd.read_csv("covid.csv")

In [50]:
readcsv

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],894,7114321,779135536
1,NaN,Peru,6603,221071,4533813
2,NaN,Bulgaria,5681,38778,1341094
3,NaN,North Macedonia,5429,9991,352093
4,NaN,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...,...
235,NaN,Pitcairn Islands,0,0,4
236,NaN,Tokelau,0,0,80
237,NaN,North Korea,0,0,0
238,NaN,Turkmenistan,0,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [53]:
readcsv=pd.read_csv("pandas files\covid.csv") #if folder has foldeer then add folder name 
#here i added pandas name i.e folders name n add \

In [54]:
readcsv

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],894,7114321,779135536
1,NaN,Peru,6603,221071,4533813
2,NaN,Bulgaria,5681,38778,1341094
3,NaN,North Macedonia,5429,9991,352093
4,NaN,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...,...
235,NaN,Pitcairn Islands,0,0,4
236,NaN,Tokelau,0,0,80
237,NaN,North Korea,0,0,0
238,NaN,Turkmenistan,0,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [207]:
readcsv=pd.read_csv(r"C:\Users\ASUS\Desktop\s\covid.csv") #if u want to give path add r

In [208]:
readcsv

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],894,7114321,779135536
1,NaN,Peru,6603,221071,4533813
2,NaN,Bulgaria,5681,38778,1341094
3,NaN,North Macedonia,5429,9991,352093
4,NaN,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...,...
235,NaN,Pitcairn Islands,0,0,4
236,NaN,Tokelau,0,0,80
237,NaN,North Korea,0,0,0
238,NaN,Turkmenistan,0,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [ ]:
============
excel to data frame
=============

In [197]:
df_ = pd.read_excel(r"C:\Users\ASUS\Desktop\s\New Microsoft Excel Worksheet.xlsx") 
#if we dont mention sheet name then by default firstsheet from excel it will take

In [198]:
df_

   prdid prdname   loc
0    101  copper  pune
1    102  silver  pune
2    103    gold  pune

In [194]:
df_mumbai = pd.read_excel(r"C:\Users\ASUS\Desktop\s\New Microsoft Excel Worksheet.xlsx",sheet_name='mumbai')

In [195]:
df_mumbai

   prdid prdname     loc
0    101  copper  mumbai
1    102  silver  mumbai
2    103    gold  mumbai

In [199]:
df_pune = pd.read_excel(r"C:\Users\ASUS\Desktop\s\New Microsoft Excel Worksheet.xlsx",sheet_name='pune')

In [74]:
df_pune

   prdid prdname   loc
0    101  copper  pune
1    102  silver  pune
2    103    gold  pune

In [75]:
pd.concat([df_pune,df_mumbai])

   prdid prdname     loc
0    101  copper    pune
1    102  silver    pune
2    103    gold    pune
0    101  copper  mumbai
1    102  silver  mumbai
2    103    gold  mumbai

In [86]:
sheetnames = ['pune','mumbai']

In [200]:
def get_sheet_names(filename):
    try:
        wb = load_workbook("New Microsoft Excel Worksheet.xlsx")
        return wb.sheetnames
    except Exception as e:
        raise(e)

def construct_df(shname):
    df_list = []
    for sheet in shname:
        df_list.append(pd.read_excel("New Microsoft Excel Worksheet.xlsx",sheet_name=sheet))
    return pd.concat(df_list,ignore_index=True)
    
    

def main():
    filename = 'New Microsoft Excel Worksheet.xlsx'
    sheetnames = get_sheet_names(filename)
    finaldf = construct_df(sheetnames)
    print(finaldf)

if __name__=='__main__':
    main()

   prdid prdname     loc
0    101  copper    pune
1    102  silver    pune
2    103    gold    pune
3    101  copper  mumbai
4    102  silver  mumbai
5    103    gold  mumbai
6    101  copper  nagpur
7    102  silver  nagpur
8    103    gold  nagpur

In [203]:
finaldf()

NameError: name 'finaldf' is not defined

In [89]:
from openpyxl import load_workbook

In [165]:
df1 = pd.read_json("emp.json")

In [166]:
df1

                                            employees
0   {'id': 100, 'FIRST_NAME': 'Steven', 'LAST_NAME...
1   {'id': 101, 'FIRST_NAME': 'Neena', 'LAST_NAME'...
2   {'id': 102, 'FIRST_NAME': 'Lex', 'LAST_NAME': ...
3   {'id': 103, 'FIRST_NAME': 'Alexander', 'LAST_N...
4   {'id': 105, 'FIRST_NAME': 'David', 'LAST_NAME'...
5   {'id': 106, 'FIRST_NAME': 'Valli', 'LAST_NAME'...
6   {'id': 107, 'FIRST_NAME': 'Diana', 'LAST_NAME'...
7   {'id': 108, 'FIRST_NAME': 'Nancy', 'LAST_NAME'...
8   {'id': 109, 'FIRST_NAME': 'Daniel', 'LAST_NAME...
9   {'id': 110, 'FIRST_NAME': 'John', 'LAST_NAME':...
10  {'id': 111, 'FIRST_NAME': 'Ismael', 'LAST_NAME...
11  {'id': 112, 'FIRST_NAME': 'Jose Manuel', 'LAST...
12  {'id': 113, 'FIRST_NAME': 'Luis', 'LAST_NAME':...
13  {'id': 114, 'FIRST_NAME': 'Den', 'LAST_NAME': ...
14  {'id': 115, 'FIRST_NAME': 'Alexander', 'LAST_N...
15  {'id': 116, 'FIRST_NAME': 'Shelli', 'LAST_NAME...
16  {'id': 117, 'FIRST_NAME': 'Sigal', 'LAST_NAME'...
17  {'id': 118, 'FIRST_NAME': 'Guy', 'LAST_NAME': ...
18  {'id': 119, 'FIRST_NAME': 'Karen', 'LAST_NAME'...
19  {'id': 120, 'FIRST_NAME': 'Matthew', 'LAST_NAM...

In [170]:
import json #first we need to convert into python object

In [171]:
with open("emp.json") as fp: #deserialize karun phthon 0obj madhe convert kela
    data = json.load(fp)

In [172]:
data['employees'] ##we have got list of dict here
# #we used employee key to fetch disctonary

[{'id': 100,
  'FIRST_NAME': 'Steven',
  'LAST_NAME': 'King',
  'EMAIL': 'SKING',
  'PHONE_NUMBER': '515.123.4567',
  'HIRE_DATE': '1987-06-17',
  'SALARY': 24000,
  'DEPARTMENT_ID': 90,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/10.png'},
 {'id': 101,
  'FIRST_NAME': 'Neena',
  'LAST_NAME': 'Kochhar',
  'EMAIL': 'NKOCHHAR',
  'PHONE_NUMBER': '515.123.4568',
  'HIRE_DATE': '1989-09-21',
  'SALARY': 17000,
  'DEPARTMENT_ID': 90,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/2.png'},
 {'id': 102,
  'FIRST_NAME': 'Lex',
  'LAST_NAME': 'De Haan',
  'EMAIL': 'LDEHAAN',
  'PHONE_NUMBER': '515.123.4569',
  'HIRE_DATE': '1993-01-13',
  'SALARY': 17000,
  'DEPARTMENT_ID': 90,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/3.png'},
 {'id': 103,
  'FIRST_NAME': 'Alexander',
  'LAST_NAME': 'Hunold',
  'EMAIL': 'AHUNOLD',
  'PHONE_NUMBER': '590.423.4567',
  'HIRE_DATE': '1990-01-03',
  'SALARY': 9000,
  'DEPARTMENT_ID': 60,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/15.png'},
 {'id': 105,
  'FIRST_NAME': 'David',
  'LAST_NAME': 'Austin',
  'EMAIL': 'DAUSTIN',
  'PHONE_NUMBER': '590.423.4569',
  'HIRE_DATE': '1997-06-25',
  'SALARY': 4800,
  'DEPARTMENT_ID': 60,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/6.png'},
 {'id': 106,
  'FIRST_NAME': 'Valli',
  'LAST_NAME': 'Pataballa',
  'EMAIL': 'VPATABAL',
  'PHONE_NUMBER': '590.423.4560',
  'HIRE_DATE': '1998-02-05',
  'SALARY': 4800,
  'DEPARTMENT_ID': 60,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/7.png'},
 {'id': 107,
  'FIRST_NAME': 'Diana',
  'LAST_NAME': 'Lorentz',
  'EMAIL': 'DLORENTZ',
  'PHONE_NUMBER': '590.423.5567',
  'HIRE_DATE': '1999-02-07',
  'SALARY': 4200,
  'DEPARTMENT_ID': 60,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/7.png'},
 {'id': 108,
  'FIRST_NAME': 'Nancy',
  'LAST_NAME': 'Greenberg',
  'EMAIL': 'NGREENBE',
  'PHONE_NUMBER': '515.124.4569',
  'HIRE_DATE': '1994-08-17',
  'SALARY': 12000,
  'DEPARTMENT_ID': 100,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/8.png'},
 {'id': 109,
  'FIRST_NAME': 'Daniel',
  'LAST_NAME': 'Faviet',
  'EMAIL': 'DFAVIET',
  'PHONE_NUMBER': '515.124.4169',
  'HIRE_DATE': '1994-08-17',
  'SALARY': 9000,
  'DEPARTMENT_ID': 100,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/17.png'},
 {'id': 110,
  'FIRST_NAME': 'John',
  'LAST_NAME': 'Chen',
  'EMAIL': 'JCHEN',
  'PHONE_NUMBER': '515.124.4269',
  'HIRE_DATE': '1997-09-28',
  'SALARY': 8200,
  'DEPARTMENT_ID': 100,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/10.png'},
 {'id': 111,
  'FIRST_NAME': 'Ismael',
  'LAST_NAME': 'Sciarra',
  'EMAIL': 'ISCIARRA',
  'PHONE_NUMBER': '515.124.4369',
  'HIRE_DATE': '1997-09-30',
  'SALARY': 7700,
  'DEPARTMENT_ID': 100,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/11.png'},
 {'id': 112,
  'FIRST_NAME': 'Jose Manuel',
  'LAST_NAME': 'Urman',
  'EMAIL': 'JMURMAN',
  'PHONE_NUMBER': '515.124.4469',
  'HIRE_DATE': '1998-03-07',
  'SALARY': 7800,
  'DEPARTMENT_ID': 100,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/12.png'},
 {'id': 113,
  'FIRST_NAME': 'Luis',
  'LAST_NAME': 'Popp',
  'EMAIL': 'LPOPP',
  'PHONE_NUMBER': '515.124.4567',
  'HIRE_DATE': '1999-12-07',
  'SALARY': 6900,
  'DEPARTMENT_ID': 100,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/13.png'},
 {'id': 114,
  'FIRST_NAME': 'Den',
  'LAST_NAME': 'Raphaely',
  'EMAIL': 'DRAPHEAL',
  'PHONE_NUMBER': '515.127.4561',
  'HIRE_DATE': '1994-12-07',
  'SALARY': 11000,
  'DEPARTMENT_ID': 30,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/14.png'},
 {'id': 115,
  'FIRST_NAME': 'Alexander',
  'LAST_NAME': 'Khoo',
  'EMAIL': 'AKHOO',
  'PHONE_NUMBER': '515.127.4562',
  'HIRE_DATE': '1995-05-18',
  'SALARY': 3100,
  'DEPARTMENT_ID': 30,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/15.png'},
 {'id': 116,
  'FIRST_NAME': 'Shelli',
  'LAST_NAME': 'Baida',
  'EMAIL': 'SBAIDA',
  'PHONE_NUMBER': '515.127.4563',
  'HIRE_DATE': '1997-12-24',
  'SALARY': 2900,
  'DEPARTMENT_ID': 30,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/6.png'},
 {'id': 117,
  'FIRST_NAME': 'Sigal',
  'LAST_NAME': 'Tobias',
  'EMAIL': 'STOBIAS',
  'PHONE_NUMBER': '515.127.4564',
  'HIRE_DATE': '1997-07-24',
  'SALARY': 2800,
  'DEPARTMENT_ID': 30,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/17.png'},
 {'id': 118,
  'FIRST_NAME': 'Guy',
  'LAST_NAME': 'Himuro',
  'EMAIL': 'GHIMURO',
  'PHONE_NUMBER': '515.127.4565',
  'HIRE_DATE': '1998-11-15',
  'SALARY': 2600,
  'DEPARTMENT_ID': 30,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/18.png'},
 {'id': 119,
  'FIRST_NAME': 'Karen',
  'LAST_NAME': 'Colmenares',
  'EMAIL': 'KCOLMENA',
  'PHONE_NUMBER': '515.127.4566',
  'HIRE_DATE': '1999-08-10',
  'SALARY': 2500,
  'DEPARTMENT_ID': 30,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/9.png'},
 {'id': 120,
  'FIRST_NAME': 'Matthew',
  'LAST_NAME': 'Weiss',
  'EMAIL': 'MWEISS',
  'PHONE_NUMBER': '650.123.1234',
  'HIRE_DATE': '1996-07-18',
  'SALARY': 8000,
  'DEPARTMENT_ID': 50,
  'Image': 'https://www.oracle.com/webfolder/technetwork/jet/Images/dvt/14.png'}]

In [95]:
pd.DataFrame(data['employees'])

,id,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,SALARY,DEPARTMENT_ID,Image
0,100,Steven,King,SKING,515.123.4567,1987-06-17,24000,90,https://www.oracle.com/webfolder/technetwork/j...
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,1989-09-21,17000,90,https://www.oracle.com/webfolder/technetwork/j...
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1993-01-13,17000,90,https://www.oracle.com/webfolder/technetwork/j...
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1990-01-03,9000,60,https://www.oracle.com/webfolder/technetwork/j...
4,105,David,Austin,DAUSTIN,590.423.4569,1997-06-25,4800,60,https://www.oracle.com/webfolder/technetwork/j...
5,106,Valli,Pataballa,VPATABAL,590.423.4560,1998-02-05,4800,60,https://www.oracle.com/webfolder/technetwork/j...
6,107,Diana,Lorentz,DLORENTZ,590.423.5567,1999-02-07,4200,60,https://www.oracle.com/webfolder/technetwork/j...
7,108,Nancy,Greenberg,NGREENBE,515.124.4569,1994-08-17,12000,100,https://www.oracle.com/webfolder/technetwork/j...
8,109,Daniel,Faviet,DFAVIET,515.124.4169,1994-08-17,9000,100,https://www.oracle.com/webfolder/technetwork/j...
9,110,John,Chen,JCHEN,515.124.4269,1997-09-28,8200,100,https://www.oracle.com/webfolder/technetwork/j...
10,111,Ismael,Sciarra,ISCIARRA,515.124.4369,1997-09-30,7700,100,https://www.oracle.com/webfolder/technetwork/j...
11,112,Jose Manuel,Urman,JMURMAN,515.124.4469,1998-03-07,7800,100,https://www.oracle.com/webfolder/technetwork/j...
12,113,Luis,Popp,LPOPP,515.124.4567,1999-12-07,6900,100,https://www.oracle.com/webfolder/technetwork/j...
13,114,Den,Raphaely,DRAPHEAL,515.127.4561,1994-12-07,11000,30,https://www.oracle.com/webfolder/technetwork/j...
14,115,Alexander,Khoo,AKHOO,515.127.4562,1995-05-18,3100,30,https://www.oracle.com/webfolder/technetwork/j...
15,116,Shelli,Baida,SBAIDA,515.127.4563,1997-12-24,2900,30,https://www.oracle.com/webfolder/technetwork/j...
16,117,Sigal,Tobias,STOBIAS,515.127.4564,1997-07-24,2800,30,https://www.oracle.com/webfolder/technetwork/j...
17,118,Guy,Himuro,GHIMURO,515.127.4565,1998-11-15,2600,30,https://www.oracle.com/webfolder/technetwork/j...
18,119,Karen,Colmenares,KCOLMENA,515.127.4566,1999-08-10,2500,30,https://www.oracle.com/webfolder/technetwork/j...
19,120,Matthew,Weiss,MWEISS,650.123.1234,1996-07-18,8000,50,https://www.oracle.com/webfolder/technetwork/j...

In [100]:
df = pd.read_json("emp - Copy.json") #then converted into dataframe

In [101]:
df

,id,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,SALARY,DEPARTMENT_ID,Image
0,100,Steven,King,SKING,515.123.4567,1987-06-17,24000,90,https://www.oracle.com/webfolder/technetwork/j...
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,1989-09-21,17000,90,https://www.oracle.com/webfolder/technetwork/j...
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1993-01-13,17000,90,https://www.oracle.com/webfolder/technetwork/j...
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1990-01-03,9000,60,https://www.oracle.com/webfolder/technetwork/j...
4,105,David,Austin,DAUSTIN,590.423.4569,1997-06-25,4800,60,https://www.oracle.com/webfolder/technetwork/j...
5,106,Valli,Pataballa,VPATABAL,590.423.4560,1998-02-05,4800,60,https://www.oracle.com/webfolder/technetwork/j...
6,107,Diana,Lorentz,DLORENTZ,590.423.5567,1999-02-07,4200,60,https://www.oracle.com/webfolder/technetwork/j...
7,108,Nancy,Greenberg,NGREENBE,515.124.4569,1994-08-17,12000,100,https://www.oracle.com/webfolder/technetwork/j...
8,109,Daniel,Faviet,DFAVIET,515.124.4169,1994-08-17,9000,100,https://www.oracle.com/webfolder/technetwork/j...
9,110,John,Chen,JCHEN,515.124.4269,1997-09-28,8200,100,https://www.oracle.com/webfolder/technetwork/j...
10,111,Ismael,Sciarra,ISCIARRA,515.124.4369,1997-09-30,7700,100,https://www.oracle.com/webfolder/technetwork/j...
11,112,Jose Manuel,Urman,JMURMAN,515.124.4469,1998-03-07,7800,100,https://www.oracle.com/webfolder/technetwork/j...
12,113,Luis,Popp,LPOPP,515.124.4567,1999-12-07,6900,100,https://www.oracle.com/webfolder/technetwork/j...
13,114,Den,Raphaely,DRAPHEAL,515.127.4561,1994-12-07,11000,30,https://www.oracle.com/webfolder/technetwork/j...
14,115,Alexander,Khoo,AKHOO,515.127.4562,1995-05-18,3100,30,https://www.oracle.com/webfolder/technetwork/j...
15,116,Shelli,Baida,SBAIDA,515.127.4563,1997-12-24,2900,30,https://www.oracle.com/webfolder/technetwork/j...
16,117,Sigal,Tobias,STOBIAS,515.127.4564,1997-07-24,2800,30,https://www.oracle.com/webfolder/technetwork/j...
17,118,Guy,Himuro,GHIMURO,515.127.4565,1998-11-15,2600,30,https://www.oracle.com/webfolder/technetwork/j...
18,119,Karen,Colmenares,KCOLMENA,515.127.4566,1999-08-10,2500,30,https://www.oracle.com/webfolder/technetwork/j...
19,120,Matthew,Weiss,MWEISS,650.123.1234,1996-07-18,8000,50,https://www.oracle.com/webfolder/technetwork/j...

In [ ]:
api to dataframe

In [ ]:
import response

In [176]:
response = requests.get("https://api.sampleapis.com/coffee/hot") #SAMPLEAPI FROM CHROME ,HGET IT FROM THERE

In [177]:
data = response.content

In [178]:
data #this data is in string jason , we need to convert into dictonary

b'[{"title":"Latte","description":"Som den mest popul\xc3\xa4ra kaffedrycken d\xc3\xa4r ute best\xc3\xa5r latte av en skv\xc3\xa4tt espresso och \xc3\xa5ngad mj\xc3\xb6lk med bara en gnutta skum. Den kan best\xc3\xa4llas utan smak eller med smak av allt fr\xc3\xa5n vanilj till pumpa kryddor.","ingredients":["Espresso","\xc3\x85ngad mj\xc3\xb6lk"],"image":"https://images.unsplash.com/photo-1561882468-9110e03e0f78?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxhdHRlfGVufDB8fDB8fHww","id":2},{"title":"Caramel Latte","description":"Om du gillar latte med en speciell smak kan karamell latte vara det b\xc3\xa4sta alternativet f\xc3\xb6r att ge dig en upplevelse av den naturliga s\xc3\xb6tman och kr\xc3\xa4migheten hos \xc3\xa5ngad mj\xc3\xb6lk och karamell.","ingredients":["Espresso","\xc3\x85ngad mj\xc3\xb6lk","Karamellsirap"],"image":"https://images.unsplash.com/photo-1599398054066-846f28917f38?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D","id":3},{"title":"Macchiato","description":"Macchiaton \xc3\xa4r en annan espresso-baserad dryck som har en liten m\xc3\xa4ngd skum p\xc3\xa5 toppen. Det \xc3\xa4r det glada mellanrummet mellan en cappuccino och en doppio.","ingredients":["Espresso"," Foam"],"image":"https://images.unsplash.com/photo-1557772611-722dabe20327?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D","id":7},{"title":"Classic Cappuccino","description":"A timeless Italian favorite built on a strict, harmonious balance of equal parts bold espresso, warm liquid steamed milk, and an exceptionally dense, pillowy layer of luxurious aerated milk foam. Each cup is artfully finished with a delicate dusting of premium organic cocoa powder, offering an airy yet satisfyingly rich mouthfeel with every sip","ingredients":["Caramel"," Macchiato"],"image":"https://images.unsplash.com/photo-1572442388796-11668a67e53d","id":8},{"title":"Matcha Latte","description":"Matcha latte \xc3\xa4r en gr\xc3\xb6n, h\xc3\xa4lsosam kaffedryck med finkrossad matcha-te och mj\xc3\xb6lk, erbjuder mild s\xc3\xb6tma, en unik smak och en mild koffeinkick.","ingredients":["Matcha-pulver","Mj\xc3\xb6lk","Socker*"],"image":"https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWF0Y2hhJTIwbGF0dGV8ZW58MHx8MHx8fDA%3D","id":11},{"title":"Svart Te","description":"Svart te f\xc3\xb6ddes i Kina. Det \xc3\xa4r tillverkat av blad fr\xc3\xa5n en v\xc3\xa4xt som kallas Camellia och kan smaks\xc3\xa4ttas olika med frukter till exempel. En trevlig, varm, smakfull och aromatisk dryck som passar till vardagen.","ingredients":["Te"],"image":"https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHRlYXxlbnwwfHwwfHx8MA%3D%3D","id":13},{"title":"Islatte","description":"Iced latte \xc3\xa4r en kyld kaffedryck som g\xc3\xb6rs genom att blanda espresso och kyld mj\xc3\xb6lk. Den serveras med isbitar och \xc3\xa4r \xc3\xa4ven k\xc3\xa4nd som caf\xc3\xa8 latte iced eller latte on the rocks.","ingredients":["Espresso","Mj\xc3\xb6lk","Is","Sirap"],"image":"https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aWNlZCUyMGxhdHRlfGVufDB8fDB8fHww","id":14},{"title":"Islatte Mocha","description":"Iced latte Mocha \xc3\xa4r en kombination av latte och mocha, som i sig \xc3\xa4r en kombination av choklad och kaffe. Den ger kalla dryck\xc3\xa4lskare en l\xc3\xa4cker upplevelse av choklad och kaffe.","ingredients":["Espresso","Is","Mj\xc3\xb6lk","Choklad "],"image":"https://images.unsplash.com/photo-1642647391072-6a2416f048e5?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fGljZWQlMjBtb2NoYSUyMGxhdHRlfGVufDB8fDB8fHww","id":15},{"title":"Frapino Caramel","description":"Det \xc3\xa4r en blandad eller b\xc3\xa4ttre sagt skakad kaffe med vispad gr\xc3\xa4dde p\xc3\xa5 toppen. Ett m\xc3\xa5ste f\xc3\xb6r varma sommardagar.","ingredients":["coffee","Is","Mj\xc3\xb6lk","Karamellsirap","Vispgr\xc3\xa4dde*","Karamells\xc3\xa5s"],"image":"https://images.unsplash.com/photo-1662047102608-a6f2e492411f?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZnJhcGlubyUyMGNhcmFtZWx8ZW58MHx8MHx8fDA%3D","id":16},{"title":"Frapino Mocka","description":"\xc3\x84nnu en ber\xc3\xb6md och uts\xc3\xb6kt kall dryck f\xc3\xb6r dem som f\xc3\xb6redrar choklad. T\xc3\xa4nk dig smaken av en shake med choklad och vispad gr\xc3\xa4dde p\xc3\xa5 toppen.","ingredients":["Coffee","Is","Mj\xc3\xb6lk","Cocoa","Vispgr\xc3\xa4dde*"],"image":"https://images.unsplash.com/photo-1530373239216-42518e6b4063?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZnJhcGlubyUyMG1vY2hhfGVufDB8fDB8fHww","id":17},{"title":"Affogato al Caff\xc3\xa8","description":"The ultimate culinary convergence of hot beverage and chilled dessert. We take a generous, indulgent scoop of our artisanal, flecked vanilla bean gelato and place it inside a chilled glass. It is served alongside a hot, freshly pulled double shot of our intense espresso, designed to be poured directly over the ice cream to create a rich, creamy pool of melting, bittersweet perfection","ingredients":["Ceremonial Matcha Latte"],"image":"https://images.unsplash.com/photo-1540331547168-8b63109225b7","id":18},{"title":"Frozen Lemonade","description":"Frozen lemonade \xc3\xa4r en uppfriskande sommardryck som kombinerar f\xc3\xa4rskpressad citronsaft, is och s\xc3\xb6tning till en svalkande, syrlig och s\xc3\xb6tsyrlig smaksensation.","ingredients":["Citronsaft","Is","Socker*"],"image":"https://images.unsplash.com/photo-1523371054106-bbf80586c38c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxlbW9uYWRlJTIwd2l0aCUyMGljZXxlbnwwfHwwfHx8MA%3D%3D","id":19},{"title":"Flat White","description":"Espresso with steamed milk and microfoam.","ingredients":["Espresso","Steamed milk"],"image":"https://example.com/flatwhite.jpg","id":999},{"title":"Caramel Macchiato","description":"A visually striking, layered espresso beverage that starts with a base of freshly steamed milk infused with sweet, gourmet vanilla-flavored syrup. We then carefully \'mark\' the milk by pouring fresh, hot espresso shots directly through the center, creating a beautiful gradient effect. The masterpiece is finished with a generous, crosshatched drizzle of our proprietary, buttery house caramel.","ingredients":"Spiced Mocha","image":"https://images.unsplash.com/photo-1577968897966-3d4325b36b61","id":1000},{"title":"latte","description":"dos de azucar sin hielo","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1001},{"title":"latte","description":"dos de azucar sin hielo","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1002},{"title":"latte","description":"dos de azucar sin hielo","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1003},{"title":"latte","description":"dos de azucar sin hielo","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1004},{"title":"latte","description":"dos de azucar sin hielo","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1005},{"title":"latte","description":"dos de azucar sin hielo","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1006},{"title":"latte","description":"dos de azucar sin hielo","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1007},{"title":"cafe con moca","description":"este es un cafe de los alpes con coxtracto de moca con sabor agridulce con temas amargos y dulces","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1008},{"title":"late de prueba ","description":"este es un late de prueba","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1009},{"title":"latte de prueba","description":"descrupcion e+del late de prueba","ingredients":["Espresso","Leche"],"image":"https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800","id":1010},{"id":1011,"title":"Caf\xc3\xa9 Antillais","description":"A coffee drink from the French Caribbean islands.","ingredients":["Caf\xc3\xa9 La Tivolienne","Rum","Sugar","Cinnamon","Vanilla Syrup"],"image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_W0XhNYWHXIMZJypNj_JWx7a8BMN2ZzcGo_gWrP-z3g&s=100"},{"title":"Caf\xc3\xa9 Antillais","description":"A coffee drink from the French Caribbean islands.","ingredients":["Caf\xc3\xa9 La Tivolienne","Rum","Sugar","Cinnamon"],"image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_W0XhNYWHXIMZJypNj_JWx7a8BMN2ZzcGo_gWrP-z3g&s=100","id":1012},{"title":"Caf\xc3\xa9 Antillais","description":"A coffee drink from the French Caribbean islands.","ingredients":["Caf\xc3\xa9 La Tivolienne","Rum","Sugar","Cinnamon"],"image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_W0XhNYWHXIMZJypNj_JWx7a8BMN2ZzcGo_gWrP-z3g&s=100","id":1013}]'

In [179]:
json.loads(data)

[{'title': 'Latte',
  'description': 'Som den mest populära kaffedrycken där ute består latte av en skvätt espresso och ångad mjölk med bara en gnutta skum. Den kan beställas utan smak eller med smak av allt från vanilj till pumpa kryddor.',
  'ingredients': ['Espresso', 'Ångad mjölk'],
  'image': 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxhdHRlfGVufDB8fDB8fHww',
  'id': 2},
 {'title': 'Caramel Latte',
  'description': 'Om du gillar latte med en speciell smak kan karamell latte vara det bästa alternativet för att ge dig en upplevelse av den naturliga sötman och krämigheten hos ångad mjölk och karamell.',
  'ingredients': ['Espresso', 'Ångad mjölk', 'Karamellsirap'],
  'image': 'https://images.unsplash.com/photo-1599398054066-846f28917f38?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  'id': 3},
 {'title': 'Macchiato',
  'description': 'Macchiaton är en annan espresso-baserad dryck som har en liten mängd skum på toppen. Det är det glada mellanrummet mellan en cappuccino och en doppio.',
  'ingredients': ['Espresso', ' Foam'],
  'image': 'https://images.unsplash.com/photo-1557772611-722dabe20327?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  'id': 7},
 {'title': 'Classic Cappuccino',
  'description': 'A timeless Italian favorite built on a strict, harmonious balance of equal parts bold espresso, warm liquid steamed milk, and an exceptionally dense, pillowy layer of luxurious aerated milk foam. Each cup is artfully finished with a delicate dusting of premium organic cocoa powder, offering an airy yet satisfyingly rich mouthfeel with every sip',
  'ingredients': ['Caramel', ' Macchiato'],
  'image': 'https://images.unsplash.com/photo-1572442388796-11668a67e53d',
  'id': 8},
 {'title': 'Matcha Latte',
  'description': 'Matcha latte är en grön, hälsosam kaffedryck med finkrossad matcha-te och mjölk, erbjuder mild sötma, en unik smak och en mild koffeinkick.',
  'ingredients': ['Matcha-pulver', 'Mjölk', 'Socker*'],
  'image': 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWF0Y2hhJTIwbGF0dGV8ZW58MHx8MHx8fDA%3D',
  'id': 11},
 {'title': 'Svart Te',
  'description': 'Svart te föddes i Kina. Det är tillverkat av blad från en växt som kallas Camellia och kan smaksättas olika med frukter till exempel. En trevlig, varm, smakfull och aromatisk dryck som passar till vardagen.',
  'ingredients': ['Te'],
  'image': 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHRlYXxlbnwwfHwwfHx8MA%3D%3D',
  'id': 13},
 {'title': 'Islatte',
  'description': 'Iced latte är en kyld kaffedryck som görs genom att blanda espresso och kyld mjölk. Den serveras med isbitar och är även känd som cafè latte iced eller latte on the rocks.',
  'ingredients': ['Espresso', 'Mjölk', 'Is', 'Sirap'],
  'image': 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aWNlZCUyMGxhdHRlfGVufDB8fDB8fHww',
  'id': 14},
 {'title': 'Islatte Mocha',
  'description': 'Iced latte Mocha är en kombination av latte och mocha, som i sig är en kombination av choklad och kaffe. Den ger kalla dryckälskare en läcker upplevelse av choklad och kaffe.',
  'ingredients': ['Espresso', 'Is', 'Mjölk', 'Choklad '],
  'image': 'https://images.unsplash.com/photo-1642647391072-6a2416f048e5?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fGljZWQlMjBtb2NoYSUyMGxhdHRlfGVufDB8fDB8fHww',
  'id': 15},
 {'title': 'Frapino Caramel',
  'description': 'Det är en blandad eller bättre sagt skakad kaffe med vispad grädde på toppen. Ett måste för varma sommardagar.',
  'ingredients': ['coffee',
   'Is',
   'Mjölk',
   'Karamellsirap',
   'Vispgrädde*',
   'Karamellsås'],
  'image': 'https://images.unsplash.com/photo-1662047102608-a6f2e492411f?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZnJhcGlubyUyMGNhcmFtZWx8ZW58MHx8MHx8fDA%3D',
  'id': 16},
 {'title': 'Frapino Mocka',
  'description': 'Ännu en berömd och utsökt kall dryck för dem som föredrar choklad. Tänk dig smaken av en shake med choklad och vispad grädde på toppen.',
  'ingredients': ['Coffee', 'Is', 'Mjölk', 'Cocoa', 'Vispgrädde*'],
  'image': 'https://images.unsplash.com/photo-1530373239216-42518e6b4063?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZnJhcGlubyUyMG1vY2hhfGVufDB8fDB8fHww',
  'id': 17},
 {'title': 'Affogato al Caffè',
  'description': 'The ultimate culinary convergence of hot beverage and chilled dessert. We take a generous, indulgent scoop of our artisanal, flecked vanilla bean gelato and place it inside a chilled glass. It is served alongside a hot, freshly pulled double shot of our intense espresso, designed to be poured directly over the ice cream to create a rich, creamy pool of melting, bittersweet perfection',
  'ingredients': ['Ceremonial Matcha Latte'],
  'image': 'https://images.unsplash.com/photo-1540331547168-8b63109225b7',
  'id': 18},
 {'title': 'Frozen Lemonade',
  'description': 'Frozen lemonade är en uppfriskande sommardryck som kombinerar färskpressad citronsaft, is och sötning till en svalkande, syrlig och sötsyrlig smaksensation.',
  'ingredients': ['Citronsaft', 'Is', 'Socker*'],
  'image': 'https://images.unsplash.com/photo-1523371054106-bbf80586c38c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxlbW9uYWRlJTIwd2l0aCUyMGljZXxlbnwwfHwwfHx8MA%3D%3D',
  'id': 19},
 {'title': 'Flat White',
  'description': 'Espresso with steamed milk and microfoam.',
  'ingredients': ['Espresso', 'Steamed milk'],
  'image': 'https://example.com/flatwhite.jpg',
  'id': 999},
 {'title': 'Caramel Macchiato',
  'description': "A visually striking, layered espresso beverage that starts with a base of freshly steamed milk infused with sweet, gourmet vanilla-flavored syrup. We then carefully 'mark' the milk by pouring fresh, hot espresso shots directly through the center, creating a beautiful gradient effect. The masterpiece is finished with a generous, crosshatched drizzle of our proprietary, buttery house caramel.",
  'ingredients': 'Spiced Mocha',
  'image': 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61',
  'id': 1000},
 {'title': 'latte',
  'description': 'dos de azucar sin hielo',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1001},
 {'title': 'latte',
  'description': 'dos de azucar sin hielo',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1002},
 {'title': 'latte',
  'description': 'dos de azucar sin hielo',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1003},
 {'title': 'latte',
  'description': 'dos de azucar sin hielo',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1004},
 {'title': 'latte',
  'description': 'dos de azucar sin hielo',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1005},
 {'title': 'latte',
  'description': 'dos de azucar sin hielo',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1006},
 {'title': 'latte',
  'description': 'dos de azucar sin hielo',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1007},
 {'title': 'cafe con moca',
  'description': 'este es un cafe de los alpes con coxtracto de moca con sabor agridulce con temas amargos y dulces',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1008},
 {'title': 'late de prueba ',
  'description': 'este es un late de prueba',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1009},
 {'title': 'latte de prueba',
  'description': 'descrupcion e+del late de prueba',
  'ingredients': ['Espresso', 'Leche'],
  'image': 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
  'id': 1010},
 {'id': 1011,
  'title': 'Café Antillais',
  'description': 'A coffee drink from the French Caribbean islands.',
  'ingredients': ['Café La Tivolienne',
   'Rum',
   'Sugar',
   'Cinnamon',
   'Vanilla Syrup'],
  'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_W0XhNYWHXIMZJypNj_JWx7a8BMN2ZzcGo_gWrP-z3g&s=100'},
 {'title': 'Café Antillais',
  'description': 'A coffee drink from the French Caribbean islands.',
  'ingredients': ['Café La Tivolienne', 'Rum', 'Sugar', 'Cinnamon'],
  'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_W0XhNYWHXIMZJypNj_JWx7a8BMN2ZzcGo_gWrP-z3g&s=100',
  'id': 1012},
 {'title': 'Café Antillais',
  'description': 'A coffee drink from the French Caribbean islands.',
  'ingredients': ['Café La Tivolienne', 'Rum', 'Sugar', 'Cinnamon'],
  'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_W0XhNYWHXIMZJypNj_JWx7a8BMN2ZzcGo_gWrP-z3g&s=100',
  'id': 1013}]

In [180]:
pd.DataFrame(json.loads(data))

,title,description,ingredients,image,id
0,Latte,Som den mest populära kaffedrycken där ute bes...,"[Espresso, Ångad mjölk]",https://images.unsplash.com/photo-1561882468-9...,2
1,Caramel Latte,Om du gillar latte med en speciell smak kan ka...,"[Espresso, Ångad mjölk, Karamellsirap]",https://images.unsplash.com/photo-159939805406...,3
2,Macchiato,Macchiaton är en annan espresso-baserad dryck ...,"[Espresso, Foam]",https://images.unsplash.com/photo-1557772611-7...,7
3,Classic Cappuccino,"A timeless Italian favorite built on a strict,...","[Caramel, Macchiato]",https://images.unsplash.com/photo-157244238879...,8
4,Matcha Latte,"Matcha latte är en grön, hälsosam kaffedryck m...","[Matcha-pulver, Mjölk, Socker*]",https://images.unsplash.com/photo-153625626395...,11
5,Svart Te,Svart te föddes i Kina. Det är tillverkat av b...,[Te],https://images.unsplash.com/photo-157609276824...,13
6,Islatte,Iced latte är en kyld kaffedryck som görs geno...,"[Espresso, Mjölk, Is, Sirap]",https://images.unsplash.com/photo-151770155092...,14
7,Islatte Mocha,Iced latte Mocha är en kombination av latte oc...,"[Espresso, Is, Mjölk, Choklad ]",https://images.unsplash.com/photo-164264739107...,15
8,Frapino Caramel,Det är en blandad eller bättre sagt skakad kaf...,"[coffee, Is, Mjölk, Karamellsirap, Vispgrädde*...",https://images.unsplash.com/photo-166204710260...,16
9,Frapino Mocka,Ännu en berömd och utsökt kall dryck för dem s...,"[Coffee, Is, Mjölk, Cocoa, Vispgrädde*]",https://images.unsplash.com/photo-153037323921...,17
10,Affogato al Caffè,The ultimate culinary convergence of hot bever...,[Ceremonial Matcha Latte],https://images.unsplash.com/photo-154033154716...,18
11,Frozen Lemonade,Frozen lemonade är en uppfriskande sommardryck...,"[Citronsaft, Is, Socker*]",https://images.unsplash.com/photo-152337105410...,19
12,Flat White,Espresso with steamed milk and microfoam.,"[Espresso, Steamed milk]",https://example.com/flatwhite.jpg,999
13,Caramel Macchiato,"A visually striking, layered espresso beverage...",Spiced Mocha,https://images.unsplash.com/photo-157796889796...,1000
14,latte,dos de azucar sin hielo,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1001
15,latte,dos de azucar sin hielo,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1002
16,latte,dos de azucar sin hielo,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1003
17,latte,dos de azucar sin hielo,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1004
18,latte,dos de azucar sin hielo,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1005
19,latte,dos de azucar sin hielo,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1006
20,latte,dos de azucar sin hielo,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1007
21,cafe con moca,este es un cafe de los alpes con coxtracto de ...,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1008
22,late de prueba,este es un late de prueba,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1009
23,latte de prueba,descrupcion e+del late de prueba,"[Espresso, Leche]",https://images.unsplash.com/photo-151443232460...,1010
24,Café Antillais,A coffee drink from the French Caribbean islands.,"[Café La Tivolienne, Rum, Sugar, Cinnamon, Van...",https://encrypted-tbn0.gstatic.com/images?q=tb...,1011
25,Café Antillais,A coffee drink from the French Caribbean islands.,"[Café La Tivolienne, Rum, Sugar, Cinnamon]",https://encrypted-tbn0.gstatic.com/images?q=tb...,1012
26,Café Antillais,A coffee drink from the French Caribbean islands.,"[Café La Tivolienne, Rum, Sugar, Cinnamon]",https://encrypted-tbn0.gstatic.com/images?q=tb...,1013

In [136]:
pd.DataFrame(data)

                                                   0
0  b'<!DOCTYPE html>\n<html lang="en">\n<head>\n<...
1                         b're>\n</body>\n</html>\n'

In [181]:
df =  pd.read_html("COVID-19 pandemic by country and territory - Wikipedia.html")

In [182]:
df

[                                    COVID-19 pandemic  \
 0   Confirmed deaths per 100,000 population,[1][no...
 1                                             Disease
 2                                            Pathogen
 3                                              Source
 4                                            Location
 5                                      First outbreak
 6                                          Index case
 7                                                Date
 8                                     Confirmed cases
 9                                              Deaths
 10                                       Vaccinations

                                   COVID-19 pandemic.1
 0   Confirmed deaths per 100,000 population,[1][no...
 1                                            COVID-19
 2                                          SARS-CoV-2
 3      Probably bats, possibly via pangolins[2][3][4]
 4                                           Worldwide
 5                                            China[5]
 6   Wuhan, Hubei, China 30°37′11″N 114°15′28″E﻿ / ...
 7   First case of COVID-19: 17 November 2019; 6 ye...
 8                                      779,135,536[6]
 9                                        7,114,321[6]
 10  5,645,247,500[6] (total vaccinated)5,197,972,5...  ,
                                                    0
 0  Map of total confirmed cases by country[10][no...
 1        Date of latest upload at the Commons source,
                                                    0
 0  Map of confirmed cases per million by country[...
 1        Date of latest upload at the Commons source,
                                                    0
 0  Map of total confirmed deaths by country[12][n...
 1                                       Date on map.,
                                                    0
 0  Map of total confirmed deaths per million peop...
 1                                       Date on map.,
                                                    0
 0  Map of daily new confirmed deaths per million ...
 1                                       Date on map.,
                                                    0
 0  Graph of daily new confirmed deaths worldwide ...
 1                         Date on timeline at bottom,
                                                    0
 0  Graph showing daily count of new confirmed dea...
 1                         Date on timeline at bottom,
                                                    0
 0  Graph of weekly count of new confirmed deaths ...
 1                         Date on timeline at bottom,
                                                    0
 0  Share of fully vaccinated population by countr...
 1                                        Date on map,
                                                    0
 0  Share of population with at least one dose of ...
 1                                        Date on map,
                                                    0
 0  Vaccine doses administered per 100 people by c...
 1                                        Date on map,
                                             Unnamed: 0  \
 0                                                  NaN
 1                                                  NaN
 2                                                  NaN
 3                                                  NaN
 4                                                  NaN
 ..                                                 ...
 235                                                NaN
 236                                                NaN
 237                                                NaN
 238                                                NaN
 239  ↑ Countries which do not report data for a col...

                                                Country  \
 0                                             World[a]
 1                                                 Peru
 2                                             Bulgaria
 3                                      North Macedonia
 4                               Bosnia and Herzegovina
 ..                                                 ...
 235                                   Pitcairn Islands
 236                                            Tokelau
 237                                        North Korea
 238                                       Turkmenistan
 239  ↑ Countries which do not report data for a col...

                                       Deaths / million  \
 0                                                  894
 1                                                 6603
 2                                                 5681
 3                                                 5429
 4                                                 5123
 ..                                                 ...
 235                                                  0
 236                                                  0
 237                                                  0
 238                                                  0
 239  ↑ Countries which do not report data for a col...

                                                 Deaths  \
 0                                              7114321
 1                                               221071
 2                                                38778
 3                                                 9991
 4                                                16419
 ..                                                 ...
 235                                                  0
 236                                                  0
 237                                                  0
 238                                                  0
 239  ↑ Countries which do not report data for a col...

                                                  Cases
 0                                            779135536
 1                                              4533813
 2                                              1341094
 3                                               352093
 4                                               404289
 ..                                                 ...
 235                                                  4
 236                                                 80
 237                                                  0
 238                                                  0
 239  ↑ Countries which do not report data for a col...

 [240 rows x 5 columns],
      Unnamed: 0       Location    Jan 1    Feb 1    Mar 1
 0           NaN          World  5440722  5682684  5954004
 1           NaN  United States   819197   881867   941112
 2           NaN         Brazil   618984   626854   649134
 3           NaN          India   481486   496242   514023
 4           NaN         Russia   309707   332012   352446
 ..          ...            ...      ...      ...      ...
 233         NaN        Tokelau        0        0        0
 234         NaN          Tonga        0        0        0
 235         NaN   Turkmenistan        0        0        0
 236         NaN         Tuvalu        0        0        0
 237         NaN        Vanuatu        0        0        0

 [238 rows x 5 columns],
      Unnamed: 0       Location    Jul 1    Aug 1    Sep 1    Oct 1    Nov 1  \
 0           NaN          World  3954147  4229169  4536307  4794137  5005025
 1           NaN  United States   600853   610606   642770   697430   743217
 2           NaN         Brazil   515985   555460   579574   596122   607694
 3           NaN          India   399459   424351   439020   448339   458437
 4           NaN         Mexico   238055   245959   267253   283091   290717
 ..          ...            ...      ...      ...      ...      ...      ...
 233         NaN        Tokelau        0        0        0        0        0
 234         NaN          Tonga        0        0        0        0        0
 235         NaN   Turkmenistan        0        0        0        0        0
 236         NaN         Tuvalu        0        0        0        0        0
 237         NaN        Vanuatu        0        0        0        0        0

        Dec 1
 0    5215745
 1     774868
 2     614376
 3     469247
 4     293950
 ..       ...
 233        0
 234        0
 235        0
 236        0
 237        0

 [238 rows x 8 columns],
                           Region[30]  Total cases  Total deaths  \
 0                     European Union    179537758       1185108
 1                      North America    103783777       1133607
 2                       Other Europe     57721948        498259
 3                      South America     65835789       1313061
 4            Russia and Central Asia     25646533        434988
 5                    Central America     11338600        380660
 6                        Middle East     22549784        238106
 7   Oceania and islands in East Asia     60806544        318455
 8                          Caribbean      2605473         26237
 9                         South Asia     50347136        620218
 10                      North Africa      3727346         83873
 11                         East Asia     57867768        189910
 12                Sub-Saharan Africa      8636456        172907
 13               Totals (or average)    650404912       6595389

     Cases per million  Deaths per million  Current weekly cases  \
 0              401363                2649                886074
 1              281404                3074                476376
 2              247054                2133                 74354
 3              153151                3055                378622
 4              108307                1837                 49022
 5               63108                2119                 60268
 6               86400                 912                 13457
 7              105317                 552               1390401
 8               60179                 606                   737
 9               27121                 334                  1911
 10              18382                 414                   668
 11              32416                 106                644079
 12               7598                 152                  6960
 13              83826                 850               3982929

     Current weekly deaths  Population millions  Vacci­nated %[31]
 0                    3985                  447               75.1
 1                    2975                  369               76.1
 2                     248                  234               61.2
 3                    1252                  430               81.7
 4                     393                  237               55.9
 5                     263                  180               69.0
 6                      65                  261               51.9
 7                    2777                  577               72.1
 8                      25                   43               46.4
 9                      24                 1856               69.4
 10                      8                  203               41.3
 11                    818                 1785               87.2
 12                     27                 1137               27.6
 13                  12860                 7759               67.0  ,
                                                    0
 0  New identified cases of COVID-19 weekly for to...,
                                                    0
 0  Deaths due to COVID-19 weekly for top 7 region...,
                                             Unnamed: 0  \
 0                                                  NaN
 1                                                  NaN
 2                                                  NaN
 3                                                  NaN
 4                                                  NaN
 ..                                                 ...
 218                                                NaN
 219                                                NaN
 220                                                NaN
 221                                                NaN
 222  ↑ Number of people who have received at least ...

                                               Location  \
 0                                          World[c][d]
 1                                             China[e]
 2                                                India
 3                                    European Union[f]
 4                                     United States[g]
 ..                                                 ...
 218                                         Montserrat
 219                                               Niue
 220                                   Pitcairn Islands
 221                                        North Korea
 222  ↑ Number of people who have received at least ...

                                          Vaccinated[a]  \
 0                                           5645247500
 1                                           1318026800
 2                                           1027438900
 3                                            338481060
 4                                            270227170
 ..                                                 ...
 218                                               2104
 219                                               1638
 220                                                 47
 221                                                  0
 222  ↑ Number of people who have received at least ...

                                             Percent[b]
 0                                               70.71%
 1                                               92.48%
 2                                               72.08%
 3                                               75.43%
 4                                               79.12%
 ..                                                 ...
 218                                             47.01%
 219                                             88.83%
 220                                            100.00%
 221                                              0.00%
 222  ↑ Number of people who have received at least ...

 [223 rows x 4 columns],
                          0                       1
 0  ≥ 800  600–799  300–599  200–299  100–199  <100,
                   Date      Countries / Territories
 0   1 December 2019[a]                        China
 1      13 January 2020                     Thailand
 2      16 January 2020                        Japan
 3      20 January 2020  South Korea • United States
 4      21 January 2020                    Taiwan[b]
 ..                 ...                          ...
 84        2 April 2022                        Nauru
 85       8 May 2022[x]                  North Korea
 86         20 May 2022                       Tuvalu
 87        16 July 2022          Pitcairn Islands[e]
 88    20 December 2022                   Tokelau[y]

 [89 rows x 2 columns],
                               showvteCOVID-19 pandemic  \
 0                COVID-19 (disease) SARS-CoV-2 (virus)
 1    showTimelinePre-pandemic Severe acute respirat...
 2                                         showTimeline
 3    Pre-pandemic Severe acute respiratory syndrome...
 4                                         Pre-pandemic
 ..                                                 ...
 162  showData (templates)Global WHO situation repor...
 163                               showData (templates)
 164  Global WHO situation reports cases deaths Worl...
 165                                             Global
 166                                               Asia

                             showvteCOVID-19 pandemic.1
 0                COVID-19 (disease) SARS-CoV-2 (virus)
 1    showTimelinePre-pandemic Severe acute respirat...
 2                                         showTimeline
 3    Pre-pandemic Severe acute respiratory syndrome...
 4    Severe acute respiratory syndrome (SARS) Middl...
 ..                                                 ...
 162  showData (templates)Global WHO situation repor...
 163                               showData (templates)
 164  Global WHO situation reports cases deaths Worl...
 165  WHO situation reports cases deaths World map b...
 166         Armenia Artsakh China confirmed per capita

 [167 rows x 2 columns],
                                         showTimeline  \
 0  Pre-pandemic Severe acute respiratory syndrome...
 1                                       Pre-pandemic
 2                                               2020
 3                                               2021
 4                                               2022
 5                                               2023

                                       showTimeline.1
 0  Pre-pandemic Severe acute respiratory syndrome...
 1  Severe acute respiratory syndrome (SARS) Middl...
 2  January responses February responses March res...
 3  January responses February responses March res...
 4  January responses February responses March res...
 5                                           Timeline  ,
               0                                                  1
 0  Pre-pandemic  Severe acute respiratory syndrome (SARS) Middl...
 1          2020  January responses February responses March res...
 2          2021  January responses February responses March res...
 3          2022  January responses February responses March res...
 4          2023                                           Timeline,
                                         showLocations  \
 0   Africa(national responses)Northern Algeria Can...
 1                          Africa(national responses)
 2                                            Northern
 3                                             Eastern
 4                                            Southern
 5                                             Central
 6                                             Western
 7                                                Asia
 8                                       Central/North
 9                                                East
 10  Hong Kong Japan timeline Tokyo 2020 Summer Oly...
 11                                     Mainland China
 12                                              South
 13  Afghanistan Bangladesh timeline Bhutan Maldive...
 14                                              India
 15  economic impact lockdown migrant workers' cris...
 16                                        By location
 17                                          Southeast
 18  Brunei Cambodia Indonesia timeline 2021 social...
 19                                           Malaysia
 20                                        Philippines
 21                                               West
 22                                             Europe
 23                                     United Kingdom
 24  history timeline January–June 2020 July–Decemb...
 25                                        By location
 26                                            Eastern
 27                                    Western Balkans
 28                                     European Union
 29                                     EFTA countries
 30                                        Microstates
 31                                      North America
 32                                           Atlantic
 33                                             Canada
 34                                          Caribbean
 35                                          Countries
 36                       British Overseas Territories
 37  Aruba Curaçao Sint Maarten Caribbean Netherlan...
 38                         Aruba Curaçao Sint Maarten
 39                              Caribbean Netherlands
 40                                 French West Indies
 41                                   US insular areas

In [108]:
type(df)

list

In [185]:
df[12]  #12 is index no

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],894,7114321,779135536
1,NaN,Peru,6603,221071,4533813
2,NaN,Bulgaria,5681,38778,1341094
3,NaN,North Macedonia,5429,9991,352093
4,NaN,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...,...
235,NaN,Pitcairn Islands,0,0,4
236,NaN,Tokelau,0,0,80
237,NaN,North Korea,0,0,0
238,NaN,Turkmenistan,0,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [183]:
final = df[12] #12 is index no

In [114]:
final.to_csv("covid1.csv",index=False)

In [116]:
final.to_html("covid1.html")

In [125]:
df1 = pd.read_html(r"C:\Users\ASUS\Downloads\Wildlife Sanctuaries in India 2026, State Wise List, Map.html")

In [126]:
df1

[                                                    0  \
 0   Total Wildlife Sanctuaries of India State Wise...
 1                                               S.No.
 2                                                  1.
 3                                                  2.
 4                                                  3.
 5                                                  4.
 6                                                  5.
 7                                                  6.
 8                                                  7.
 9                                                  8.
 10                                                 9.
 11                                                10.
 12                                                11.
 13                                                12.
 14                                                13.
 15                                                14.
 16                                                15.
 17                                                16.
 18                                                17.
 19                                                18.
 20                                                19.
 21                                                20.
 22                                                21.
 23                                                22.
 24                                                23.
 25                                                24.
 26                                                25.
 27                                                26.
 28                                                27.
 29                                                28.
 30                                                29.
 31                                                30.
 32                                                31.
 33                                                32.
 34                                                33.
 35                                                34.
 36                                                35.
 37                                                36.
 38                                                37.
 39                                                NaN

                                                     1  \
 0   Total Wildlife Sanctuaries of India State Wise...
 1                                          State & UT
 2                                      Andhra Pradesh
 3                                   Arunachal Pradesh
 4                                               Assam
 5                                               Bihar
 6                                        Chhattisgarh
 7                                                 Goa
 8                                             Gujarat
 9                                             Haryana
 10                                   Himachal Pradesh
 11                                          Jharkhand
 12                                          Karnataka
 13                                             Kerala
 14                                     Madhya Pradesh
 15                                        Maharashtra
 16                                            Manipur
 17                                          Meghalaya
 18                                            Mizoram
 19                                           Nagaland
 20                                             Odisha
 21                                             Punjab
 22                                          Rajasthan
 23                                             Sikkim
 24                                         Tamil Nadu
 25                                          Telangana
 26                                            Tripura
 27                                      Uttar Pradesh
 28                                        Uttarakhand
 29                                        West Bengal
 30                                  Andaman & Nicobar
 31                                         Chandigarh
 32                               Dadra & Nagar Haveli
 33                                        Daman & Diu
 34                                              Delhi
 35                                    Jammu & Kashmir
 36                                             Ladakh
 37                                        Lakshadweep
 38                                         Puducherry
 39                                              TOTAL

                                                     2  \
 0   Total Wildlife Sanctuaries of India State Wise...
 1                                    State Area (km²)
 2                                              160229
 3                                               83743
 4                                               78438
 5                                               94163
 6                                              135191
 7                                                3702
 8                                              196022
 9                                               44212
 10                                              55673
 11                                              79714
 12                                             191791
 13                                              38863
 14                                             308245
 15                                             307713
 16                                              22327
 17                                              22429
 18                                              21081
 19                                              16579
 20                                             155707
 21                                              50362
 22                                             342239
 23                                               7096
 24                                             130058
 25                                             114840
 26                                              10486
 27                                             240928
 28                                              53483
 29                                              88752
 30                                               8249
 31                                                114
 32                                                491
 33                                                112
 34                                               1483
 35                                             163090
 36                                              59146
 37                                                 32
 38                                                480
 39                                            3287263

                                                     3  \
 0   Total Wildlife Sanctuaries of India State Wise...
 1                           No. of Wildlife Sanctuary
 2                                                  13
 3                                                  13
 4                                                  17
 5                                                  12
 6                                                  11
 7                                                   6
 8                                                  23
 9                                                   7
 10                                                 28
 11                                                 11
 12                                                 38
 13                                                 18
 14                                                 24
 15                                                 49
 16                                                  7
 17                                                  4
 18                                                  9
 19                                                  4
 20                                                 19
 21                                                 13
 22                                                 25
 23                                                  7
 24                                                 33
 25                                                  9
 26                                                  4
 27                                                 26
 28                                                  7
 29                                                 16
 30                                                 97
 31                                                  2
 32                                                  1
 33                                                  1
 34                                                  1
 35                                                 14
 36                                                  2
 37                                                  1
 38                                                  1
 39                                                573

                                                     4  \
 0   Total Wildlife Sanctuaries of India State Wise...
 1                                          Area (km²)
 2                                             6771.40
 3                                             7614.56
 4                                             1728.95
 5                                             2851.67
 6                                             3760.28
 7                                              647.91
 8                                            16618.42
 9                                              118.21
 10                                            6115.97
 11                                            1955.82
 12                                            8216.69
 13                                            2156.21
 14                                            7046.19
 15                                            7861.70
 16                                             708.14
 17                                              94.11
 18                                            1359.75
 19                                              43.91
 20                                            7094.65
 21                                             326.60
 22                                            5592.38
 23                                             399.10
 24                                            7096.54
 25                                            5672.70
 26                                             603.64
 27                                            5822.20
 28                                            2690.12
 29                                            1440.18
 30                                             395.60
 31                                              26.01
 32                                              92.17
 33                                               2.19
 34                                              19.61
 35                                            1815.04
 36                                            9000.00
 37                                               0.01
 38                                               3.90
 39                                          123762.56

                                                     5
 0   Total Wildlife Sanctuaries of India State Wise...
 1                                     % of State Area
 2                                                4.23
 3                                                9.09
 4                                                2.20
 5                                                3.03
 6                                                2.78
 7                                               17.50
 8                                                8.48
 9                                                0.27
 10                                              10.99
 11                                               2.45
 12                                               4.28
 13                                               5.55
 14                                               2.29
 15                                               2.55
 16                                               3.17
 17                                               0.42
 18                                               6.45
 19                                               0.26
 20                                               4.56
 21                                               0.65
 22                                               1.63
 23                                               5.62
 24                                               5.46
 25                                               4.94
 26                                               5.76
 27                                               2.42
 28                                               5.03
 29                                               1.62
 30                                               4.80
 31                                              22.82
 32                                              18.77
 33                                               1.96
 34                                               1.32
 35                                               1.11
 36                                              15.22
 37                                               0.03
 38                                               0.81
 39                                               3.76  ,
   Top 10 Largest Wildlife Sanctuaries in India 2026  \
                                                Rank
 0                                                 1
 1                                                 2
 2                                                 3
 3                                                 4
 4                                                 5
 5                                                 6
 6                                                 7
 7                                                 8
 8                                                 9
 9                                                10


                            Wildlife Sanctuary Area (km²)        Location
 0             Kutch Desert Wildlife Sanctuary    7506.22         Gujarat
 1                   Indian Wild Ass Sanctuary    4954.00         Gujarat
 2                        Desert National Park    3162.00       Rajasthan
 3              Great Indian Bustard Sanctuary    1222.00     Maharashtra
 4               Achanakmar Wildlife Sanctuary     914.02    Chhattisgarh
 5                    Manas Wildlife Sanctuary     950.00           Assam
 6                    Koyna Wildlife Sanctuary     423.55     Maharashtra
 7                   Bhadra Wildlife Sanctuary     492.46       Karnataka
 8  Nagarjunsagar–Srisailam Wildlife Sanctuary    3568.00  Andhra Pradesh
 9               Sundarbans Wildlife Sanctuary     362.40     West Bengal  ,
   Top 10 Smallest Wildlife Sanctuaries in India 2026  \
                                                 Rank
 0                                                  1
 1                                                  2
 2                                                  3
 3                                                  4
 4                                                  5
 5                                                  6
 6                                                  7
 7                                                  8
 8                                                  9
 9                                                 10


                  Wildlife Sanctuary Area (km²)       Location
 0    Mayureshwar Wildlife Sanctuary       5.14    Maharashtra
 1            Bor Wildlife Sanctuary      61.10    Maharashtra
 2        Chilika Wildlife Sanctuary      15.53         Odisha
 3         Bondla Wildlife Sanctuary       7.98            Goa
 4  Mahavir Swami Wildlife Sanctuary       5.40  Uttar Pradesh
 5    Kinnerasani Wildlife Sanctuary     635.40      Telangana
 6       Pobitora Wildlife Sanctuary      38.80          Assam
 7           Kutch Bustard Sanctuary       2.00        Gujarat
 8         Nangal Wildlife Sanctuary       3.00         Punjab
 9           Thol Wildlife Sanctuary       7.00        Gujarat  ,
                                                      0  \
 0    Wildlife Sanctuaries of India State Wise List ...
 1                                                S No.
 2                                                   1.
 3                                                   1.
 4                                                   1.
 ..                                                 ...
 102                                                26.
 103                                                26.
 104                                                26.
 105                                                26.
 106                                                26.

                                                      1  \
 0    Wildlife Sanctuaries of India State Wise List ...
 1                                               States
 2                                                Assam
 3                                                Assam
 4                                                Assam
 ..                                                 ...
 102                                        West Bengal
 103                                        West Bengal
 104                                        West Bengal
 105                                        West Bengal
 106                                        West Bengal

                                                      2
 0    Wildlife Sanctuaries of India State Wise List ...
 1                                 Wildlife Sanctuaries
 2                            Nambor Wildlife Sanctuary
 3                     Dihing Patkai Wildlife Sanctuary
 4                East Karbi Anglong Wildlife Sanctuary
 ..                                                 ...
 102                      Chintamani Kar Bird Sanctuary
 103                  Haliday Island Wildlife Sanctuary
 104                       Ballavpur Wildlife Sanctuary
 105                  Lothian Island Wildlife Sanctuary
 106                       Mahananda Wildlife Sanctuary

 [107 rows x 3 columns],
                                                     0  \
 0   Wildlife Sanctuaries of India Union Territory ...
 1                                               S No.
 2                                                  1.
 3                                                  1.
 4                                                  1.
 5                                                  1.
 6                                                  1.
 7                                                  2.
 8                                                  2.
 9                                                  2.
 10                                                 3.
 11                                                 4.
 12                                                 4.

                                                     1  \
 0   Wildlife Sanctuaries of India Union Territory ...
 1                                                 UTs
 2                         Andaman and Nicobar Islands
 3                         Andaman and Nicobar Islands
 4                         Andaman and Nicobar Islands
 5                         Andaman and Nicobar Islands
 6                         Andaman and Nicobar Islands
 7                                     Jammu & Kashmir
 8                                     Jammu & Kashmir
 9                                     Jammu & Kashmir
 10                                        Lakshadweep
 11               Dadra Nagar Haveli and Daman and Diu
 12               Dadra Nagar Haveli and Daman and Diu


In [131]:
final1=df1[2]

In [132]:
final1

  Top 10 Smallest Wildlife Sanctuaries in India 2026  \
                                                Rank
0                                                  1
1                                                  2
2                                                  3
3                                                  4
4                                                  5
5                                                  6
6                                                  7
7                                                  8
8                                                  9
9                                                 10


                 Wildlife Sanctuary Area (km²)       Location
0    Mayureshwar Wildlife Sanctuary       5.14    Maharashtra
1            Bor Wildlife Sanctuary      61.10    Maharashtra
2        Chilika Wildlife Sanctuary      15.53         Odisha
3         Bondla Wildlife Sanctuary       7.98            Goa
4  Mahavir Swami Wildlife Sanctuary       5.40  Uttar Pradesh
5    Kinnerasani Wildlife Sanctuary     635.40      Telangana
6       Pobitora Wildlife Sanctuary      38.80          Assam
7           Kutch Bustard Sanctuary       2.00        Gujarat
8         Nangal Wildlife Sanctuary       3.00         Punjab
9           Thol Wildlife Sanctuary       7.00        Gujarat

In [ ]:
from sqlalchemy import craete_engine

In [ ]:
conn = create_engine('')

In [209]:
readcsv=pd.read_csv(r"C:\Users\ASUS\Desktop\s\covid.csv")

In [38]:
readcsv

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],894,7114321,779135536
1,NaN,Peru,6603,221071,4533813
2,NaN,Bulgaria,5681,38778,1341094
3,NaN,North Macedonia,5429,9991,352093
4,NaN,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...,...
235,NaN,Pitcairn Islands,0,0,4
236,NaN,Tokelau,0,0,80
237,NaN,North Korea,0,0,0
238,NaN,Turkmenistan,0,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [39]:
readcsv.shape #gives total no of rows , columns

(240, 5)

In [40]:
readcsv.dtypes  #colomns data types

Unnamed: 0          object
Country             object
Deaths / million    object
Deaths              object
Cases               object
dtype: object

In [ ]:
pythom --str
pandas--object

In [41]:
readcsv.info() #get concise summary of teh Dataframe
#exact same work of readcsv.dtypes()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1 non-null      object
 1   Country           240 non-null    object
 2   Deaths / million  240 non-null    object
 3   Deaths            240 non-null    object
 4   Cases             240 non-null    object
dtypes: object(5)
memory usage: 9.5+ KB

In [42]:
readcsv.ndim #dimensions as in rows n coloumns

2

In [236]:
readcsv.describe() #numerical col
#gives breif info abt ur data

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
count,1,240,240,240,240
unique,1,240,222,223,239
top,↑ Countries which do not report data for a col...,World[a],0,0,0
freq,1,1,8,8,2

In [44]:
readcsv.size #total no of elements

1200

In [211]:
#how to fetch columns from dataframe
readcsv.columns

Index(['Unnamed: 0', 'Country', 'Deaths / million', 'Deaths', 'Cases'], dtype='object')

In [45]:
readcsv['Country'] #if u want to fetch 1 column

0                                               World[a]
1                                                   Peru
2                                               Bulgaria
3                                        North Macedonia
4                                 Bosnia and Herzegovina
                             ...
235                                     Pitcairn Islands
236                                              Tokelau
237                                          North Korea
238                                         Turkmenistan
239    ↑ Countries which do not report data for a col...
Name: Country, Length: 240, dtype: object

In [214]:
readcsv.Country #if u want to fetch 1 column

0                                               World[a]
1                                                   Peru
2                                               Bulgaria
3                                        North Macedonia
4                                 Bosnia and Herzegovina
                             ...
235                                     Pitcairn Islands
236                                              Tokelau
237                                          North Korea
238                                         Turkmenistan
239    ↑ Countries which do not report data for a col...
Name: Country, Length: 240, dtype: object

In [218]:
#if u need multiple columns we need to pass list
readcsv[['Country','Deaths','Cases']]
#ifu want to store in variable u can
#final= readcsv[['Country','Deaths','Cases']]

,Country,Deaths,Cases
0,World[a],7114321,779135536
1,Peru,221071,4533813
2,Bulgaria,38778,1341094
3,North Macedonia,9991,352093
4,Bosnia and Herzegovina,16419,404289
...,...,...,...
235,Pitcairn Islands,0,4
236,Tokelau,0,80
237,North Korea,0,0
238,Turkmenistan,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [222]:
readcsv[[col for col in readcsv.columns if col.startswith("C")]]

,Country,Cases
0,World[a],779135536
1,Peru,4533813
2,Bulgaria,1341094
3,North Macedonia,352093
4,Bosnia and Herzegovina,404289
...,...,...
235,Pitcairn Islands,4
236,Tokelau,80
237,North Korea,0
238,Turkmenistan,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [223]:
#if u wanna savein variable then
col1 = [col for col in readcsv.columns if col.startswith("C")]

In [224]:
readcsv[col1]

,Country,Cases
0,World[a],779135536
1,Peru,4533813
2,Bulgaria,1341094
3,North Macedonia,352093
4,Bosnia and Herzegovina,404289
...,...,...
235,Pitcairn Islands,4
236,Tokelau,80
237,North Korea,0
238,Turkmenistan,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [225]:
readcsv[[col for col in readcsv.columns if not col.startswith("C")]]

,Unnamed: 0,Deaths / million,Deaths
0,NaN,894,7114321
1,NaN,6603,221071
2,NaN,5681,38778
3,NaN,5429,9991
4,NaN,5123,16419
...,...,...,...
235,NaN,0,0
236,NaN,0,0
237,NaN,0,0
238,NaN,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [226]:
readcsv['Country'].value_counts()

Country
World[a]                                                                                                                                                                                                                                                                                                                                             1
Peru                                                                                                                                                                                                                                                                                                                                                 1
Dominican Republic                                                                                                                                                                                                                                                                                                                                   1
Greenland                                                                                                                                                                                                                                                                                                                                            1
India                                                                                                                                                                                                                                                                                                                                                1
                                                                                                                                                                                                                                                                                                                                                    ..
United States Virgin Islands                                                                                                                                                                                                                                                                                                                         1
Cyprus                                                                                                                                                                                                                                                                                                                                               1
Caribbean Netherlands                                                                                                                                                                                                                                                                                                                                1
Canada                                                                                                                                                                                                                                                                                                                                               1
↑ Countries which do not report data for a column are not included in that column's world total. ↑ Data on member states of the European Union are individually listed, but are also summed here for convenience. They are not double-counted in world totals. ↑ Does not include special administrative regions (Hong Kong and Macau) or Taiwan.    1
Name: count, Length: 240, dtype: int64

In [227]:
readcsv['Country'].unique()

array(['World[a]', 'Peru', 'Bulgaria', 'North Macedonia',
       'Bosnia and Herzegovina', 'Hungary', 'Croatia', 'Slovenia',
       'Georgia', 'Montenegro', 'Czech Republic', 'Latvia', 'Moldova',
       'Slovakia', 'Greece', 'San Marino', 'United States', 'Romania',
       'Lithuania', 'United Kingdom', 'Brazil', 'Italy', 'Chile',
       'Martinique', 'Poland', 'Armenia', 'Gibraltar', 'Belgium',
       'Paraguay', 'Trinidad and Tobago', 'Argentina', 'Portugal',
       'European Union[b]', 'Sweden', 'Russia', 'Colombia', 'Aruba',
       'Ukraine', 'Serbia', 'Guadeloupe', 'France', 'Mexico', 'Estonia',
       'Spain', 'Bermuda', 'Guam', 'Austria', 'Tunisia',
       'French Polynesia', 'Saint Lucia', 'Uruguay', 'Liechtenstein',
       'Suriname', 'Sint Maarten', 'Bahamas', 'Malta', 'Barbados',
       'Germany', 'Finland', 'Grenada', 'Ecuador', 'Panama', 'Andorra',
       'Republic of Ireland', 'Lebanon', 'Kosovo', 'Bolivia',
       'Costa Rica', 'Puerto Rico', 'Hong Kong', 'Montserrat', 'Monaco',
       'Belize', 'Denmark', 'British Virgin Islands', 'Curaçao',
       'South Africa', 'Iran', 'Switzerland', 'Guyana',
       'Collectivity of Saint Martin', 'Antigua and Barbuda', 'Jersey',
       'Luxembourg', 'United States Virgin Islands', 'Cyprus',
       'Caribbean Netherlands', 'Canada', 'Namibia', 'Israel',
       'French Guiana', 'Isle of Man', 'Seychelles', 'Netherlands',
       'Jamaica', 'Albania', 'Jordan', 'Saint Vincent and the Grenadines',
       'Eswatini', 'Turkey', 'Botswana', 'Guatemala', 'Dominica',
       'New Caledonia', 'Malaysia', 'Palestine', 'Honduras', 'Réunion',
       'Guernsey', 'Norway', 'Azerbaijan', 'Bahrain',
       'Saint Kitts and Nevis', 'Oman', 'Australia', 'Fiji', 'Kazakhstan',
       'Turks and Caicos Islands', 'Libya', 'Northern Mariana Islands',
       'New Zealand', 'Anguilla', 'Mauritius', 'Cabo Verde',
       'Wallis and Futuna', 'Belarus', 'Cuba', 'Sri Lanka', 'Taiwan',
       'American Samoa', 'South Korea', 'El Salvador', 'Mongolia',
       'Mayotte', 'Maldives', 'Japan', 'Philippines', 'Indonesia',
       'Federated States of Micronesia', 'Iraq', 'Palau', 'Kuwait',
       'Faroe Islands', 'Cayman Islands', 'Iceland', 'Thailand',
       'Saint Barthélemy', 'Morocco', 'Vietnam', 'Marshall Islands',
       'Nepal', 'Brunei', 'Dominican Republic', 'Greenland', 'India',
       'Myanmar', 'Singapore', 'Zimbabwe', 'Sao Tome and Principe',
       'Saint Pierre and Miquelon', 'Lesotho', 'Saudi Arabia',
       'Solomon Islands', 'Qatar', 'United Arab Emirates', 'Egypt',
       'Venezuela', 'Mauritania', 'Zambia', 'Afghanistan', 'Comoros',
       'Kiribati', 'Cambodia', 'Bangladesh', 'Macau', 'Djibouti',
       'Algeria', 'Kyrgyzstan', 'Samoa', 'Gambia', 'Syria',
       'Cook Islands', 'Malawi', 'Gabon', 'Pakistan', 'Tonga', 'Senegal',
       'Rwanda', 'Kenya', 'Sudan', 'Equatorial Guinea', 'Timor-Leste',
       'Tuvalu', 'Laos', 'China[c]', 'Nauru', 'Guinea-Bissau', 'Uganda',
       'Somalia', 'Haiti', 'Cameroon', 'Mozambique', 'Papua New Guinea',
       'Republic of the Congo', 'Ethiopia', 'Yemen', 'Liberia', 'Angola',
       'Madagascar', 'Vanuatu', 'Ghana', 'Nicaragua', 'Togo', 'Guinea',
       'Mali', 'Eritrea', 'Uzbekistan', 'Ivory Coast', 'Bhutan',
       'Central African Republic', 'Burkina Faso', 'Sierra Leone',
       'Democratic Republic of the Congo', 'Nigeria', 'South Sudan',
       'Tanzania', 'Niger', 'Tajikistan', 'Benin', 'Chad', 'Burundi',
       'Vatican City', 'Niue', 'Falkland Islands',
       'Saint Helena, Ascension and Tristan da Cunha', 'Pitcairn Islands',
       'Tokelau', 'North Korea', 'Turkmenistan',
       "↑ Countries which do not report data for a column are not included in that column's world total. ↑ Data on member states of the European Union are individually listed, but are also summed here for convenience. They are not double-counted in world totals. ↑ Does not include special administrative regions (Hong Kong and Macau) or Taiwan."],
      dtype=object)

In [228]:
readcsv['Country'].nunique() 
#to count of many no of uniques

240

In [230]:
readcsv.index 
#index is +1 like last index is 239

RangeIndex(start=0, stop=240, step=1)

In [231]:
readcsv.memory_usage()
#kontya col ni kiti memory ghetli ahe

Index                132
Unnamed: 0          1920
Country             1920
Deaths / million    1920
Deaths              1920
Cases               1920
dtype: int64

In [ ]:
=================
DATA SELECTION FROM DATA FRAME
================

In [ ]:
df.loc[]--label based indexing for rows and columns
df.iloc[]--Integer location based indexing for rows n columns

In [ ]:
loc : label based col name  filtering
we need subset of data frame ie a part of dataframe

In [238]:
dff

   id  name city
0   1     a    d
1   2    aa   gt
2   3  aaaa   hj

In [ ]:
loc[row:col]  #to fetch single rown col

range -- stop value is inclsuive 
only loc in entire data science has -stop value  inclusive 


else
range
iloc etc has stop value exclusive ---stop -1

In [240]:
dff.loc[0,'name'] #col name to be in ''

'a'

In [ ]:
# loc[row_start:row_end, col_start: col_end]
# when i need multiple rows n cols
# : used when rows n colms are in continous i.e id, name, city i want all 3
# but if i want only id n city then use list

In [242]:
dff.loc[0:1,'id':'city']

   id name city
0   1    a    d
1   2   aa   gt

In [243]:
dff.loc[0:1,["id","city"]]

   id city
0   1    d
1   2   gt

In [244]:
dff.loc[[0,2],["id","city"]]

   id city
0   1    d
2   3   hj

In [245]:
dff.loc[1:2,'name':'city']

   name city
1    aa   gt
2  aaaa   hj

In [248]:
dff.loc[1:2,['city']]

  city
1   gt
2   hj

In [249]:
dff.loc[1:2,'city']

1    gt
2    hj
Name: city, dtype: object

In [254]:
dff1 =  pd.read_html("COVID-19 pandemic by country and territory - Wikipedia.html")

In [255]:
final1 = dff1[12]

In [256]:
final1

,Unnamed: 0,Country,Deaths / million,Deaths,Cases
0,NaN,World[a],894,7114321,779135536
1,NaN,Peru,6603,221071,4533813
2,NaN,Bulgaria,5681,38778,1341094
3,NaN,North Macedonia,5429,9991,352093
4,NaN,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...,...
235,NaN,Pitcairn Islands,0,0,4
236,NaN,Tokelau,0,0,80
237,NaN,North Korea,0,0,0
238,NaN,Turkmenistan,0,0,0
239,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...,↑ Countries which do not report data for a col...

In [259]:
final.loc[0:238,'Country':'Cases']

,Country,Deaths / million,Deaths,Cases
0,World[a],894,7114321,779135536
1,Peru,6603,221071,4533813
2,Bulgaria,5681,38778,1341094
3,North Macedonia,5429,9991,352093
4,Bosnia and Herzegovina,5123,16419,404289
...,...,...,...,...
234,"Saint Helena, Ascension and Tristan da Cunha",0,0,2166
235,Pitcairn Islands,0,0,4
236,Tokelau,0,0,80
237,North Korea,0,0,0
238,Turkmenistan,0,0,0

In [ ]:
iloc----------integer based location 
here instead of col name we will use col integer location no
starts with 0,1,2....

range--stop value is exclusive i,.e u have to give +1

In [261]:
dff.iloc[0:2,0:3]

   id name city
0   1    a    d
1   2   aa   gt

In [262]:
final1.iloc[0:239,0:4]

,Unnamed: 0,Country,Deaths / million,Deaths
0,NaN,World[a],894,7114321
1,NaN,Peru,6603,221071
2,NaN,Bulgaria,5681,38778
3,NaN,North Macedonia,5429,9991
4,NaN,Bosnia and Herzegovina,5123,16419
...,...,...,...,...
234,NaN,"Saint Helena, Ascension and Tristan da Cunha",0,0
235,NaN,Pitcairn Islands,0,0
236,NaN,Tokelau,0,0
237,NaN,North Korea,0,0
238,NaN,Turkmenistan,0,0

In [ ]:
data Selection tech
loc vs iloc
loc---label based indexing
stop value inclsuiove


iloc--
integer based indexing
stop value is exclusive

In [ ]:
df.at[] Access a single value for a given row /column pair (label based)
df.iat[] Access a single value for a given row /column pair (integer based)
df.query()  query dataframe with an expression

In [263]:
dff.at[1,'name']

'aa'

In [265]:
dff.iat[1,1]

'aa'

In [266]:
dff.at[0,'city']='pune' #if i want to change/update a single value

In [267]:
dff

   id  name  city
0   1     a  pune
1   2    aa    gt
2   3  aaaa    hj

In [269]:
dff.iat[0,1] = 'Rajasthan'

In [270]:
dff

   id       name  city
0   1  Rajasthan  pune
1   2         aa    gt
2   3       aaaa    hj

In [ ]:
apply filter data based on condition

In [274]:
dfdf=pd.read_csv(r"C:\Users\ASUS\Desktop\s\employees.csv")

In [275]:
dfdf

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [276]:
dfdf['Team']=='Sales'

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999     True
Name: Team, Length: 1000, dtype: bool

In [277]:
dfdf[dfdf['Team']=='Sales'] # i did wrapping
#if i need entire data frame
#instead of puttingh in new variavble n using memory just overwrite it

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
35,Theresa,Female,10/10/2006,1:12 AM,85182,16.675,False,Sales
45,Roger,Male,4/17/1980,11:32 AM,88010,13.886,True,Sales
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales
51,NaN,NaN,12/17/2011,8:29 AM,41126,14.009,NaN,Sales
...,...,...,...,...,...,...,...,...
963,Ann,Female,9/23/1994,11:15 AM,89443,17.940,True,Sales
964,Bruce,Male,5/7/1980,8:00 PM,35802,12.391,True,Sales
972,Victor,NaN,7/28/2006,2:49 PM,76381,11.159,True,Sales
975,Susan,Female,4/7/1995,10:05 PM,92436,12.467,False,Sales
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [281]:
#if i want morethan 1 teams 
dfdf[((dfdf['Team']=='Sales') | (dfdf['Team']=='Finance'))]
#here logical or  -- | is used   and --&
#Wrap each condition in round brackets (e.g., (df['A'] > 1) | (df['B'] < 5))
#because bitwise operators have higher priority than comparison operators.

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
...,...,...,...,...,...,...,...,...
975,Susan,Female,4/7/1995,10:05 PM,92436,12.467,False,Sales
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [284]:
dfdf[~((dfdf['Team']=='Sales') | (dfdf['Team']=='Finance'))]
#  ~ negation is used oif mala hai 2 team sodun bakiche teams pahije ahet

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
993,Tina,Female,5/15/1997,3:53 PM,56450,19.040,True,Engineering
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development

In [286]:
#if u want add multiple colnmns but u cant write and or again n again
dfdf[dfdf['Team'].isin(['Distribution','Sales','Finance'])]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
...,...,...,...,...,...,...,...,...
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [283]:
dfdf[((dfdf['Salary']>10000) & (dfdf['Team']=='Sales'))]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
35,Theresa,Female,10/10/2006,1:12 AM,85182,16.675,False,Sales
45,Roger,Male,4/17/1980,11:32 AM,88010,13.886,True,Sales
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales
51,NaN,NaN,12/17/2011,8:29 AM,41126,14.009,NaN,Sales
...,...,...,...,...,...,...,...,...
963,Ann,Female,9/23/1994,11:15 AM,89443,17.940,True,Sales
964,Bruce,Male,5/7/1980,8:00 PM,35802,12.391,True,Sales
972,Victor,NaN,7/28/2006,2:49 PM,76381,11.159,True,Sales
975,Susan,Female,4/7/1995,10:05 PM,92436,12.467,False,Sales
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [291]:
dfdf[dfdf['First Name'].str.startswith('A')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [ ]:
the result contains NaN instead of only True or False.

Filtering requires a boolean mask:
Pandas doesn't know whether to include or exclude the NaN row, so it raises the error.

In [295]:
#metho 1
dfdf[dfdf['First Name'].str.startswith('A', na=False)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
53,Alan,NaN,3/3/2014,1:28 PM,40341,17.578,True,Finance
86,Annie,NaN,9/29/2007,12:11 AM,103495,17.290,True,Business Development
87,Annie,Female,1/30/1993,2:05 AM,144887,8.276,True,Sales
101,Aaron,Male,2/17/2012,10:20 AM,61602,11.849,True,Marketing
...,...,...,...,...,...,...,...,...
963,Ann,Female,9/23/1994,11:15 AM,89443,17.940,True,Sales
970,Alice,Female,9/3/1988,8:54 PM,63571,15.397,True,Product
988,Alice,Female,10/5/2004,9:34 AM,47638,11.209,False,Human Resources
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [296]:
#metho2

dfdf = dfdf.dropna(subset=['First Name'])
dfdf[dfdf['First Name'].str.startswith('A')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
53,Alan,NaN,3/3/2014,1:28 PM,40341,17.578,True,Finance
86,Annie,NaN,9/29/2007,12:11 AM,103495,17.290,True,Business Development
87,Annie,Female,1/30/1993,2:05 AM,144887,8.276,True,Sales
101,Aaron,Male,2/17/2012,10:20 AM,61602,11.849,True,Marketing
...,...,...,...,...,...,...,...,...
963,Ann,Female,9/23/1994,11:15 AM,89443,17.940,True,Sales
970,Alice,Female,9/3/1988,8:54 PM,63571,15.397,True,Product
988,Alice,Female,10/5/2004,9:34 AM,47638,11.209,False,Human Resources
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [298]:
#metho3 

dfdf['First Name'] = dfdf['First Name'].fillna('')
dfdf[dfdf['First Name'].str.startswith('A')]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\1368207584.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf['First Name'] = dfdf['First Name'].fillna('')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
53,Alan,NaN,3/3/2014,1:28 PM,40341,17.578,True,Finance
86,Annie,NaN,9/29/2007,12:11 AM,103495,17.290,True,Business Development
87,Annie,Female,1/30/1993,2:05 AM,144887,8.276,True,Sales
101,Aaron,Male,2/17/2012,10:20 AM,61602,11.849,True,Marketing
...,...,...,...,...,...,...,...,...
963,Ann,Female,9/23/1994,11:15 AM,89443,17.940,True,Sales
970,Alice,Female,9/3/1988,8:54 PM,63571,15.397,True,Product
988,Alice,Female,10/5/2004,9:34 AM,47638,11.209,False,Human Resources
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
# Notice this is a warning, not an error.
# Your code may still work, but Pandas is warning that the changes might not be applied to the original DataFrame.

# df = pd.read_csv("employee.csv")

# dfdf = df[df["Salary"] > 50000]
# dfdf is created from df.

# Pandas asks:
# "Should I modify only dfdf, or should I also modify the original df?"
# Since it isn't sure, it gives the warning.



# dfdf.loc[:, 'First Name'] = dfdf['First Name'].fillna('')
# .loc[rows, columns]
# : means all rows.



    
# Create an independent copy.
# When creating dfdf, do:
# dfdf = df[df['Salary'] > 50000].copy()
# dfdf['First Name'] = dfdf['First Name'].fillna('')

In [ ]:
# What is SettingWithCopyWarning?

# SettingWithCopyWarning occurs when we try to modify a DataFrame that is actually a slice of another DataFrame.
# Pandas warns because it cannot determine whether the changes should affect only the slice or the original 
# DataFrame. This can be avoided by using .loc[] for assignment or by creating a copy of the DataFrame using .copy()



# We use .copy() to create an independent DataFrame. This prevents SettingWithCopyWarning and ensures that changes 
# made to the new DataFrame do not accidentally affect the original DataFrame.

In [297]:
dfdf[dfdf['First Name'].str.contains('og')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
45,Roger,Male,4/17/1980,11:32 AM,88010,13.886,True,Sales
187,Roger,Male,11/19/2004,3:55 PM,51430,6.460,False,Marketing
202,Roger,Male,11/8/1982,2:32 AM,140558,5.084,True,Sales
503,Roger,Male,8/3/2015,4:56 PM,125033,4.887,True,Marketing
544,Roger,Male,7/3/2010,5:11 PM,105689,13.320,True,Marketing
764,Roger,Male,5/2/1988,10:04 PM,115582,15.343,True,Sales

In [ ]:
pandas has 9000 pages documentation
we have automation

In [304]:
dfdf.query("Salary>90000 and Team == 'Finance' and Gender == 'Male'")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
56,Carl,Male,5/3/2006,5:55 PM,130276,16.084,True,Finance
83,Shawn,Male,9/23/2005,2:55 AM,148115,6.539,True,Finance
117,Steven,Male,3/1/1995,3:03 PM,109095,9.494,False,Finance
205,Brandon,Male,3/27/2006,5:54 PM,115711,8.012,True,Finance
219,Billy,Male,3/13/1995,12:05 PM,120444,7.768,True,Finance
241,Walter,Male,7/6/1983,11:54 PM,127813,5.961,False,Finance
318,Roy,Male,8/6/2006,7:52 AM,148225,1.841,False,Finance
348,Philip,Male,8/2/1989,11:21 AM,129968,19.897,False,Finance
420,Justin,Male,5/22/1986,6:30 AM,121508,19.334,True,Finance
458,Albert,Male,9/30/2007,5:34 PM,102626,15.843,False,Finance
725,Jeremy,Male,5/19/1991,1:40 PM,131513,1.876,True,Finance
790,Fred,Male,3/3/1989,2:27 AM,129712,11.058,False,Finance
837,Joseph,Male,5/23/1985,10:16 PM,139570,15.804,True,Finance
861,Jerry,Male,3/26/1989,4:15 AM,140850,18.855,False,Finance
891,Timothy,Male,8/25/1991,10:37 AM,92587,8.475,False,Finance
954,Joe,Male,1/19/1980,4:06 PM,119667,1.148,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance

In [305]:
dfdf.head()
#bydefualt return the first 5 rows

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [306]:
dfdf.head(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN

In [307]:
dfdf.tail()
#returnsd last 5

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [310]:
dfdf.sample(5)
#getrandom samples from the dataframe

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
114,Ashley,Female,8/4/2002,11:00 AM,58698,6.811,True,Business Development
631,Jason,NaN,3/6/2008,1:20 AM,82873,1.869,False,Client Services
350,Thomas,NaN,8/31/1995,8:31 PM,41549,3.950,False,Sales
931,Harold,Male,6/23/2012,12:40 PM,140444,3.771,False,Distribution
634,Carl,Male,3/30/1987,5:59 PM,75598,19.289,False,NaN

In [313]:
dfdf.get('First Name')
# like dictonary...retrive a column by name to fetch single colms

0      Douglas
1       Thomas
2        Maria
3        Jerry
4        Larry
        ...
995      Henry
996    Phillip
997    Russell
998      Larry
999     Albert
Name: First Name, Length: 933, dtype: object

In [317]:
#select col baed on their data types
dfdf.select_dtypes("int")

     Salary
0     97308
1     61933
2    130590
3    138705
4    101004
..      ...
995  132483
996   42392
997   96914
998   60500
999  129949

[933 rows x 1 columns]

In [314]:
dfdf.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [318]:
dfdf.select_dtypes("O")

,First Name,Gender,Start Date,Last Login Time,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,True,Client Services
...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,False,Product
998,Larry,Male,4/20/2013,4:45 PM,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,True,Sales

In [322]:
dfdf['test'] = dfdf['Team'].str.replace("Product","PP")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\88435544.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf['test'] = dfdf['Team'].str.replace("Product","PP")

In [323]:
dfdf

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,test
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,PP
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales

In [328]:
dfdf['double_bonus']= dfdf['Bonus %']*2

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\3914588175.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf['double_bonus']= dfdf['Bonus %']*2

In [329]:
dfdf

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,test,double_bonus
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,13.890
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,NaN,8.340
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,23.716
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,18.680
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,2.778
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,33.310
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,39.350
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,PP,2.842
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,23.970
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,20.338

In [331]:
dfdf.drop('test',axis=1)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,double_bonus
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,13.890
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,8.340
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,23.716
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,18.680
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,2.778
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,33.310
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,39.350
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2.842
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,23.970
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,20.338

In [ ]:
how to delete col from dfdf
axis = 0 operation on row
axis =1  oprat on col

In [332]:
dfdf.drop( 'test', axis=1 )

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,double_bonus
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,13.890
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,8.340
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,23.716
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,18.680
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,2.778
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,33.310
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,39.350
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2.842
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,23.970
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,20.338

In [333]:
dfdf
#test col is still present
#pandas dataframe is immutable
#we need to store in new variable if we want th drop result

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,test,double_bonus
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,13.890
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,NaN,8.340
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,23.716
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,18.680
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,2.778
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,33.310
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,39.350
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,PP,2.842
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,23.970
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,20.338

In [334]:
#method 1
final12 = dfdf.drop( 'test', axis=1 )

In [335]:
final12

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,double_bonus
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,13.890
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,8.340
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,23.716
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,18.680
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,2.778
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,33.310
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,39.350
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2.842
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,23.970
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,20.338

In [336]:
#method 2 
#if i want to save changes in save variable then use inplace = true

dfdf.drop('test', axis = 1, inplace = True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\32865130.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf.drop('test', axis = 1, inplace = True)

In [337]:
dfdf

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,double_bonus
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,13.890
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,8.340
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,23.716
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,18.680
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,2.778
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,33.310
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,39.350
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2.842
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,23.970
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,20.338

In [338]:
dfdf.drop('double_bonus',axis = 1 , inplace = True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\3428576646.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf.drop('double_bonus',axis = 1 , inplace = True)

In [339]:
dfdf

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [340]:
#drop multiple colms

dfdf.drop(columns = ['Start Date' , 'Last Login Time', 'Bonus %'], inplace = True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\2840810999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf.drop(columns = ['Start Date' , 'Last Login Time', 'Bonus %'], inplace = True)

In [341]:
dfdf

    First Name  Gender  Salary Senior Management                  Team
0      Douglas    Male   97308              True             Marketing
1       Thomas    Male   61933              True                   NaN
2        Maria  Female  130590             False               Finance
3        Jerry    Male  138705              True               Finance
4        Larry    Male  101004              True       Client Services
..         ...     ...     ...               ...                   ...
995      Henry     NaN  132483             False          Distribution
996    Phillip    Male   42392             False               Finance
997    Russell    Male   96914             False               Product
998      Larry    Male   60500             False  Business Development
999     Albert    Male  129949              True                 Sales

[933 rows x 5 columns]

In [343]:
#to delete row
#bydefalut axis = 0
dfdf. drop(1, inplace = True) # 1 is index no of row

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\2174297144.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf. drop(1, inplace = True) # 1 is index no of row

In [344]:
dfdf

    First Name  Gender  Salary Senior Management                  Team
0      Douglas    Male   97308              True             Marketing
2        Maria  Female  130590             False               Finance
3        Jerry    Male  138705              True               Finance
4        Larry    Male  101004              True       Client Services
5       Dennis    Male  115163             False                 Legal
..         ...     ...     ...               ...                   ...
995      Henry     NaN  132483             False          Distribution
996    Phillip    Male   42392             False               Finance
997    Russell    Male   96914             False               Product
998      Larry    Male   60500             False  Business Development
999     Albert    Male  129949              True                 Sales

[932 rows x 5 columns]

In [345]:
dfdf.drop([2,5,87], inplace = True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\4036903235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf.drop([2,5,87], inplace = True)

In [346]:
dfdf

    First Name  Gender  Salary Senior Management                  Team
0      Douglas    Male   97308              True             Marketing
3        Jerry    Male  138705              True               Finance
4        Larry    Male  101004              True       Client Services
6         Ruby  Female   65476              True               Product
8       Angela  Female   95570              True           Engineering
..         ...     ...     ...               ...                   ...
995      Henry     NaN  132483             False          Distribution
996    Phillip    Male   42392             False               Finance
997    Russell    Male   96914             False               Product
998      Larry    Male   60500             False  Business Development
999     Albert    Male  129949              True                 Sales

[929 rows x 5 columns]

In [347]:
dfdf.set_index( "empid" , inplace =True)

KeyError: "None of ['empid'] are in the columns"

In [ ]:
df.drop("1026"  , inplace = True)

In [367]:
dfdf.reset_index( inplace =True)

#apan jr kahi rows delete kele tr index no mmadhe gap hoin
#butwe need to be in itagain as 0 1 2 3 4  5....

In [ ]:
col add--col drop
row add--series--row drop

In [350]:
#want to rename 1 or 2 colmns
dfdf.rename({"First Nmae": "Name","Team": "Dept"},axis = 1, inplace = True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\3029695585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfdf.rename({"First Nmae": "Name","Team": "Dept"},axis = 1, inplace = True)

In [369]:
dfdf

,index,infosys_FIRST NAME,infosys_GENDER,infosys_SALARY,infosys_SENIOR MANAGEMENT,infosys_DEPT
0,0,Douglas,Male,97308,True,Marketing
1,3,Jerry,Male,138705,True,Finance
2,4,Larry,Male,101004,True,Client Services
3,6,Ruby,Female,65476,True,Product
4,8,Angela,Female,95570,True,Engineering
...,...,...,...,...,...,...
924,995,Henry,NaN,132483,False,Distribution
925,996,Phillip,Male,42392,False,Finance
926,997,Russell,Male,96914,False,Product
927,998,Larry,Male,60500,False,Business Development
928,999,Albert,Male,129949,True,Sales

In [ ]:
col upper , lower case

In [370]:
dfdf.columns = [col.upper() for col in dfdf.columns]

In [371]:
dfdf

,INDEX,INFOSYS_FIRST NAME,INFOSYS_GENDER,INFOSYS_SALARY,INFOSYS_SENIOR MANAGEMENT,INFOSYS_DEPT
0,0,Douglas,Male,97308,True,Marketing
1,3,Jerry,Male,138705,True,Finance
2,4,Larry,Male,101004,True,Client Services
3,6,Ruby,Female,65476,True,Product
4,8,Angela,Female,95570,True,Engineering
...,...,...,...,...,...,...
924,995,Henry,NaN,132483,False,Distribution
925,996,Phillip,Male,42392,False,Finance
926,997,Russell,Male,96914,False,Product
927,998,Larry,Male,60500,False,Business Development
928,999,Albert,Male,129949,True,Sales

In [358]:
[col.upper() for col in dfdf.columns]

['FIRST NAME', 'GENDER', 'SALARY', 'SENIOR MANAGEMENT', 'DEPT']

In [372]:
dfdf.columns = [col.lower() for col in dfdf.columns]

In [373]:
dfdf

,index,infosys_first name,infosys_gender,infosys_salary,infosys_senior management,infosys_dept
0,0,Douglas,Male,97308,True,Marketing
1,3,Jerry,Male,138705,True,Finance
2,4,Larry,Male,101004,True,Client Services
3,6,Ruby,Female,65476,True,Product
4,8,Angela,Female,95570,True,Engineering
...,...,...,...,...,...,...
924,995,Henry,NaN,132483,False,Distribution
925,996,Phillip,Male,42392,False,Finance
926,997,Russell,Male,96914,False,Product
927,998,Larry,Male,60500,False,Business Development
928,999,Albert,Male,129949,True,Sales

In [ ]:
infosys_colname

In [375]:
#want to rename all colmns
dfdf.columns = ["infosys_{}".format(col) for col in dfdf.columns]

In [376]:
dfdf

,infosys_index,infosys_infosys_first name,infosys_infosys_gender,infosys_infosys_salary,infosys_infosys_senior management,infosys_infosys_dept
0,0,Douglas,Male,97308,True,Marketing
1,3,Jerry,Male,138705,True,Finance
2,4,Larry,Male,101004,True,Client Services
3,6,Ruby,Female,65476,True,Product
4,8,Angela,Female,95570,True,Engineering
...,...,...,...,...,...,...
924,995,Henry,NaN,132483,False,Distribution
925,996,Phillip,Male,42392,False,Finance
926,997,Russell,Male,96914,False,Product
927,998,Larry,Male,60500,False,Business Development
928,999,Albert,Male,129949,True,Sales

In [377]:
dfdf.rename({1:"one", 2 :"two"})

,infosys_index,infosys_infosys_first name,infosys_infosys_gender,infosys_infosys_salary,infosys_infosys_senior management,infosys_infosys_dept
0,0,Douglas,Male,97308,True,Marketing
one,3,Jerry,Male,138705,True,Finance
two,4,Larry,Male,101004,True,Client Services
3,6,Ruby,Female,65476,True,Product
4,8,Angela,Female,95570,True,Engineering
...,...,...,...,...,...,...
924,995,Henry,NaN,132483,False,Distribution
925,996,Phillip,Male,42392,False,Finance
926,997,Russell,Male,96914,False,Product
927,998,Larry,Male,60500,False,Business Development
928,999,Albert,Male,129949,True,Sales

In [381]:
dfd.isnull().sum()
#gives the count of how many null values each colm has

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [ ]:
NAN---COMPLTE RECORD DELETE --LAST OPPTION--DATA LOSS

In [379]:
dfd=pd.read_csv(r"C:\Users\ASUS\Desktop\s\employees.csv")

In [380]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [382]:
dfd.dropna()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
dropna ---delete

how| all
subset
thresh

In [ ]:
how == any| all


any --if in row there is a single NAN value then delete entire row
bydefault any is set

In [383]:
dfd.dropna(how = 'all')
#where complete row is NAN

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [387]:
#drop speciidc colms null 
#kahi colms madhe null nahi chalnar baki madhe chalen like adharno , pan no madhe null nahi pahije
dfd.dropna(subset = ["First Name", "Start Date"])

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
requirement ---out pof 4 colms , any 2 col should have values

2 non null

In [388]:
dfd.dropna(thresh = 2) #non null value should be present

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
till now we droped the null 
now we will fill the nan with something

In [389]:
dfd.fillna(0)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,0
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,0,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [391]:
dfd['Team_fill'] = dfd["Team"].fillna("General")

In [392]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Team_fill
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,General
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales

In [ ]:
numeric col ----mean | median | mode

mean == avg
median === middle value
mode== most frequent value

In [394]:
dfd['Salary'].mean()

np.float64(90662.181)

In [395]:
dfd['Salary'].median()

90428.0

In [397]:
dfd['Team'].mode()
#moed is ofcategorical value

0    Client Services
Name: Team, dtype: object

In [402]:
dfd['Mean Salary'] = dfd['Salary'].fillna(dfd['Salary'].mean())

In [403]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Team_fill,mean salary,Mean Salary
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,97308,97308
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,General,61933,61933
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,130590,130590
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,138705,138705
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,101004,101004
...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,132483,132483
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,42392,42392
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,96914,96914
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,60500,60500
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,129949,129949

In [ ]:
stastical impuatation ---- values impute

In [404]:
dfd['temp'] = dfd['Team'].fillna(method = 'ffill') #forward fill

#compare team n temp

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\4210151131.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfd['temp'] = dfd['Team'].fillna(method = 'ffill') #forward fill

In [405]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Team_fill,mean salary,Mean Salary,temp
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,97308,97308,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,General,61933,61933,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,130590,130590,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,138705,138705,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,101004,101004,Client Services
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,132483,132483,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,42392,42392,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,96914,96914,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,60500,60500,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,129949,129949,Sales

In [ ]:
dfd.drop(columns = ['Team_fill','Mean Salary','team salary'],axis = 1, inplace = True )

In [407]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,mean salary,temp
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,97308,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,61933,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,130590,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,138705,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,101004,Client Services
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,132483,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,42392,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,96914,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,60500,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,129949,Sales

In [410]:
dfd.drop(columns = ['mean salary'],axis = 1, inplace = True )

In [411]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales

In [412]:
dfd['bfill_Team'] = dfd['Team'].fillna(method = 'bfill')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10780\669524685.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfd['bfill_Team'] = dfd['Team'].fillna(method = 'bfill')

In [413]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales

In [ ]:
axis
drop
inplace
dropna
filna

In [414]:
dfd.notnull().sum()
#to check how mnay are not null
#dfd.isnull().sum() to chck null

First Name            933
Gender                855
Start Date           1000
Last Login Time      1000
Salary               1000
Bonus %              1000
Senior Management     933
Team                  957
temp                 1000
bfill_Team           1000
dtype: int64

In [418]:
dfd[dfd['First Name'].isnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,Finance,Finance
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN,Client Services,Client Services
25,NaN,Male,10/8/2012,1:12 AM,37076,18.576,NaN,Client Services,Client Services,Client Services
32,NaN,Male,8/21/1998,2:27 PM,122340,6.417,NaN,NaN,Product,Business Development
39,NaN,Male,1/29/2016,2:33 AM,122173,7.797,NaN,Client Services,Client Services,Client Services
...,...,...,...,...,...,...,...,...,...,...
902,NaN,Male,5/23/2001,7:52 PM,103877,6.322,NaN,Distribution,Distribution,Distribution
925,NaN,Female,8/23/2000,4:19 PM,95866,19.388,NaN,Sales,Sales,Sales
946,NaN,Female,9/15/1985,1:50 AM,133472,16.941,NaN,Distribution,Distribution,Distribution
947,NaN,Male,7/30/2012,3:07 PM,107351,5.329,NaN,Marketing,Marketing,Marketing
951,NaN,Female,9/14/2010,5:19 AM,143638,9.662,NaN,NaN,Business Development,Human Resources

In [417]:
dfd[dfd['First Name'].notnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales

In [420]:

dfd['upper'] = dfd['Team'].str.upper()

In [421]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing,MARKETING
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance,FINANCE
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance,FINANCE
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services,CLIENT SERVICES
...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution,DISTRIBUTION
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance,FINANCE
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product,PRODUCT
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development,BUSINESS DEVELOPMENT
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales,SALES

In [423]:
dfd['Team'].str.split(" ")
#split strings by a dilimiter
#result in list

0                  [Marketing]
1                          NaN
2                    [Finance]
3                    [Finance]
4           [Client, Services]
                ...
995             [Distribution]
996                  [Finance]
997                  [Product]
998    [Business, Development]
999                    [Sales]
Name: Team, Length: 1000, dtype: object

In [424]:
dfd['name len'] = dfd['First Name'].str.len()

In [425]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper,name len
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing,MARKETING,7.0
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance,NaN,6.0
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance,FINANCE,5.0
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance,FINANCE,5.0
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services,CLIENT SERVICES,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution,DISTRIBUTION,5.0
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance,FINANCE,7.0
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product,PRODUCT,7.0
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales,SALES,6.0

In [427]:
#if iwant specific colms
dfd[['First Name' , 'name len' , 'Gender' , 'Team']]

    First Name  name len  Gender                  Team
0      Douglas       7.0    Male             Marketing
1       Thomas       6.0    Male                   NaN
2        Maria       5.0  Female               Finance
3        Jerry       5.0    Male               Finance
4        Larry       5.0    Male       Client Services
..         ...       ...     ...                   ...
995      Henry       5.0     NaN          Distribution
996    Phillip       7.0    Male               Finance
997    Russell       7.0    Male               Product
998      Larry       5.0    Male  Business Development
999     Albert       6.0    Male                 Sales

[1000 rows x 4 columns]

In [438]:
#i want first 3 alphabhets of Name only
dfd['First Name'].str.slice(0,3) # 0 - 2
# o 

#0 is starting index no 
#3 is n-1  index no

0      Dou
1      Tho
2      Mar
3      Jer
4      Lar
      ...
995    Hen
996    Phi
997    Rus
998    Lar
999    Alb
Name: First Name, Length: 1000, dtype: object

In [441]:
dfd['First Name'].str.slice(-4,-1)

0      gla
1      oma
2      ari
3      err
4      arr
      ...
995    enr
996    lli
997    sel
998    arr
999    ber
Name: First Name, Length: 1000, dtype: object

In [429]:
dfd['Team'].str.strip() #remove leading an trailing white spaces

0                 Marketing
1                       NaN
2                   Finance
3                   Finance
4           Client Services
               ...
995            Distribution
996                 Finance
997                 Product
998    Business Development
999                   Sales
Name: Team, Length: 1000, dtype: object

In [431]:
dfd['tsplit'] = dfd['Team'].str.split() #split strings by delimiter

In [432]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper,name len,tsplit
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing,MARKETING,7.0,[Marketing]
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance,NaN,6.0,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance,FINANCE,5.0,[Finance]
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance,FINANCE,5.0,[Finance]
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services,CLIENT SERVICES,5.0,"[Client, Services]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution,DISTRIBUTION,5.0,[Distribution]
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance,FINANCE,7.0,[Finance]
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product,PRODUCT,7.0,[Product]
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]"
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales,SALES,6.0,[Sales]

In [435]:
dfd['namelen'] = dfd['First Name'].str.len()

In [436]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper,name len,tsplit,namelen
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing,MARKETING,7.0,[Marketing],7.0
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance,NaN,6.0,NaN,6.0
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services,CLIENT SERVICES,5.0,"[Client, Services]",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution,DISTRIBUTION,5.0,[Distribution],5.0
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance,FINANCE,7.0,[Finance],7.0
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product,PRODUCT,7.0,[Product],7.0
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales,SALES,6.0,[Sales],6.0

In [ ]:
apply python functions on pandas dataframe
2methods
1] apply - single cpol or complete df
2]map - sinle col

In [445]:
df2 = pd.DataFrame({"a":[1,2,3],
                     "b":[3,4,5],
                     "c":[6,3,6]
                    })

In [446]:
df2

   a  b  c
0  1  3  6
1  2  4  3
2  3  5  6

In [448]:
def sqr_element(element):
    return element**2

In [449]:
df2.apply(sqr_element)

   a   b   c
0  1   9  36
1  4  16   9
2  9  25  36

In [451]:
def fetch_username(name):
    return name[0]

In [455]:
dfd['username'] = dfd['temp'].map(fetch_username)

In [456]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper,name len,tsplit,namelen,username
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing,MARKETING,7.0,[Marketing],7.0,M
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance,NaN,6.0,NaN,6.0,M
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0,F
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0,F
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services,CLIENT SERVICES,5.0,"[Client, Services]",5.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution,DISTRIBUTION,5.0,[Distribution],5.0,D
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance,FINANCE,7.0,[Finance],7.0,F
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product,PRODUCT,7.0,[Product],7.0,P
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales,SALES,6.0,[Sales],6.0,S

In [ ]:
dfd['Start Date']

In [460]:
def year_fetch(record):
    year = record.split('/')[-1]
    return year

In [462]:
dfd['year'] = dfd['Start Date'].map(year_fetch)

In [463]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper,name len,tsplit,namelen,username,year
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing,MARKETING,7.0,[Marketing],7.0,M,1993
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance,NaN,6.0,NaN,6.0,M,1996
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,1993
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,2005
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services,CLIENT SERVICES,5.0,"[Client, Services]",5.0,C,1998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution,DISTRIBUTION,5.0,[Distribution],5.0,D,2014
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance,FINANCE,7.0,[Finance],7.0,F,1984
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product,PRODUCT,7.0,[Product],7.0,P,2013
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B,2013
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales,SALES,6.0,[Sales],6.0,S,2012

In [465]:
dfd['Start Date'].map(lambda x: x.split('/')[-1])

0      1993
1      1996
2      1993
3      2005
4      1998
       ...
995    2014
996    1984
997    2013
998    2013
999    2012
Name: Start Date, Length: 1000, dtype: object

In [ ]:
map functio used on function n datastructure

In [466]:
def sal_15_per(salary):
    per = (salary/100)*15
    return per

In [469]:
dfd['sal_15'] = dfd['Salary'].map(sal_15_per)

In [470]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper,name len,tsplit,namelen,username,year,sal_15
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,Marketing,MARKETING,7.0,[Marketing],7.0,M,1993,14596.20
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Marketing,Finance,NaN,6.0,NaN,6.0,M,1996,9289.95
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,1993,19588.50
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,2005,20805.75
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,Client Services,CLIENT SERVICES,5.0,"[Client, Services]",5.0,C,1998,15150.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,Distribution,DISTRIBUTION,5.0,[Distribution],5.0,D,2014,19872.45
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,Finance,FINANCE,7.0,[Finance],7.0,F,1984,6358.80
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,Product,PRODUCT,7.0,[Product],7.0,P,2013,14537.10
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B,2013,9075.00
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,Sales,SALES,6.0,[Sales],6.0,S,2012,19492.35

In [472]:
df3  = pd.DataFrame({"id":[1,2,3],
                     "name":['a','b','c'],
                      "gen":['m','f','m']
                    })

In [473]:
df3

   id name gen
0   1    a   m
1   2    b   f
2   3    c   m

In [475]:
df3['gen_no'] = df3['gen'].map(lambda x: 1 if x== 'm' else 2)

In [476]:
df3

   id name gen  gen_no
0   1    a   m       1
1   2    b   f       2
2   3    c   m       1

In [481]:
dfd.sort_values("Salary", ascending = False, ignore_index = True)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,temp,bfill_Team,upper,name len,tsplit,namelen,username,year,sal_15
0,Katherine,Female,8/13/1996,12:21 AM,149908,18.912,False,Finance,Finance,Finance,FINANCE,9.0,[Finance],9.0,F,1996,22486.20
1,Rose,Female,5/28/2015,8:40 AM,149903,5.630,False,Human Resources,Human Resources,Human Resources,HUMAN RESOURCES,4.0,"[Human, Resources]",4.0,H,2015,22485.45
2,Cynthia,Female,7/12/2006,8:55 AM,149684,7.864,False,Product,Product,Product,PRODUCT,7.0,[Product],7.0,P,2006,22452.60
3,NaN,Female,2/23/2005,9:50 PM,149654,1.825,NaN,Sales,Sales,Sales,SALES,NaN,[Sales],NaN,S,2005,22448.10
4,Kathy,Female,3/18/2000,7:26 PM,149563,16.991,True,Finance,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,2000,22434.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Cynthia,Female,7/5/1986,1:24 AM,35381,11.749,False,Finance,Finance,Finance,FINANCE,7.0,[Finance],7.0,F,1986,5307.15
996,Matthew,Male,1/2/2013,10:33 PM,35203,18.040,False,Human Resources,Human Resources,Human Resources,HUMAN RESOURCES,7.0,"[Human, Resources]",7.0,H,2013,5280.45
997,Steven,Male,3/30/1980,9:20 PM,35095,8.379,True,Client Services,Client Services,Client Services,CLIENT SERVICES,6.0,"[Client, Services]",6.0,C,1980,5264.25
998,Kevin,Male,3/25/1982,7:31 AM,35061,5.128,False,Legal,Legal,Legal,LEGAL,5.0,[Legal],5.0,L,1982,5259.15
999,Michael,Male,7/30/1993,5:35 PM,35013,14.879,False,Product,Product,Product,PRODUCT,7.0,[Product],7.0,P,1993,5251.95

In [ ]:
indexing used to fast fetch the record as compared to other methods
row ko pinter assign kiya
like dictonary directly jump skipps other records

In [492]:
dfd.set_index("Team", inplace =True)

In [493]:
dfd

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,temp,bfill_Team,upper,name len,tsplit,namelen,username,year,sal_15
Team,,,,,,,,,,,,,,,,
Marketing,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,MARKETING,7.0,[Marketing],7.0,M,1993,14596.20
NaN,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Marketing,Finance,NaN,6.0,NaN,6.0,M,1996,9289.95
Finance,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,1993,19588.50
Finance,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,2005,20805.75
Client Services,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,CLIENT SERVICES,5.0,"[Client, Services]",5.0,C,1998,15150.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Distribution,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,DISTRIBUTION,5.0,[Distribution],5.0,D,2014,19872.45
Finance,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,FINANCE,7.0,[Finance],7.0,F,1984,6358.80
Product,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,PRODUCT,7.0,[Product],7.0,P,2013,14537.10
Business Development,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B,2013,9075.00
Sales,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,SALES,6.0,[Sales],6.0,S,2012,19492.35

In [495]:
dfd.loc[["Finance","Product"],:]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,temp,bfill_Team,upper,name len,tsplit,namelen,username,year,sal_15
Team,,,,,,,,,,,,,,,,
Finance,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,1993,19588.50
Finance,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,2005,20805.75
Finance,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,Finance,FINANCE,NaN,[Finance],NaN,F,2015,6885.90
Finance,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance,Finance,FINANCE,8.0,[Finance],8.0,F,1999,6213.90
Finance,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,2009,17219.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Product,Jonathan,Male,8/21/2013,12:45 AM,121797,16.923,False,Product,Product,PRODUCT,8.0,[Product],8.0,P,2013,18269.55
Product,Alice,Female,9/3/1988,8:54 PM,63571,15.397,True,Product,Product,PRODUCT,5.0,[Product],5.0,P,1988,9535.65
Product,Sarah,Female,12/4/1995,9:16 AM,124566,5.949,False,Product,Product,PRODUCT,5.0,[Product],5.0,P,1995,18684.90
Product,Ernest,Male,7/20/2013,6:41 AM,142935,13.198,True,Product,Product,PRODUCT,6.0,[Product],6.0,P,2013,21440.25
Product,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,PRODUCT,7.0,[Product],7.0,P,2013,14537.10

In [501]:
dfd.reset_index(inplace = True)

In [502]:
dfd

,Team,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,temp,bfill_Team,upper,name len,tsplit,namelen,username,year,sal_15
0,Marketing,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,Marketing,MARKETING,7.0,[Marketing],7.0,M,1993,14596.20
1,NaN,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,Marketing,Finance,NaN,6.0,NaN,6.0,M,1996,9289.95
2,Finance,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,1993,19588.50
3,Finance,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,Finance,FINANCE,5.0,[Finance],5.0,F,2005,20805.75
4,Client Services,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Client Services,CLIENT SERVICES,5.0,"[Client, Services]",5.0,C,1998,15150.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Distribution,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,Distribution,DISTRIBUTION,5.0,[Distribution],5.0,D,2014,19872.45
996,Finance,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Finance,FINANCE,7.0,[Finance],7.0,F,1984,6358.80
997,Product,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Product,PRODUCT,7.0,[Product],7.0,P,2013,14537.10
998,Business Development,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B,2013,9075.00
999,Sales,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Sales,SALES,6.0,[Sales],6.0,S,2012,19492.35

In [504]:
dfd.set_index("Team", inplace = True )

KeyError: "None of ['Team'] are in the columns"

In [505]:
dfd.sort_index()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,temp,bfill_Team,upper,name len,tsplit,namelen,username,year,sal_15
Team,,,,,,,,,,,,,,,,
Business Development,Michael,Male,5/22/2011,10:42 AM,73354,18.357,False,Business Development,Business Development,BUSINESS DEVELOPMENT,7.0,"[Business, Development]",7.0,B,2011,11003.10
Business Development,Robin,Female,10/1/2012,2:44 AM,41808,19.239,False,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B,2012,6271.20
Business Development,Maria,Female,3/14/2003,5:23 PM,96250,10.056,False,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B,2003,14437.50
Business Development,Harold,NaN,2/4/2004,11:02 AM,79459,7.776,True,Business Development,Business Development,BUSINESS DEVELOPMENT,6.0,"[Business, Development]",6.0,B,2004,11918.85
Business Development,Doris,Female,7/5/1993,5:54 PM,141439,3.799,False,Business Development,Business Development,BUSINESS DEVELOPMENT,5.0,"[Business, Development]",5.0,B,1993,21215.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,Mildred,Female,4/6/2007,10:06 PM,139284,11.390,True,Business Development,Finance,NaN,7.0,NaN,7.0,B,2007,20892.60
NaN,Phillip,NaN,10/20/2003,11:09 AM,89700,2.277,True,Finance,Finance,NaN,7.0,NaN,7.0,F,2003,13455.00
NaN,Ryan,Male,11/16/2012,1:47 PM,57292,6.010,False,Human Resources,Legal,NaN,4.0,NaN,4.0,H,2012,8593.80
NaN,Joe,Male,12/8/1998,10:28 AM,126120,1.020,False,Business Development,Marketing,NaN,3.0,NaN,3.0,B,1998,18918.00
NaN,NaN,Female,9/14/2010,5:19 AM,143638,9.662,NaN,Business Development,Human Resources,NaN,NaN,NaN,NaN,B,2010,21545.70

In [506]:
dfd.sort_index(ascending = False , inplace = True)

In [487]:
df2

   a  b  c
0  1  3  6
1  2  4  3
2  3  5  6

In [507]:
df3 = pd.DataFrame({"a":[11,12,13],
                     "b":[33,14,15],
                     "c":[16,13,None]
                    })

In [489]:
df2.add(df3)
#adds elementwise
#dim of both data frame should be same

    a   b   c
0  12  36  22
1  14  18  16
2  16  20  22

In [508]:
df3.add(df2)

    a   b     c
0  12  36  22.0
1  14  18  16.0
2  16  20   NaN

In [509]:
df2.sub(df3)

    a   b     c
0 -10 -30 -10.0
1 -10 -10 -10.0
2 -10 -10   NaN

In [510]:
df2.mul(df3)

    a   b     c
0  11  99  96.0
1  24  56  39.0
2  39  75   NaN

In [511]:
df2.div(df3)

          a         b         c
0  0.090909  0.090909  0.375000
1  0.166667  0.285714  0.230769
2  0.230769  0.333333       NaN

In [ ]:
on col we do transformtion- crate function -apply logic per/sal//prsal --per

join --sql table --df

In [ ]:
merge vs concat vs append
========================
pandas ------- append deprecated-remove--
append ch lkam ata concat karta

In [ ]:
merge ---sql joins

col --join

In [ ]:
two or more dataframe la join karnyastahi use concat

In [512]:
df4=pd.DataFrame({"id":[1,2,3],
                "name":['a','b','c'],
               "city":['p','q','r'] })

In [513]:
df5=pd.DataFrame({"id":[11,22,33],
                "name":['a1','b1','c1'],
               "city":['p','q','r'] })

In [515]:
pd.concat([df4,df5], axis = 0, ignore_index = True)

   id name city
0   1    a    p
1   2    b    q
2   3    c    r
3  11   a1    p
4  22   b1    q
5  33   c1    r

In [518]:
pd.concat([df4,df4,df4,df5,df2,df3])

     id name city     a     b     c
0   1.0    a    p   NaN   NaN   NaN
1   2.0    b    q   NaN   NaN   NaN
2   3.0    c    r   NaN   NaN   NaN
0   1.0    a    p   NaN   NaN   NaN
1   2.0    b    q   NaN   NaN   NaN
2   3.0    c    r   NaN   NaN   NaN
0   1.0    a    p   NaN   NaN   NaN
1   2.0    b    q   NaN   NaN   NaN
2   3.0    c    r   NaN   NaN   NaN
0  11.0   a1    p   NaN   NaN   NaN
1  22.0   b1    q   NaN   NaN   NaN
2  33.0   c1    r   NaN   NaN   NaN
0   NaN  NaN  NaN   1.0   3.0   6.0
1   NaN  NaN  NaN   2.0   4.0   3.0
2   NaN  NaN  NaN   3.0   5.0   6.0
0   NaN  NaN  NaN  11.0  33.0  16.0
1   NaN  NaN  NaN  12.0  14.0  13.0
2   NaN  NaN  NaN  13.0  15.0   NaN

In [522]:
df6=pd.DataFrame({'empid': [1,2,56,78,32],
                 "sal":[95,57,545,452,777],
                 "dept":['IT','HR','IT','Admin','Sales']})

In [520]:
df6

   id  sal   dept
0   1   95     IT
1   2   57     HR
2  56  545     IT
3  78  452  Admin
4  32  777  Sales

In [521]:
df4.merge(df6)
#innerjoin
#we didnt give col name which is coom 
#it took on it own

   id name city  sal dept
0   1    a    p   95   IT
1   2    b    q   57   HR

In [523]:
#if col name are diff
df4.merge(df6,left_on = 'id',right_on = "empid", how = 'left')

   id name city  empid   sal dept
0   1    a    p    1.0  95.0   IT
1   2    b    q    2.0  57.0   HR
2   3    c    r    NaN   NaN  NaN

In [524]:
df4.merge(df6,left_on = 'id',right_on = "empid", how = 'right')

    id name city  empid  sal   dept
0  1.0    a    p      1   95     IT
1  2.0    b    q      2   57     HR
2  NaN  NaN  NaN     56  545     IT
3  NaN  NaN  NaN     78  452  Admin
4  NaN  NaN  NaN     32  777  Sales

In [525]:
#bydefault inner join
df4.merge(df6,left_on = 'id',right_on = "empid")

   id name city  empid  sal dept
0   1    a    p      1   95   IT
1   2    b    q      2   57   HR

In [526]:
df4.merge(df6,left_on = 'id',right_on = "empid", how = 'outer')

    id name city  empid    sal   dept
0  1.0    a    p    1.0   95.0     IT
1  2.0    b    q    2.0   57.0     HR
2  3.0    c    r    NaN    NaN    NaN
3  NaN  NaN  NaN   32.0  777.0  Sales
4  NaN  NaN  NaN   56.0  545.0     IT
5  NaN  NaN  NaN   78.0  452.0  Admin

In [545]:
dfg=pd.read_csv(r"C:\Users\ASUS\Desktop\s\employees.csv")

In [546]:
test = dfg.groupby('Team')

In [547]:
test.get_group("Finance")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
46,Bruce,Male,11/28/2009,10:47 PM,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,7/27/1998,11:12 AM,137144,10.081,False,Finance
954,Joe,Male,1/19/1980,4:06 PM,119667,1.148,True,Finance
987,Gloria,Female,12/8/2014,5:08 AM,136709,10.331,True,Finance
992,Anthony,Male,10/16/2011,8:35 AM,112769,11.625,True,Finance
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance

In [532]:
test.agg({"Salary":"sum"})

                       Salary
Team
Business Development  9278498
Client Services       9351789
Distribution          7965042
Engineering           8672766
Finance               9406387
Human Resources       8275952
Legal                 7858718
Marketing             8862688
Product               8423223
Sales                 8664303

In [533]:
test.agg({"Salary":"max"}) 
#it gavwe max salary per team/dept

                      Salary
Team
Business Development  147417
Client Services       147183
Distribution          149105
Engineering           147362
Finance               149908
Human Resources       149903
Legal                 148985
Marketing             149456
Product               149684
Sales                 149654

In [534]:
test.agg({"Salary":"min"})

                      Salary
Team
Business Development   36844
Client Services        35095
Distribution           35575
Engineering            36946
Finance                35381
Human Resources        35203
Legal                  35061
Marketing              36643
Product                35013
Sales                  35802

In [540]:
test.agg({"Salary":"mean"}) 
#to calcularte avg

                            Salary
Team
Business Development  91866.316832
Client Services       88224.424528
Distribution          88500.466667
Engineering           94269.195652
Finance               92219.480392
Human Resources       90944.527473
Legal                 89303.613636
Marketing             90435.591837
Product               88665.505263
Sales                 92173.436170

In [ ]:
sum
min
max
len
in pandas thereis npo avg so import pandas n use mean to get avg

In [542]:
#method1 for count - of records
test.agg({"Salary":len})

                      Salary
Team
Business Development     101
Client Services          106
Distribution              90
Engineering               92
Finance                  102
Human Resources           91
Legal                     88
Marketing                 98
Product                   95
Sales                     94

In [550]:
#method 2
dfg['Team'].value_counts()

Team
Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
Name: count, dtype: int64

In [553]:
dfg[dfg['Gender']=='Female'].groupby("Team").agg({"Salary":"sum"})

                       Salary
Team
Business Development  4633453
Client Services       4148644
Distribution          3009142
Engineering           3973686
Finance               4056952
Human Resources       3462528
Legal                 3086873
Marketing             3802970
Product               3878219
Sales                 3502768

In [560]:
dfg.groupby("Team")["Salary"].max().nlargest(1)

Team
Finance    149908
Name: Salary, dtype: int64

In [561]:
dfg.groupby("Team").agg({"Salary":"max"})

                      Salary
Team
Business Development  147417
Client Services       147183
Distribution          149105
Engineering           147362
Finance               149908
Human Resources       149903
Legal                 148985
Marketing             149456
Product               149684
Sales                 149654

In [562]:
dfg.groupby("Team")["Salary"].max().idxmax()

'Finance'

In [ ]:
how to change data type of col
1] astype

2]to datetime

In [564]:
dfg.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [570]:
dfg['Salary'] = dfg['Salary'].astype(float)
#if u want to change the same col else give diff name

In [567]:
dfg

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933.0,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590.0,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

In [568]:
dfg.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary               float64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [571]:
dfg['Salary'] = dfg['Salary'].astype('float32')
#if u want to change the bit then

In [572]:
dfg.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary               float32
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [574]:
dfg['Salary'] = dfg['Salary'].astype('int64')

In [576]:
#startdate is object-string n so we cannot apply datetime
#operations cant run
dfg['new_date'] = pd.to_datetime(dfg['Start Date'])

In [577]:
dfg

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,new_date
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,1993-08-06
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,1996-03-31
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,1993-04-23
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,2005-03-04
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1998-01-24
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,2014-11-23
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,1984-01-31
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2013-05-20
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,2013-04-20
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,2012-05-15

In [578]:
dfg.dtypes

First Name                   object
Gender                       object
Start Date                   object
Last Login Time              object
Salary                        int64
Bonus %                     float64
Senior Management            object
Team                         object
new_date             datetime64[ns]
dtype: object

In [579]:
dfg['month'] = dfg['new_date'].dt.month

In [580]:
dfg

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,new_date,month
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,1993-08-06,8
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,1996-03-31,3
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,1993-04-23,4
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,2005-03-04,3
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1998-01-24,1
...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,2014-11-23,11
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,1984-01-31,1
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2013-05-20,5
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,2013-04-20,4
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,2012-05-15,5

In [581]:
dfg['year'] = dfg['new_date'].dt.year

In [582]:
dfg

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,new_date,month,year
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,1993-08-06,8,1993
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,1996-03-31,3,1996
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,1993-04-23,4,1993
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,2005-03-04,3,2005
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1998-01-24,1,1998
...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,2014-11-23,11,2014
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,1984-01-31,1,1984
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2013-05-20,5,2013
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,2013-04-20,4,2013
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,2012-05-15,5,2012

In [583]:
dfg['day'] = dfg['new_date'].dt.day

In [584]:
dfg

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,new_date,month,year,day
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,1993-08-06,8,1993,6
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,1996-03-31,3,1996,31
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,1993-04-23,4,1993,23
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,2005-03-04,3,2005,4
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,1998-01-24,1,1998,24
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,2014-11-23,11,2014,23
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,1984-01-31,1,1984,31
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,2013-05-20,5,2013,20
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,2013-04-20,4,2013,20
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,2012-05-15,5,2012,15

In [ ]:
JAN

January

dd mm  yyyy
dd mm yy
etc
directives 
in documnetation
https://docs.python.org/3/library/datetime.html

In [585]:
dfg['new_date'].dt.strftime('%d-%m-%y')

0      06-08-93
1      31-03-96
2      23-04-93
3      04-03-05
4      24-01-98
         ...
995    23-11-14
996    31-01-84
997    20-05-13
998    20-04-13
999    15-05-12
Name: new_date, Length: 1000, dtype: object

In [587]:
dfg['new_date'].dt.strftime('%Y-%b-%d %I:%H %p')

0      1993-Aug-06 12:00 AM
1      1996-Mar-31 12:00 AM
2      1993-Apr-23 12:00 AM
3      2005-Mar-04 12:00 AM
4      1998-Jan-24 12:00 AM
               ...
995    2014-Nov-23 12:00 AM
996    1984-Jan-31 12:00 AM
997    2013-May-20 12:00 AM
998    2013-Apr-20 12:00 AM
999    2012-May-15 12:00 AM
Name: new_date, Length: 1000, dtype: object

In [588]:
import datetime

In [589]:
filename = 'copper_daily_{}.csv'
filename.format(datetime.datetime.now())

'copper_daily_2026-08-08 00:19:37.293236.csv'

In [590]:
dfg['todays'] = datetime.datetime.now()

In [592]:
dfg['todays'].dt.strftime('%Y-%b-%d %I:%H %p')

0      2026-Aug-08 12:00 AM
1      2026-Aug-08 12:00 AM
2      2026-Aug-08 12:00 AM
3      2026-Aug-08 12:00 AM
4      2026-Aug-08 12:00 AM
               ...
995    2026-Aug-08 12:00 AM
996    2026-Aug-08 12:00 AM
997    2026-Aug-08 12:00 AM
998    2026-Aug-08 12:00 AM
999    2026-Aug-08 12:00 AM
Name: todays, Length: 1000, dtype: object

In [1]:
event = {'Records': [{'eventVersion': '2.5', 'eventSource': 'aws:s3', 'awsRegion': 'ap-south-1', 'eventTime': '2026-09-08T10:50:43.164Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'A2QABJ4OT1HH7N'}, 'requestParameters': {'sourceIPAddress': '223.233.82.96'}, 'responseElements': {'x-amz-request-id': '4S3GHJJD0AJ9P6JB', 'x-amz-id-2': 'TO0owD4T+F2ziMAwgf5uDlYHJE/VnRKT2X60CdW7lEqzLiZIiRy6HdEdbNSFkZ5LqTcZN9bhvbIisXp6NfTTMdZzYoNE5zqWDcKDgKT4XDY='}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': '48dd222c-559f-4a5e-87b6-402fd18f79a0', 'bucket': {'name': 'filesdumpsins3-automaticallytrigger', 'ownerIdentity': {'principalId': 'A2QABJ4OT1HH7N'}, 'arn': 'arn:aws:s3:::filesdumpsins3-automaticallytrigger'}, 'object': {'key': 'emp.json', 'size': 6659, 'eTag': 'de39c17594c0288a1595bd8d36dfc308', 'sequencer': '006A9FE88324D16300'}}}]}

In [2]:
event

{'Records': [{'eventVersion': '2.5',
   'eventSource': 'aws:s3',
   'awsRegion': 'ap-south-1',
   'eventTime': '2026-09-08T10:50:43.164Z',
   'eventName': 'ObjectCreated:Put',
   'userIdentity': {'principalId': 'A2QABJ4OT1HH7N'},
   'requestParameters': {'sourceIPAddress': '223.233.82.96'},
   'responseElements': {'x-amz-request-id': '4S3GHJJD0AJ9P6JB',
    'x-amz-id-2': 'TO0owD4T+F2ziMAwgf5uDlYHJE/VnRKT2X60CdW7lEqzLiZIiRy6HdEdbNSFkZ5LqTcZN9bhvbIisXp6NfTTMdZzYoNE5zqWDcKDgKT4XDY='},
   's3': {'s3SchemaVersion': '1.0',
    'configurationId': '48dd222c-559f-4a5e-87b6-402fd18f79a0',
    'bucket': {'name': 'filesdumpsins3-automaticallytrigger',
     'ownerIdentity': {'principalId': 'A2QABJ4OT1HH7N'},
     'arn': 'arn:aws:s3:::filesdumpsins3-automaticallytrigger'},
    'object': {'key': 'emp.json',
     'size': 6659,
     'eTag': 'de39c17594c0288a1595bd8d36dfc308',
     'sequencer': '006A9FE88324D16300'}}}]}

In [13]:
bucketname = event['Records'][0]['s3']['bucket']['name']
filenamr = event['Records'][0]['s3']['object']['key']

In [15]:
bucketname
filenamr

'emp.json'

In [4]:
filenamr = event['Records'][0]['s3']['object']['key']

'emp.json'